### ISSUE TITLE
Docker swarm ignores filters on a containers label when getting events

### ISSUE THREAD

**Issue by cainjonm** [docker/swarm#2466] opened 2016-08-25 02:42 UTC
If I run the following (where swarm is running on :4000)

`docker -H :4000 events -f label=foo=bar`
then
`docker -H :4000 run busybox`

the events command will output events for this run command, even though the label 'foo=bar' does not exist.

looking at api/events.go and api/handlers.go (if these are the correct places) - it looks like any filtering other than `until` is not supported? But this doesn't seem to be explicitly documented.

`Server Version: swarm/1.2.5`

**Comment by michelvocks** [comment] 2016-09-16 20:34
I was able to reproduce it. Docker swarm version 1.2.5 / docker 1.13.0 from master.

**Comment by nishanttotla** [comment] 2018-02-05 23:21
Closing this, dupe of https://github.com/docker/swarm/issues/2390.

**Closed by nishanttotla** 2018-02-05 23:21 UTC
Labels: area/event
