### ISSUE TITLE
Network Inspect API Missing Containers

### ISSUE THREAD

**Issue by tacchino** [docker/swarm#1681] opened 2016-01-25 21:11 UTC
When using the Swarm API endpoint an inspect call for an overlay network with an attached container returns an empty container list. If that call is instead made against the Docker engine API endpoint that the container is running on the container is returned as expected.

**Comment by vieux** [comment] 2016-01-26 00:29
@tacchino can you provide steps to reproduce easily ? thanks

**Comment by tacchino** [comment] 2016-01-26 13:41
@vieux Sure, I'll give you what I'm running.

* Set up multi-node Swarm cluster (I used three VirtualBox VMs each running a Swarm manager container and a Swarm worker container along with a 4th VM running an etcd container)
* Using the a manager containers API endpoint
  * Create an overlay network
  * Launch a container into the cluster
  * Connect the container to the overlay network (/networkid/connect)
  * Inspect the network (/networkid/inspect)

Expected result: Inspect returns a list of containers including the container attached above
Actual result: Inspect returns an empty list

This was run with swarm:latest (1.0.1)

Let me know if you need more than that, happy to help.

**Comment by vieux** [comment] 2016-01-26 22:41
@tacchino can you confirm that if you start the container directly on the network (with --net <NETWORK>) you see it in inspect ?

**Comment by tacchino** [comment] 2016-01-27 10:00
@vieux I'm using the API directly not the CLI. I'm not seeing an option in /containers/create to add in networking config although looking at the CLI code it looks like it might be using a NetworkingConfig data structure. Is there a documentation hole?

**Comment by dvenza** [comment] 2016-01-29 09:02
Hi, I have the same problem.

I run a new container (via the commandline) passing the option --net=testnet, network inspect says there are no containers:
```
$ docker -H bf12:2380 network inspect testnet
[
    {
        "Name": "testnet",
        "Id": "7c11dbc0e3e04fe1e198e9a43f11188bd27e95301292192e9c25fdcb1902914a",
        "Scope": "global",
        "Driver": "overlay",
        "IPAM": {
            "Driver": "default",
            "Config": [
                {}
            ]
        },
        "Containers": {},
        "Options": {}
    }
]
```
If I inspect the container just started:
```
$ docker -H bf12:2380 inspect web2
[...]
        "Networks": {
            "testnet": {
                "EndpointID": "a320f6dbfc418fd21bbfef37327fd5f1c9b7b3a7a50d004cc0565690ea37abf5",
                "Gateway": "",
                "IPAddress": "10.0.0.2",
                "IPPrefixLen": 24,
                "IPv6Gateway": "",
                "GlobalIPv6Address": "",
                "GlobalIPv6PrefixLen": 0,
                "MacAddress": "02:42:0a:00:00:02"
            }
        }
[...]
```

**Comment by dvenza** [comment] 2016-01-29 09:26
Version info (latest available on Ubuntu):
`Docker version 1.9.1, build a34a1d5`

```
$ docker pull swarm
Using default tag: latest
latest: Pulling from library/swarm
Digest: sha256:c21fd414b0488637b1f05f13a59b032a3f9da5d818d31da1a4ca98a84c0c781b
Status: Image is up to date for swarm:latest
```

**Comment by vieux** [comment] 2016-01-30 01:28
@dvenza yes this is a known bug in swarm 1.0.1 can you pleas try with the latest RC ?

`docker pull swarm:1.1.0-rc2`

Thanks

**Comment by amitshukla** [comment] 2016-02-04 17:58
@dvenza did rc2 or rc3 fix the issue?

**Comment by dvenza** [comment] 2016-02-17 12:49
I cannot reproduce this bug on swarm 1.1.0.

Thanks

**Comment by abronan** [comment] 2016-02-17 16:57
Closing this one, thanks for reporting.

**Closed by abronan** 2016-02-17 16:57 UTC
Labels: area/API, area/network, kind/question
