### ISSUE TITLE
403 error attempting to create swarm token

### ISSUE THREAD

**Issue by nathanleclaire** [docker/swarm#1304] opened 2015-10-15 23:00 UTC
On my DigitalOcean droplet (ostensibly in SFO1 datacenter):

```console
$ docker run swarm:latest create
... pull ...
<html><body><h1>403 Forbidden</h1>
Since Docker is a US company, we must comply with us export control regulations. In an effort to comply with these, we now block all IP addresses that are located in Cuba, Iran, North Korea, Sudan, and Syria. If you are not in one of these countries and are blocked, please reach out to https://support.docker.com
</body></html>
```

Hey, I'm not in Iran y'all!!

cc @abronan @vieux @aluzzardi

**Comment by nathanleclaire** [comment] 2015-10-15 23:02
Works fine directly from my VM in the SF office though.

**Comment by anweiss** [comment] 2015-10-15 23:03
+1 getting same error here...running on Azure VM

**Comment by abronan** [comment] 2015-10-15 23:05
This error is hilarious :smile: 

Y'all in Cuba just admit it.

We'll look into it and try from some provider's VM to see if we run into the same issue.

**Comment by xbglowx** [comment] 2015-10-15 23:10
Taking a look at the geoip blocking

**Comment by abronan** [comment] 2015-10-15 23:12
thanks @xbglowx

**Comment by xbglowx** [comment] 2015-10-15 23:14
Is this still happening for everyone?

**Comment by abronan** [comment] 2015-10-15 23:15
@nathanleclaire @anweiss Can you retry and see if that works?

**Comment by xbglowx** [comment] 2015-10-15 23:19
The problem is still there. Seems your swam endpoints are hitting our staging environment.

**Comment by xbglowx** [comment] 2015-10-15 23:21
I found the problem. Should be fix for all in stage. Good thing I didn't push this change out to prod yet.

**Comment by nathanleclaire** [comment] 2015-10-15 23:24
Looks good on my end now

**Comment by abronan** [comment] 2015-10-15 23:24
Nice :+1: 

Closing. Thanks @xbglowx !

**Closed by abronan** 2015-10-15 23:24 UTC
Labels: area/discovery, kind/bug

**Comment by nathanleclaire** [comment] 2015-10-15 23:36
:+1:

**Comment by Yam408** [comment] 2015-10-16 05:06
√

**Comment by MrAta** [comment] 2016-03-06 09:53
hey dudes! im from iran and need to use docker for my research!
Open source communities never make sanctions against any country! because it is in contradiction with their brand:"free knowledge"
so why docker does so?
its like a joke! its a disaster for me and my friend that we can't access docker hub from iran!
if you search a little and see your around, you would find that iran is far different from other countries like syria , sudan and north korea!
i never support iran's government policies about the world and vice versa! because knowledge and science is holy. and politics are very low level in counter with science and knowledge to cause an impact on science and knowledge so that it couldn't be used by all.
so im sorry for all who made this absorb decision.

**Comment by clacki** [comment] 2016-03-15 23:21
hi guys ...
i have this problem too.
anybody can fix this problem ?

دوستان عزیز این مشکل چطوری میشه رفع کرد .
داکر لازمم نمیدونم چی کار کنم ...
همه جا هنوز ما تحریمیم ؟

**Comment by MrAta** [comment] 2016-03-16 05:15
hi @clacki 
We've used proxy servers. that is we have another server abroad and by using shadow socks proxy and polipo we created a tunnel and then we could pull from docker's hub.
[this](https://github.com/noNameFa/linuxProxyTutorial) is a great tut. hope be helpful.
