### ISSUE TITLE
swarm create failed on Fedora 22

### ISSUE THREAD

**Issue by dove-young** [docker/swarm#1070] opened 2015-07-17 08:05 UTC
Here is the swarm image
```
[root@tivx93 ~]# docker  images
REPOSITORY                   TAG                  IMAGE ID            CREATED             VIRTUAL SIZE
docker.io/swarm              latest               446e413bd987        3 days ago          10.28 MB

````
Here is the failing message
````
[root@tivx93 sysconfig]# docker run --rm swarm create
Timestamp: 2015-07-17 22:30:59.141267172 +0800 CST
Code: System error

Message: [/usr/bin/tar -cf /var/lib/docker/tmp/0d95e38524c70e56af287e4ca53346b83144adfd679987c2a0926290d3673d78804048592/_tmp.tar -C /var/lib/docker/overlay/0d95e38524c7
0e56af287e4ca53346b83144adfd679987c2a0926290d3673d78/merged/tmp .] failed: /usr/bin/tar: /var/lib/docker/overlay/0d95e38524c70e56af287e4ca53346b83144adfd679987c2a0926290
d3673d78/merged/tmp: Cannot open: No such file or directory
/usr/bin/tar: Error is not recoverable: exiting now
: exit status 2

Frames:
---
0: setupRootfs
Package: github.com/docker/libcontainer
File: rootfs_linux.go@30
---
1: Init
Package: github.com/docker/libcontainer.(*linuxStandardInit)
File: standard_init_linux.go@52
---
2: StartInitialization
Package: github.com/docker/libcontainer.(*LinuxFactory)
File: factory_linux.go@223
---
3: initializer
Package: github.com/docker/docker/daemon/execdriver/native
File: init.go@35
---
4: Init
Package: github.com/docker/docker/pkg/reexec
File: reexec.go@26
---
5: main
Package: main
File: docker.go@29
---
6: main
Package: runtime
File: proc.go@63
---
---                                                                                                                                                             [12/2262]
7: goexit
Package: runtime
File: asm_amd64.s@2232
FATA[0000] Error response from daemon: : exit status 2  
[root@tivx93 sysconfig]# 
[root@tivx93 sysconfig]# 
[root@tivx93 sysconfig]# 
[root@tivx93 sysconfig]# setproxy
[root@tivx93 sysconfig]# 
[root@tivx93 sysconfig]# 
[root@tivx93 sysconfig]# docker run --rm swarm create
Timestamp: 2015-07-17 22:31:13.756778645 +0800 CST
Code: System error

Message: [/usr/bin/tar -cf /var/lib/docker/tmp/76709c3ed4b44d151df15f07afe1e759eacb1830a0107443ef2377e381412fcd776929775/_tmp.tar -C /var/lib/docker/overlay/76709c3ed4b4
4d151df15f07afe1e759eacb1830a0107443ef2377e381412fcd/merged/tmp .] failed: /usr/bin/tar: /var/lib/docker/overlay/76709c3ed4b44d151df15f07afe1e759eacb1830a0107443ef2377e3
81412fcd/merged/tmp: Cannot open: No such file or directory
/usr/bin/tar: Error is not recoverable: exiting now
: exit status 2

Frames:
---
0: setupRootfs
Package: github.com/docker/libcontainer
File: rootfs_linux.go@30
---
1: Init
Package: github.com/docker/libcontainer.(*linuxStandardInit)
File: standard_init_linux.go@52
---
2: StartInitialization
Package: github.com/docker/libcontainer.(*LinuxFactory)
File: factory_linux.go@223
---
3: initializer
Package: github.com/docker/docker/daemon/execdriver/native
File: init.go@35
---
4: Init
Package: github.com/docker/docker/pkg/reexec
File: reexec.go@26
---
---
5: main
Package: main
File: docker.go@29
---
6: main
Package: runtime
File: proc.go@63
---
7: goexit
Package: runtime
File: asm_amd64.s@2232
FATA[0000] Error response from daemon: : exit status 2  
[root@tivx93 sysconfig]# 
````

But docker daemon works well. 

````
[root@tivx93 sysconfig]# docker run -d fedora/php:4.2.8 tail -f /dev/null
22c9f23b4f1b00fff4263bf677acaa83da47a75fa7cc6af466de4012f510e3c3
[root@tivx93 sysconfig]# docker ps 
CONTAINER ID        IMAGE               COMMAND               CREATED             STATUS              PORTS               NAMES
22c9f23b4f1b        fedora/php:4.2.8    "tail -f /dev/null"   4 seconds ago       Up 3 seconds                            tender_bohr         
[root@tivx93 sysconfig]#
````

**Comment by dove-young** [comment] 2015-07-17 08:29
I pulled swarm:0.3.0 and tried again on my laptop. It still failed.

````
->  docker run --rm swarm:0.3.0 create
Timestamp: 2015-07-17 16:27:36.632810861 +0800 CST
Code: System error

Message: [/usr/bin/tar -cf /var/lib/docker/tmp/f268cb9dea805c3fe1befbac77f47cbe65e4dcfaf46a62fc390e70d7c63d281d504874775/_tmp.tar -C /var/lib/docker/overlay/f268cb9dea805c3fe1befbac77f47cbe65e4dcfaf46a62fc390e70d7c63d281d/merged/tmp .] failed: /usr/bin/tar: /var/lib/docker/overlay/f268cb9dea805c3fe1befbac77f47cbe65e4dcfaf46a62fc390e70d7c63d281d/merged/tmp: Cannot open: No such file or directory
/usr/bin/tar: Error is not recoverable: exiting now
: exit status 2

Frames:
---
0: setupRootfs
Package: github.com/docker/libcontainer
File: rootfs_linux.go@30
---
1: Init
Package: github.com/docker/libcontainer.(*linuxStandardInit)
File: standard_init_linux.go@52
---
2: StartInitialization
Package: github.com/docker/libcontainer.(*LinuxFactory)
File: factory_linux.go@223
---
3: initializer
Package: github.com/docker/docker/daemon/execdriver/native
File: init.go@35
---
4: Init
Package: github.com/docker/docker/pkg/reexec
File: reexec.go@26FATA[0000] Error response from daemon: : exit status 2  
 10116 + 16:27:36 + ~ 
````

**Comment by bpradipt** [comment] 2015-07-20 14:16
@dove-young this seems to be duplicate of - https://github.com/docker/swarm/issues/781

**Comment by abronan** [comment] 2015-07-20 15:46
@dove-young It is indeed a duplicate of the issue referenced in the comment above (thanks for spotting this @bpradipt). I'll close this one but feel free to continue the discussion in #781.

**Closed by abronan** 2015-07-20 15:46 UTC
Labels: kind/duplicate
