### ISSUE TITLE
/info api returns incorrect label of node

### ISSUE THREAD

**Issue by xinxian0458** [docker/swarm#2452] opened 2016-08-18 10:35 UTC
I have two nodes in the cluster, and each has label `role==master, role==slave, role==publicslave`, but when I call swarm api via `curl -i --cacert ./ca.pem --cert ./cert.pem --key ./key.pem  https://52.78.120.211:3376/info`, I only get label `role=publicslave`. 

>docker daemon response

``` json
{
  "ID": "DRIJ:R5TQ:PCZK:AF3A:ATN6:KBPQ:WN33:AZF4:XKRB:UMNY:QWNY:T7QR",
  "Containers": 2,
  "ContainersRunning": 2,
  "ContainersPaused": 0,
  "ContainersStopped": 0,
  "Images": 1,
  "Driver": "devicemapper",
  "DriverStatus": [
    [
      "Pool Name",
      "docker-202:2-419438502-pool"
    ],
    [
      "Pool Blocksize",
      "65.54 kB"
    ],
    [
      "Base Device Size",
      "10.74 GB"
    ],
    [
      "Backing Filesystem",
      "xfs"
    ],
    [
      "Data file",
      "/dev/loop0"
    ],
    [
      "Metadata file",
      "/dev/loop1"
    ],
    [
      "Data Space Used",
      "48.23 MB"
    ],
    [
      "Data Space Total",
      "107.4 GB"
    ],
    [
      "Data Space Available",
      "105.4 GB"
    ],
    [
      "Metadata Space Used",
      "688.1 kB"
    ],
    [
      "Metadata Space Total",
      "2.147 GB"
    ],
    [
      "Metadata Space Available",
      "2.147 GB"
    ],
    [
      "Thin Pool Minimum Free Space",
      "10.74 GB"
    ],
    [
      "Udev Sync Supported",
      "true"
    ],
    [
      "Deferred Removal Enabled",
      "false"
    ],
    [
      "Deferred Deletion Enabled",
      "false"
    ],
    [
      "Deferred Deleted Device Count",
      "0"
    ],
    [
      "Data loop file",
      "/var/lib/docker/devicemapper/devicemapper/data"
    ],
    [
      "Metadata loop file",
      "/var/lib/docker/devicemapper/devicemapper/metadata"
    ],
    [
      "Library Version",
      "1.02.107-RHEL7 (2016-06-09)"
    ]
  ],
  "SystemStatus": null,
  "Plugins": {
    "Volume": [
      "local"
    ],
    "Network": [
      "host",
      "bridge",
      "null",
      "overlay"
    ],
    "Authorization": null
  },
  "MemoryLimit": true,
  "SwapLimit": true,
  "KernelMemory": true,
  "CpuCfsPeriod": true,
  "CpuCfsQuota": true,
  "CPUShares": true,
  "CPUSet": true,
  "IPv4Forwarding": true,
  "BridgeNfIptables": false,
  "BridgeNfIp6tables": false,
  "Debug": false,
  "NFd": 32,
  "OomKillDisable": true,
  "NGoroutines": 66,
  "SystemTime": "2016-08-18T06:05:21.111491125-04:00",
  "ExecutionDriver": "",
  "LoggingDriver": "json-file",
  "CgroupDriver": "cgroupfs",
  "NEventsListener": 1,
  "KernelVersion": "4.4.1-1.el7.elrepo.x86_64",
  "OperatingSystem": "Red Hat Enterprise Linux Server 7.2 (Maipo)",
  "OSType": "linux",
  "Architecture": "x86_64",
  "IndexServerAddress": "https://index.docker.io/v1/",
  "RegistryConfig": {
    "InsecureRegistryCIDRs": [
      "127.0.0.0/8"
    ],
    "IndexConfigs": {
      "docker.io": {
        "Name": "docker.io",
        "Mirrors": null,
        "Secure": true,
        "Official": true
      }
    },
    "Mirrors": null
  },
  "NCPU": 2,
  "MemTotal": 8370114560,
  "DockerRootDir": "/var/lib/docker",
  "HttpProxy": "",
  "HttpsProxy": "",
  "NoProxy": "",
  "Name": "jessie01",
  "Labels": [
    "role=master",
    "role=slave",
    "role=publicslave",
    "provider=amazonec2"
  ],
  "ExperimentalBuild": false,
  "ServerVersion": "1.12.0",
  "ClusterStore": "consul://52.78.61.56:8500",
  "ClusterAdvertise": "172.31.8.122:2376",
  "SecurityOptions": [
    "seccomp"
  ],
  "Runtimes": {
    "runc": {
      "path": "docker-runc"
    }
  },
  "DefaultRuntime": "runc",
  "Swarm": {
    "NodeID": "",
    "NodeAddr": "",
    "LocalNodeState": "inactive",
    "ControlAvailable": false,
    "Error": "",
    "RemoteManagers": null,
    "Nodes": 0,
    "Managers": 0,
    "Cluster": {
      "ID": "",
      "Version": {},
      "CreatedAt": "0001-01-01T00:00:00Z",
      "UpdatedAt": "0001-01-01T00:00:00Z",
      "Spec": {
        "Orchestration": {},
        "Raft": {},
        "Dispatcher": {},
        "CAConfig": {},
        "TaskDefaults": {}
      }
    }
  },
  "LiveRestoreEnabled": false
}
```

> swarm response

``` json
{
  "ID": "",
  "Containers": 3,
  "ContainersRunning": 3,
  "ContainersPaused": 0,
  "ContainersStopped": 0,
  "Images": 2,
  "Driver": "",
  "DriverStatus": null,
  "SystemStatus": [
    [
      "Role",
      "primary"
    ],
    [
      "Strategy",
      "spread"
    ],
    [
      "Filters",
      "health, port, dependency, affinity, constraint"
    ],
    [
      "Nodes",
      "2"
    ],
    [
      " jessie01",
      "52.78.120.211:2376"
    ],
    [
      "  └ Status",
      "Healthy"
    ],
    [
      "  └ Containers",
      "2"
    ],
    [
      "  └ Reserved CPUs",
      "0 / 2"
    ],
    [
      "  └ Reserved Memory",
      "0 B / 8.185 GiB"
    ],
    [
      "  └ Labels",
      "executiondriver=, kernelversion=4.4.1-1.el7.elrepo.x86_64, operatingsystem=Red Hat Enterprise Linux Server 7.2 (Maipo), provider=amazonec2, role=publicslave, storagedriver=devicemapper"
    ],
    [
      "  └ Error",
      "(none)"
    ],
    [
      "  └ UpdatedAt",
      "2016-08-18T10:23:31Z"
    ],
    [
      " jessie02",
      "52.78.23.105:2376"
    ],
    [
      "  └ Status",
      "Healthy"
    ],
    [
      "  └ Containers",
      "1"
    ],
    [
      "  └ Reserved CPUs",
      "0 / 2"
    ],
    [
      "  └ Reserved Memory",
      "0 B / 8.185 GiB"
    ],
    [
      "  └ Labels",
      "executiondriver=, kernelversion=4.4.1-1.el7.elrepo.x86_64, operatingsystem=Red Hat Enterprise Linux Server 7.2 (Maipo), provider=amazonec2, role=publicslave, storagedriver=devicemapper"
    ],
    [
      "  └ Error",
      "(none)"
    ],
    [
      "  └ UpdatedAt",
      "2016-08-18T10:23:21Z"
    ]
  ],
  "Plugins": {
    "Volume": null,
    "Network": null,
    "Authorization": null
  },
  "MemoryLimit": true,
  "SwapLimit": true,
  "CpuCfsPeriod": true,
  "CpuCfsQuota": true,
  "CPUShares": true,
  "CPUSet": true,
  "IPv4Forwarding": true,
  "BridgeNfIptables": true,
  "BridgeNfIp6tables": true,
  "Debug": false,
  "NFd": 0,
  "OomKillDisable": true,
  "NGoroutines": 0,
  "SystemTime": "2016-08-18T10:24:10.915295251Z",
  "ExecutionDriver": "",
  "LoggingDriver": "",
  "NEventsListener": 0,
  "KernelVersion": "4.4.1-1.el7.elrepo.x86_64",
  "OperatingSystem": "linux",
  "OSType": "",
  "Architecture": "amd64",
  "IndexServerAddress": "",
  "RegistryConfig": null,
  "NCPU": 4,
  "MemTotal": 17577240576,
  "DockerRootDir": "",
  "HttpProxy": "",
  "HttpsProxy": "",
  "NoProxy": "",
  "Name": "ebcca3b48c56",
  "Labels": null,
  "ExperimentalBuild": false,
  "ServerVersion": "",
  "ClusterStore": "",
  "ClusterAdvertise": ""
}
```
>

**Comment by dongluochen** [comment] 2016-08-18 17:38
Swarm treats Engine labels as key-value pairs. Only one value is stored in Swarm for one key. This key-value pair in Swarm is used to select node for a container to run. For example, some containers should be run on nodes with SSD. See https://docs.docker.com/swarm/scheduler/filter/.

**Comment by dongluochen** [comment] 2016-08-24 03:08
This is intended behavior. Closing this issue.

**Closed by dongluochen** 2016-08-24 03:08 UTC
Labels: kind/question
