### ISSUE TITLE
mesos: Abnormal executor termination

### ISSUE THREAD

**Issue by ahmetalpbalkan** [docker/swarm#1177] opened 2015-08-29 01:09 UTC
```
$ docker info

Containers: 2
Images: 2
Storage Driver:
Role: primary
Strategy: spread
Filters: affinity, health, constraint, port, dependency
Offers: 2
  Offer: 20150828-223151-100663306-5050-5917-O28
   └ cpus: 2
   └ mem: 2.359 GiB
   └ disk: 23.8 GiB
   └ ports: 31000-32000
  Offer: 20150828-223151-100663306-5050-5917-O34
   └ cpus: 2
   └ mem: 2.359 GiB
   └ disk: 23.8 GiB
   └ ports: 31000-32000
Execution Driver:
Kernel Version:
Operating System:
CPUs: 4
Total Memory: 4.719 GiB
Name: c7859bdee91d
ID:
Http Proxy:
Https Proxy:
No Proxy:

```

```
$ docker run -i -t -m 200 -c 1 busybox sleep 9999999
FATA[0000] Error response from daemon: Abnormal executor termination
```

any ideas what might be going on here?

I see failed tasks on mesos master UI after running this a few times:

![image](https://cloud.githubusercontent.com/assets/159209/9559813/da48a77e-4daf-11e5-992d-77395709139d.png)

**Comment by rgardler** [comment] 2015-08-30 02:13
I know @ahmetalpbalkan and I are trying to do the same thing and I'm seeing the same problem. 

The Mesos slave logs are empty, though there is evidence that a request was received. 

rgardler@acs-1:~$ ls -l /tmp/mesos/slaves/20150830-002657-117440522-505 0-7896-S2/frameworks/20150830-002657-117440522-5050-7896-0000/executors /
total 20
drwxr-xr-x 3 root root 4096 Aug 30 01:44 3da44d93dca6
drwxr-xr-x 3 root root 4096 Aug 30 01:45 6252d1231063
drwxr-xr-x 3 root root 4096 Aug 30 01:45 648b95fca2d3
drwxr-xr-x 3 root root 4096 Aug 30 00:28 7894008d1a8f
drwxr-xr-x 3 root root 4096 Aug 30 02:09 f23168a0cffc

rgardler@acs-1:~$ cat /tmp/mesos/slaves/20150830-002657-117440522-5050- 7896-S2/frameworks/20150830-002657-117440522-5050-7896-0000/executors/f 23168a0cffc/runs/latest/stderr
rgardler@acs-1:~$ cat /tmp/mesos/slaves/20150830-002657-117440522-5050- 7896-S2/frameworks/20150830-002657-117440522-5050-7896-0000/executors/f 23168a0cffc/runs/latest/stdout
rgardler@acs-1:~$

Still digging...

**Comment by tnachen** [comment] 2015-08-30 02:18
You're looking at the sandbox logs but I think you'll find the actual problem of the executor in the Mesos slave log. Usually there might be a user problem, where swarm is launched by a user and Mesos tries to impersonate that user on the slave but can't find it. If that's the case you can use SWARM_MESOS_USER env variable (e.g: SWARM_MESOS_USER=root)

**Comment by rgardler** [comment] 2015-08-30 02:46
Thanks @tnachen that helps point me in the right direction, though I've not resolved it yet... (but now I know of another source of useful logs):

rgardler@acs-1:~$ cat /var/log/mesos/mesos-slave.ERROR
Log file created at: 2015/08/30 02:09:09
Running on machine: acs-1
Log line format: [IWEF]mmdd hh:mm:ss.uuuuuu threadid file:line] msg
E0830 02:09:09.269501 35183 slave.cpp:3258] Container '524076e6-91d3-4950-a553-257579ed422b' for executor 'f23168a0cffc' of framework '20150830-002657-117440522-5050-7896-0000' failed to start: Failed to create container: Failed to chown: Failed to get user information for '': Success
E0830 02:09:09.269963 35183 slave.cpp:3340] Termination of executor 'f23168a0cffc' of framework '20150830-002657-117440522-5050-7896-0000' failed: Unknown container: 524076e6-91d3-4950-a553-257579ed422b

Still digging...

**Comment by tnachen** [comment] 2015-08-30 05:20
Ah so go framework tried to get the current user but it couldn't, setting SWARM_MESOS_USER=root or some other user in the slave will fix this

**Comment by rgardler** [comment] 2015-08-30 18:55
Setting SWARM_MESOS_USER is not working for me. I am getting the same errors. I've confirmed that I am setting SWARM_MESOS_USER=root (on both master and slave, though if I understand you correctly I need only do it on the slaves).

Any other pointers?

**Comment by tnachen** [comment] 2015-08-30 18:59
Sorry you need to set it when you launch Swarm, nothing needs to change for master or slave

**Comment by rgardler** [comment] 2015-08-30 20:35
Ah-Ha! I feel I'm clawing my way up the learning curve. Thank you for your guidance. Running the Swarm container with '-e SWARM_MESOS_USER=root' did the trick.

@ahmetalpbalkan please verify this works for you and close this ticket.

**Comment by ahmetalpbalkan** [comment] 2015-08-30 20:37
Will do. This probably should be part of the documentation as we installed Mesos cluster from the standard tutorials (nearly all are the same) and yet this step was required. I'm guessing we're not the only ones hitting this.

**Comment by ahmetalpbalkan** [comment] 2015-08-30 20:47
Works for me as well. Here's my command:

```
docker run -d --restart=always \
    -e SWARM_MESOS_USER=root \
    -p 2375:2375 -p 3375:3375 swarm manage \
    -c mesos-experimental \
    --cluster-opt mesos.address=0.0.0.0 \
    --cluster-opt mesos.port=3375 mesos-master:5050
```

**Comment by ahmetalpbalkan** [comment] 2015-08-30 20:47
thanks @tnachen

**Closed** 2015-08-30 20:47 UTC
Labels: area/mesos, kind/question

**Comment by pires** [comment] 2017-04-21 04:48
FYI, this happens most probably because you are compiling in a system with no cgo support, e.g. cross-compiling with `GOOS=linux`. Mesos does take care of finding the user for your tasks but not when using the HTTP API, which is the case for mesos-go v0 API.

**Comment by pathakg** [comment] 2017-12-22 13:58
ran into same issue and I have update /etc/default/mesos-slave file, added MESOS_SWITCH_USER=0
& restarted the mesos-slave, this fixed the issue..
