### ISSUE TITLE
Swarm node is removed and then re-registered when deleting a container

### ISSUE THREAD

**Issue by programmerq** [docker/swarm#1393] opened 2015-11-09 23:12 UTC
I've been working on diagnosing the following issue:

-----------

> swarm v1.0.0 setup with the following machines, using a consul backend:
> 
> master IP Adress: 10.245.1.2 
> node1: name "compute", IP Address: 10.245.1.10 
> node2: name "compute1", IP Address: 10.245.1.11
> 
> We are interacting with the swarm using a docker client (i.e. via the REST API). In one of our workflows, we need to stop and remove a list of containers in a successive order (no concurrency). When more than one container exist on a given node, a previous stop container followed by a delete container will sometimes kick off the node from the cluster, causing successive calls to stop/delete containers to fail with a "No such container" error.

-----------

In my attempts to reproduce the "No such container" issue, I found the following setup was able to give me the same output:

I launched consul on one host, and then created a swarm cluster in digitalocean using the consul discovery backend.

I then launched 30 instances of bash running `docker run -e constraint:node==swarm-node04 --rm busybox` in a while loop.

Next, I null routed the consul server from swarm-node04. Once consul lost contact with the node, the bash processes started failing. One of the error messages was identical to the "No such container" output from the original issue.

------------

The null-routing consul test seems to show that a networking issue between a node and consul can cause this sort of failure where swarm loses awareness of a particular container.

Better handling of this sort of thing at the swarm level would be handy. Forcing downstream docker clients to do retries because of this sort of race condition is less than ideal. Unfortunately, the original error and behavior is something that is tricky to reproduce.

**Comment by dongluochen** [comment] 2015-11-12 02:38
@programmerq I'm not sure of your ask here. Swarm gets container information thru the nodes it manages. If a node is not in KV, in this case the node fails its connection with consul, swarm would not see this node when consul removes it. Swarm will not be able to list containers from this node.

**Comment by programmerq** [comment] 2015-11-12 19:35
After sleeping on this, I'm not as convinced that we definitely have a case that can be purely blamed on the network. Going back to the original issue, the "No such container" issue happens a small percentage of the time. It seems like consul takes longer to detect a failure than the 50-100 millisecond window where this message can occur.

Let me see if I can phrase it differently:

-----

When I use my docker client and point it to a swarm cluster, I have an expectation that I will have a similar experience. Sometimes when trying to call 'docker stop' on a container, I get a message that says it does not exist when it really does. A subsequent retry immediately after the failure, and it will work.

One workaround might be that I could change my docker API client to handle this behavior that seems to be specific to the swarm docker daemon API implementation. Unfortunately, none of the existing docker api clients seem to do any sort of retries, so this is not the most workable solution.

Since this sort of failure doesn't happen with a "normal" docker daemon, I believe that swarm may have a bug and this gap needs to be filled regardless of the underlying cause.

-----

Hopefully the intent is more clear?

**Comment by abronan** [comment] 2015-11-13 00:52
> The null-routing consul test seems to show that a networking issue between a node and consul can cause this sort of failure where swarm loses awareness of a particular container.

@programmerq This works as intended, if you shut down, lose contact with the store, cut the contact with the store yourself: Nodes are going to fail to renew their TTL on Consul and the Manager will ultimately be notified that those Nodes are not taking part in the cluster anymore (because as far as I understand, the Manager was still talking to Consul). All those Nodes are going to be removed from the Node list with all their containers Config (thus you will get those `container not found` errors where issuing any request on the cluster).

If the Manager was also denied the access to Consul, the Watch mechanism wouldn't trigger and the Nodes/containers Config would still be there (but you would not be able to add more nodes because the discovery is down).

We use `Consul`, `etcd` and `zookeeper` as the discovery mechanism for the nodes in the Cluster but also as a mean for nodes to `heartbeat` their presence in the Cluster.

I'll spin up a Consul cluster now and let it live for some time to see if there is any issue with the renew TTL process that would kick a node inadvertently.

Also can you try to reproduce with `etcd`? I'm sure the `rare` issue you are getting is when using Consul because of the TTL renew mechanism (which leaves a lingering Lock when communication is lost, deleting the entry when the TTL expires, resulting in the node being registered again after some time when it retries to take the Lock and renew the TTL session for that entry).

**Comment by thaJeztah** [comment] 2015-12-25 23:24
What's the status here? @programmerq have you tried to reproduce with `etcd`? @abronan any luck finding an issue in the TTL renew?

**Comment by abronan** [comment] 2016-01-04 21:22
I was not able to reproduce in normal usage scenario (and I had to run it quite extensively with Consul to fix another issue).

An issue with the TTL renew mechanism was fixed by #1545 but this concerns the Leader Election mechanism only and not discovery/Node registration.

@programmerq Feel free to comment here or open a new issue if you still encounter problems with Consul and if you are able to reproduce somehow (but without shutting down the connection to the store which would indeed result in nodes being kicked after some time. Intermittent connectivity issue will also trigger this behavior but that is more of a Consul issue).

Closing this in the meantime.

**Closed by abronan** 2016-01-04 21:22 UTC
