### ISSUE TITLE
Deploying an application unable to use a previously used port

### ISSUE THREAD

**Issue by arun-gupta** [docker/swarm#765] opened 2015-05-11 22:39 UTC
Created a cluster as:

```
docker run swarm create
docker-machine create -d virtualbox --swarm --swarm-master --swarm-discovery token://$TOKEN swarm-master
docker-machine create -d virtualbox --swarm --swarm-discovery token://$TOKEN swarm-node-01
docker-machine create -d virtualbox --swarm --swarm-discovery token://$TOKEN swarm-node-02
```

Deployed an application as:

```
eval $(docker-machine env --swarm swarm-master)
docker run -it -p 8080:8080 arungupta/javaee7-hol
```

Terminated the application by Ctrl+C. Trying to run the application again as:

```docker-recipes> docker run -p 8080:8080 -it arungupta/javaee7-hol```

It gives the error:

```
FATA[0000] Error response from daemon: unable to find a node with port 8080 available
```

`docker ps -a` shows:

```
docker-recipes> docker ps -a
CONTAINER ID        IMAGE                          COMMAND                CREATED             STATUS                            PORTS                                     NAMES
44b4addd1429        arungupta/javaee7-hol:latest   "/opt/jboss/wildfly/   4 minutes ago       Exited (130) About a minute ago                                             swarm-master/happy_mayer            
8edd5b7ff815        arungupta/javaee7-hol:latest   "/opt/jboss/wildfly/   4 minutes ago                                                                                   swarm-node-01/naughty_ardinghelli   
60efa0dca948        arungupta/javaee7-hol:latest   "/opt/jboss/wildfly/   6 minutes ago                                                                                   swarm-node-02/hopeful_wright        
12f6a35860f9        swarm:latest                   "/swarm join --addr    21 minutes ago      Up 20 minutes                     2375/tcp                                  swarm-node-02/swarm-agent           
caa60b4ec3fb        swarm:latest                   "/swarm join --addr    22 minutes ago      Up 22 minutes                     2375/tcp                                  swarm-node-01/swarm-agent           
5c4410190b15        swarm:latest                   "/swarm join --addr    29 minutes ago      Up 28 minutes                     2375/tcp                                  swarm-master/swarm-agent            
8c8f60299718        swarm:latest                   "/swarm manage --tls   29 minutes ago      Up 28 minutes                     2375/tcp, 192.168.99.101:3376->3376/tcp   swarm-master/swarm-agent-master     
```

Port 8080 is available for use and so the application should start.

**Comment by arun-gupta** [comment] 2015-05-11 23:05
Starting the application as:

```docker run -p 8081:8080 -it arungupta/javaee7-hol```

starts up well.

**Comment by jimmyxian** [comment] 2015-05-12 11:15
Was able to reproduce.
Two ways to solve:
* Manually remove the container that has already to use port 8080 even exited
* Fix port filter: Check container's state in `portAlreadyInUse` function. Add one condition `container.state != 'exited'`. I have done this locally, it works

ping @aluzzardi @vieux @abronan , Any thoughts?

**Comment by chanwit** [comment] 2015-05-12 12:58
@jimmyxian we've been discussing about this in #273 as there will be a race.
As you mentioned, the workaround is to remove the container before starting a new one.
But I think checking the container's state would be feasible too. /cc @aluzzardi

**Comment by buster** [comment] 2015-09-22 14:39
I'm evaluating docker machine+swarm+compose and it seems strange that i can't stop and restart containers because of this.
I'd vote for the port filter fix, please do this :+1:

**Comment by ericchapman** [comment] 2015-10-10 14:40
I ended up doing the following
  - ```%> docker-compose build```
  - ```%> docker-compose stop```
  - ```%> docker-compose rm -f```
  - ```%> docker-compose up -d```

It adds an extra few seconds of downtime but seems to work around the issue

**Comment by chanwit** [comment] 2015-10-10 14:44
> Fix port filter: Check container's state in portAlreadyInUse function. Add one condition container.state != 'exited'. I have done this locally, it works.

@docker/swarm-maintainers I think we should consider @jimmyxian's solution for the better UX. I know that it's gonna have race conditions, but the UX will be better IMO.

**Comment by fiunchinho** [comment] 2015-12-08 12:44
I've encountered the same issue. Removing the exited container solves the problem. I'd rather have better UX and fix the race conditions eventually.

**Comment by dongluochen** [comment] 2015-12-08 20:42
When a container stops, our assumption is the resource it occupies is released. I think we should allow reuse. @jimmyxian, can you make a PR for this?

**Comment by jimmyxian** [comment] 2015-12-09 01:24
@dongluochen OK

**Comment by aluzzardi** [comment] 2015-12-09 02:41
This is working as designed.

If we were to allow re-use of a stopped container's ports, then it means that if you try to start the other container again `docker start` will simply fail.

It would also lead to a restart race - during a restart, between the time the container is stopped and started, some other container might take its port.

**Comment by dongluochen** [comment] 2015-12-09 06:04
Thanks @aluzzardi. How about CPU/memory? Does swarm preserve CPU/memory allocation for 'stopped' containers? I suspect that might lead to resource waste.

**Comment by vieux** [comment] 2016-01-20 16:18
I as @aluzzardi said, it's working as expected. I feel like we can close the issue since the behaviour was explained in #1520

**Closed by vieux** 2016-01-20 16:18 UTC
Labels: area/scheduler, priority/P2
