### ISSUE TITLE
Unstarted container causes ps -a to panic

### ISSUE THREAD

**Issue by bfirsh** [docker/swarm#985] opened 2015-06-20 22:34 UTC
Running `docker ps -a` against my Swarm causes a panic:

```
2015/06/20 22:28:37 http: panic serving 162.245.20.143:27042: runtime error: index out of range
goroutine 117 [running]:
net/http.func·011()
	/usr/src/go/src/pkg/net/http/server.go:1100 +0xb7
runtime.panic(0x963280, 0xcd6a3c)
	/usr/src/go/src/pkg/runtime/panic.c:248 +0x18d
github.com/docker/swarm/api.getContainersJSON(0xc2080b0f00, 0x7f7ee13bfc18, 0xc208496500, 0xc208161ee0)
	/go/src/github.com/docker/swarm/api/handlers.go:199 +0x16e7
github.com/docker/swarm/api.func·008(0x7f7ee13bfc18, 0xc208496500, 0xc208161ee0)
	/go/src/github.com/docker/swarm/api/primary.go:111 +0x2a0
net/http.HandlerFunc.ServeHTTP(0xc20803d300, 0x7f7ee13bfc18, 0xc208496500, 0xc208161ee0)
	/usr/src/go/src/pkg/net/http/server.go:1235 +0x40
github.com/gorilla/mux.(*Router).ServeHTTP(0xc2080add60, 0x7f7ee13bfc18, 0xc208496500, 0xc208161ee0)
	/go/src/github.com/docker/swarm/Godeps/_workspace/src/github.com/gorilla/mux/mux.go:98 +0x292
github.com/docker/swarm/api.(*dispatcher).ServeHTTP(0xc2080be910, 0x7f7ee13bfc18, 0xc208496500, 0xc208161ee0)
	/go/src/github.com/docker/swarm/api/server.go:32 +0x9d
net/http.serverHandler.ServeHTTP(0xc2081372c0, 0x7f7ee13bfc18, 0xc208496500, 0xc208161ee0)
	/usr/src/go/src/pkg/net/http/server.go:1673 +0x19f
net/http.(*conn).serve(0xc208459780)
	/usr/src/go/src/pkg/net/http/server.go:1174 +0xa7e
created by net/http.(*Server).Serve
	/usr/src/go/src/pkg/net/http/server.go:1721 +0x313
2015/06/20 22:28:49 http: panic serving 162.245.20.143:23937: runtime error: index out of range
goroutine 119 [running]:
net/http.func·011()
	/usr/src/go/src/pkg/net/http/server.go:1100 +0xb7
runtime.panic(0x963280, 0xcd6a3c)
	/usr/src/go/src/pkg/runtime/panic.c:248 +0x18d
github.com/docker/swarm/api.getContainersJSON(0xc2080b0f00, 0x7f7ee13bfc18, 0xc2083dc5a0, 0xc2083e9930)
	/go/src/github.com/docker/swarm/api/handlers.go:199 +0x16e7
github.com/docker/swarm/api.func·008(0x7f7ee13bfc18, 0xc2083dc5a0, 0xc2083e9930)
	/go/src/github.com/docker/swarm/api/primary.go:111 +0x2a0
net/http.HandlerFunc.ServeHTTP(0xc20803d300, 0x7f7ee13bfc18, 0xc2083dc5a0, 0xc2083e9930)
	/usr/src/go/src/pkg/net/http/server.go:1235 +0x40
github.com/gorilla/mux.(*Router).ServeHTTP(0xc2080add60, 0x7f7ee13bfc18, 0xc2083dc5a0, 0xc2083e9930)
	/go/src/github.com/docker/swarm/Godeps/_workspace/src/github.com/gorilla/mux/mux.go:98 +0x292
github.com/docker/swarm/api.(*dispatcher).ServeHTTP(0xc2080be910, 0x7f7ee13bfc18, 0xc2083dc5a0, 0xc2083e9930)
	/go/src/github.com/docker/swarm/api/server.go:32 +0x9d
net/http.serverHandler.ServeHTTP(0xc2081372c0, 0x7f7ee13bfc18, 0xc2083dc5a0, 0xc2083e9930)
	/usr/src/go/src/pkg/net/http/server.go:1673 +0x19f
net/http.(*conn).serve(0xc20847d000)
	/usr/src/go/src/pkg/net/http/server.go:1174 +0xa7e
created by net/http.(*Server).Serve
	/usr/src/go/src/pkg/net/http/server.go:1721 +0x313
2015/06/20 22:28:57 http: panic serving 162.245.20.143:29143: runtime error: index out of range
goroutine 125 [running]:
net/http.func·011()
	/usr/src/go/src/pkg/net/http/server.go:1100 +0xb7
runtime.panic(0x963280, 0xcd6a3c)
	/usr/src/go/src/pkg/runtime/panic.c:248 +0x18d
github.com/docker/swarm/api.getContainersJSON(0xc2080b0f00, 0x7f7ee13bfc18, 0xc2083fa5a0, 0xc20843f860)
	/go/src/github.com/docker/swarm/api/handlers.go:199 +0x16e7
github.com/docker/swarm/api.func·008(0x7f7ee13bfc18, 0xc2083fa5a0, 0xc20843f860)
	/go/src/github.com/docker/swarm/api/primary.go:111 +0x2a0
net/http.HandlerFunc.ServeHTTP(0xc20803d300, 0x7f7ee13bfc18, 0xc2083fa5a0, 0xc20843f860)
	/usr/src/go/src/pkg/net/http/server.go:1235 +0x40
github.com/gorilla/mux.(*Router).ServeHTTP(0xc2080add60, 0x7f7ee13bfc18, 0xc2083fa5a0, 0xc20843f860)
	/go/src/github.com/docker/swarm/Godeps/_workspace/src/github.com/gorilla/mux/mux.go:98 +0x292
github.com/docker/swarm/api.(*dispatcher).ServeHTTP(0xc2080be910, 0x7f7ee13bfc18, 0xc2083fa5a0, 0xc20843f860)
	/go/src/github.com/docker/swarm/api/server.go:32 +0x9d
net/http.serverHandler.ServeHTTP(0xc2081372c0, 0x7f7ee13bfc18, 0xc2083fa5a0, 0xc20843f860)
	/usr/src/go/src/pkg/net/http/server.go:1673 +0x19f
net/http.(*conn).serve(0xc2083bb900)
	/usr/src/go/src/pkg/net/http/server.go:1174 +0xa7e
created by net/http.(*Server).Serve
	/usr/src/go/src/pkg/net/http/server.go:1721 +0x313
```

Here's the container that causes it:

```
[
{
    "Id": "2aa608b0df1a6749865ebce68573c338c48ad01e50de6f4272c5ae81317b3bf9",
    "Created": "2015-06-20T22:24:43.65488236Z",
    "Path": "/usr/local/bin/entrypoint",
    "Args": [],
    "State": {
        "Running": false,
        "Paused": false,
        "Restarting": false,
        "OOMKilled": false,
        "Dead": false,
        "Pid": 0,
        "ExitCode": 128,
        "Error": "Cannot find child for /prod_haproxy_1",
        "StartedAt": "0001-01-01T00:00:00Z",
        "FinishedAt": "0001-01-01T00:00:00Z"
    },
    "Image": "71bfb61ca2851b8087d31eb07d5ec184bf6eb4ebc175297af47652e8cc358b7b",
    "NetworkSettings": {
        "Bridge": "",
        "EndpointID": "3fb481b26e7043c682ece1343c78089883779fe17adfea89e4f4eee54081e72d",
        "Gateway": "",
        "GlobalIPv6Address": "",
        "GlobalIPv6PrefixLen": 0,
        "HairpinMode": false,
        "IPAddress": "172.21.0.1",
        "IPPrefixLen": 16,
        "IPv6Gateway": "",
        "LinkLocalIPv6Address": "",
        "LinkLocalIPv6PrefixLen": 0,
        "MacAddress": "",
        "NetworkID": "b7cba9424070e4f478abd56fe7046612c417a0a1c6813c51d163f2e11f9077e3",
        "PortMapping": null,
        "Ports": {},
        "SandboxKey": "",
        "SecondaryIPAddresses": null,
        "SecondaryIPv6Addresses": null
    },
    "ResolvConfPath": "/var/lib/docker/containers/2aa608b0df1a6749865ebce68573c338c48ad01e50de6f4272c5ae81317b3bf9/resolv.conf",
    "HostnamePath": "",
    "HostsPath": "/var/lib/docker/containers/2aa608b0df1a6749865ebce68573c338c48ad01e50de6f4272c5ae81317b3bf9/hosts",
    "LogPath": "",
    "Name": "/prod_haproxy_1",
    "RestartCount": 0,
    "Driver": "aufs",
    "ExecDriver": "native-0.2",
    "MountLabel": "",
    "ProcessLabel": "",
    "Volumes": {
        "/etc/docker": "/etc/docker"
    },
    "VolumesRW": {
        "/etc/docker": true
    },
    "AppArmorProfile": "",
    "ExecIDs": null,
    "HostConfig": {
        "Binds": [
            "/etc/docker:/etc/docker:rw"
        ],
        "ContainerIDFile": "",
        "LxcConf": null,
        "Memory": 0,
        "MemorySwap": 0,
        "CpuShares": 0,
        "CpuPeriod": 0,
        "CpusetCpus": "",
        "CpusetMems": "",
        "CpuQuota": 0,
        "BlkioWeight": 0,
        "OomKillDisable": false,
        "Privileged": false,
        "PortBindings": {
            "8080/tcp": [
                {
                    "HostIp": "",
                    "HostPort": "80"
                }
            ]
        },
        "Links": null,
        "PublishAllPorts": false,
        "Dns": null,
        "DnsSearch": null,
        "ExtraHosts": [],
        "VolumesFrom": [],
        "Devices": null,
        "NetworkMode": "default",
        "IpcMode": "",
        "PidMode": "",
        "UTSMode": "",
        "CapAdd": null,
        "CapDrop": null,
        "RestartPolicy": {
            "Name": "",
            "MaximumRetryCount": 0
        },
        "SecurityOpt": null,
        "ReadonlyRootfs": false,
        "Ulimits": null,
        "LogConfig": {
            "Type": "json-file",
            "Config": {}
        },
        "CgroupParent": ""
    },
    "Config": {
        "Hostname": "2aa608b0df1a",
        "Domainname": "",
        "User": "",
        "AttachStdin": false,
        "AttachStdout": false,
        "AttachStderr": false,
        "ExposedPorts": {
            "8080/tcp": {},
            "8443/tcp": {}
        },
        "PublishService": "",
        "Tty": false,
        "OpenStdin": false,
        "StdinOnce": false,
        "Env": [
            "DOCKER_HOST=tcp://45.55.75.103:3376",
            "PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
        ],
        "Cmd": null,
        "Image": "bfirsh/interlock-haproxy-swarm:multihost",
        "Volumes": {
            "/etc/docker": {}
        },
        "VolumeDriver": "",
        "WorkingDir": "",
        "Entrypoint": [
            "/usr/local/bin/entrypoint"
        ],
        "NetworkDisabled": false,
        "MacAddress": "",
        "OnBuild": null,
        "Labels": {
            "com.docker.compose.config-hash": "bc9c0cc6d8ed503085d81da34ab7b3f18612ec4ed447a082cfbaacef7e300f92",
            "com.docker.compose.container-number": "1",
            "com.docker.compose.oneoff": "False",
            "com.docker.compose.project": "prod",
            "com.docker.compose.service": "haproxy",
            "com.docker.compose.version": "1.4.0dev",
            "com.docker.swarm.constraints": "[\"node==swarm-0\"]",
            "com.docker.swarm.id": "c5f64a5cb86b0202bcc3a384ef0883c01534ac5634b726ed904250c792964e61"
        }
    }
}
]
```

**Comment by bpradipt** [comment] 2015-07-20 15:51
Hello @bfirsh, can you please share more details which might help to debug the issue. I have been unable to recreate it after multiple trials.
1. How the swarm cluster was setup - discovery mechanism? 
2. Is the panic happening for any container that is unstarted ?
3. Are you able to use ps -a on the individual swarm members ?

**Comment by vieux** [comment] 2015-07-20 17:45
@bfirsh do you still have the machine availalble ? Can you do a curl `/v1.19/containers/json?all=1` against the docker daemon and post it here ?

The issue looks like `container.Names`, we could add a check to prevent the panic, but I don't see how it could happen in the first place.

**Comment by krmcbride** [comment] 2015-07-23 10:40
I was seeing this issue consistently when I had `Dead` containers hanging out anywhere in the cluster.  I could `docker ps -a` on any individual node, see the dead containers and clean them up, and then everything was peachy again when talking to swarm.

I was getting dead containers from running Consul health checks and hitting https://github.com/docker/docker/issues/9665.

**Comment by aluzzardi** [comment] 2015-08-04 23:50
ping @bfirsh

**Comment by bfirsh** [comment] 2015-08-05 10:16
Unfortunately haven't got the machine still available, happy for this to be closed.

Though generally, Swarm probably shouldn't panic given malformed API responses from the Engine. Perhaps this error could have been caught somewhere?

**Comment by lmesz** [comment] 2015-08-12 07:10
Hello,

Same here, when one of the node in the cluster contained "Dead" container. Swarm panic with the mentioned trace.
I agree with @bfirsh. In this case swarm should remove the node from the available nodes and don't crash.

**Comment by u2mejc** [comment] 2015-09-18 22:42
Hi All, I have this issue is reproducible the latest images: swarm:latest and 0.4.0-rc2. It's breaking third party tools that use the API or wrap this command. It's not related to a dead node that I can tell, the log is still printing token discovery requests and no other containers are running on clean ec2 instances running ubuntu 14.04.

```bash
ubuntu@docker-host:~$ docker version
Client:
 Version:      1.8.2
 API version:  1.20
 Go version:   go1.4.2
 Git commit:   0a8c2e3
 Built:        Thu Sep 10 19:19:00 UTC 2015
 OS/Arch:      linux/amd64

Server:
 Version:      swarm/0.4.0
 API version:  1.16
 Go version:   go1.4.2
 Git commit:   d647d82
 Built:        
 OS/Arch:      linux/amd64
```
```go
2015/09/18 21:59:25 http: panic serving 172.17.42.1:46120: runtime error: index out of range
goroutine 33 [running]:
net/http.func·011()
	/usr/src/go/src/net/http/server.go:1130 +0xbb
github.com/docker/swarm/api.getContainersJSON(0xc20800c640, 0x7fe469c7f1f8, 0xc20823c1e0, 0xc208346340)
	/go/src/github.com/docker/swarm/api/handlers.go:197 +0x1815
github.com/docker/swarm/api.func·007(0x7fe469c7f1f8, 0xc20823c1e0, 0xc208346340)
	/go/src/github.com/docker/swarm/api/primary.go:118 +0x2de
net/http.HandlerFunc.ServeHTTP(0xc20801e940, 0x7fe469c7f1f8, 0xc20823c1e0, 0xc208346340)
	/usr/src/go/src/net/http/server.go:1265 +0x41
github.com/gorilla/mux.(*Router).ServeHTTP(0xc208036370, 0x7fe469c7f1f8, 0xc20823c1e0, 0xc208346340)
	/go/src/github.com/docker/swarm/Godeps/_workspace/src/github.com/gorilla/mux/mux.go:98 +0x297
github.com/docker/swarm/api.(*dispatcher).ServeHTTP(0xc208092270, 0x7fe469c7f1f8, 0xc20823c1e0, 0xc208346340)
	/go/src/github.com/docker/swarm/api/server.go:32 +0x9d
net/http.serverHandler.ServeHTTP(0xc2080d7500, 0x7fe469c7f1f8, 0xc20823c1e0, 0xc208346340)
	/usr/src/go/src/net/http/server.go:1703 +0x19a
net/http.(*conn).serve(0xc20823c140)
	/usr/src/go/src/net/http/server.go:1204 +0xb57
created by net/http.(*Server).Serve
	/usr/src/go/src/net/http/server.go:1751 +0x35e
```

@bpradipt asked:
**1. How the swarm cluster was setup - discovery mechanism?**
Just default docker hub discovery using tokens.
**2. Is the panic happening for any container that is unstarted ?**
The panic is seen in the logs of the manager container only. When this happens, the client sees an EOF error.
**3. Are you able to use ps -a on the individual swarm members ?**
Yes, local hosts (ec2 instances) running docker containers are fine and docker ps -a works. This is only an issue when connecting to the swarm manager.

@vieux asked to test with curl:
```
curl -v localhost:2475/v1.19/containers/json?all=1
* Hostname was NOT found in DNS cache
*   Trying 127.0.0.1...
* Connected to localhost (127.0.0.1) port 2475 (#0)
> GET /v1.19/containers/json?all=1 HTTP/1.1
> User-Agent: curl/7.35.0
> Host: localhost:2475
> Accept: */*
> 
* Empty reply from server
* Connection #0 to host localhost left intact
curl: (52) Empty reply from server
```

I have these containers in hand to test, so I can run more tests if needed. I'm pretty green to go code so I haven't been able to get a PR together. 

Here's a gist of the standard install as recommend by the docker documentation (install ubuntu / swarm for development): https://gist.github.com/u2mejc/73c596b8070efad9c8fe

**Comment by abronan** [comment] 2015-09-18 23:08
Hi @u2mejc, thanks for your investigation! Although I think the issue you hit is related to docker/docker#16403 somehow because the response returned by the daemon you used (`1.8.2`) was empty (nil instead of an empty array). The patch got merged so you might want to try with the latest `docker` version and build the `dev` binary to see if the issue still persists :)

Let me know if you still have the issue after trying with the `dev` build.

**Comment by u2mejc** [comment] 2015-09-21 20:32
Hi @abronan, the issue appears to still persist at master for swarm (and docker):

```shell
ubuntu@docker-host:~/go$ bin/swarm manage token://XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX &
[2] 5406
ubuntu@docker-host:~/go$ INFO[0000] Listening for HTTP                            addr=127.0.0.1:2375 proto=tcp
INFO[0000] Registered Engine ip-192-168-100-206 at 192.168.100.206:2375 

ubuntu@docker-host:~/go$ export DOCKER_HOST=tcp://localhost:2375
ubuntu@docker-host:~/go$ docker version
Client:
 Version:      1.9.0-dev
 API version:  1.21
 Go version:   go1.4.2
 Git commit:   743dc1c
 Built:        Mon Sep 21 13:20:09 UTC 2015
 OS/Arch:      linux/amd64

Server:
 Version:      swarm/0.5.0-dev
 API version:  1.16
 Go version:   go1.5.1
 Git commit:   HEAD
 Built:        
 OS/Arch:      linux/amd64
ubuntu@docker-host:~/go$ docker info
Containers: 46
Images: 4
Role: primary
Strategy: spread
Filters: affinity, health, constraint, port, dependency
Nodes: 1
 ip-192-168-100-206: 192.168.100.206:2375
  └ Containers: 46
  └ Reserved CPUs: 0 / 1
  └ Reserved Memory: 0 B / 2.051 GiB
  └ Labels: executiondriver=native-0.2, kernelversion=3.13.0-62-generic, operatingsystem=Ubuntu 14.04.2 LTS, storagedriver=aufs
CPUs: 1
Total Memory: 2.051 GiB
Name: docker-host
ubuntu@docker-host:~/go$ docker ps
CONTAINER ID        IMAGE               COMMAND             CREATED             STATUS              PORTS               NAMES
ubuntu@docker-host:~/go$ docker ps -a
2015/09/21 19:44:47 http: panic serving 127.0.0.1:44202: runtime error: index out of range
goroutine 36 [running]:
net/http.(*conn).serve.func1(0xc8203d4840, 0x7faad9f74de0, 0xc82002a968)
    /usr/local/go/src/net/http/server.go:1287 +0xb5
github.com/docker/swarm/api.getContainersJSON(0xc8200f1540, 0x7faad9f83a80, 0xc8203d48f0, 0xc8201f1b20)
    /home/ubuntu/go/src/github.com/docker/swarm/api/handlers.go:242 +0x1adc
github.com/docker/swarm/api.NewPrimary.func1(0x7faad9f83a80, 0xc8203d48f0, 0xc8201f1b20)
    /home/ubuntu/go/src/github.com/docker/swarm/api/primary.go:120 +0x300
net/http.HandlerFunc.ServeHTTP(0xc820133340, 0x7faad9f83a80, 0xc8203d48f0, 0xc8201f1b20)
    /usr/local/go/src/net/http/server.go:1422 +0x3a
github.com/gorilla/mux.(*Router).ServeHTTP(0xc82005ccd0, 0x7faad9f83a80, 0xc8203d48f0, 0xc8201f1b20)
    /home/ubuntu/go/src/github.com/gorilla/mux/mux.go:100 +0x29e
github.com/docker/swarm/api.(*dispatcher).ServeHTTP(0xc8200f3360, 0x7faad9f83a80, 0xc8203d48f0, 0xc8201f1b20)
    /home/ubuntu/go/src/github.com/docker/swarm/api/server.go:32 +0x9f
net/http.serverHandler.ServeHTTP(0xc82028c480, 0x7faad9f83a80, 0xc8203d48f0, 0xc8201f1b20)
    /usr/local/go/src/net/http/server.go:1862 +0x19e
net/http.(*conn).serve(0xc8203d4840)
    /usr/local/go/src/net/http/server.go:1361 +0xbee
created by net/http.(*Server).Serve
    /usr/local/go/src/net/http/server.go:1910 +0x3f6
An error occurred trying to connect: Get http://localhost:2375/v1.21/containers/json?all=1: EOF
```

Also tested 1.9.0-dev and swarm/0.4.0 together with the same results. I followed the steps for docker master here: https://github.com/docker/docker#getting-the-development-builds and swarm here: https://github.com/docker/swarm#installation-for-swarm-developers

This issue appears specific to when swarm is the server, when docker is the server, the client speaks over TCP without issue:

```http
$ curl -v localhost:2375/v1.19/containers/json?all=1
* Hostname was NOT found in DNS cache
*   Trying 127.0.0.1...
* Connected to localhost (127.0.0.1) port 2375 (#0)
>INFO[0092] GET /v1.19/containers/json?all=1             
 GET /v1.19/containers/json?all=1 HTTP/1.1
> User-Agent: curl/7.35.0
> Host: localhost:2375
> Accept: */*
> 
< HTTP/1.1 200 OK
< Content-Type: application/json
* Server Docker/1.8.2 (linux) is not blacklisted
< Server: Docker/1.8.2 (linux)
< Date: Mon, 21 Sep 2015 20:10:46 GMT
< Content-Length: 1687
< 
[{"Id":"ac4cd73266362f3025748fb2f3a5d9a87a2627f64c7", SNIP}]
* Connection #0 to host localhost left intact

$ curl -v localhost:2375/v1.19/version

* Hostname was NOT found in DNS cache
*   Trying 127.0.0.1...
* Connected to localhost (127.0.0.1) port 2375 (#0)
>INFO[0140] GET /v1.19/version                           
 GET /v1.19/version HTTP/1.1
> User-Agent: curl/7.35.0
> Host: localhost:2375
> Accept: */*
> 
< HTTP/1.1 200 OK
< Content-Type: application/json
* Server Docker/1.8.2 (linux) is not blacklisted
< Server: Docker/1.8.2 (linux)
< Date: Mon, 21 Sep 2015 20:11:34 GMT
< Content-Length: 191
< 
{"Version":"1.8.2","ApiVersion":"1.20","GitCommit":"0a8c2e3","GoVersion":"go1.4.2","Os":"linux","Arch":"amd64","KernelVersion":"3.13.0-48-generic","BuildTime":"Thu Sep 10 19:19:00 UTC 2015"}
* Connection #0 to host localhost left intact
```

Let me know what else I can do to help.

**Comment by abronan** [comment] 2015-09-21 21:33
@u2mejc Thanks a lot for all those details.

I just tried with the exact same setup, I built the binary as of today for `1.9.0-dev`, with swarm `0.5.0-dev`  (also on ubuntu `14.04` with the same kernel) and issuing a `docker ps -a` works as expected and does not panic :(

Not quite sure what is the issue in your case yet but will keep looking at those logs.

**Comment by jimmyxian** [comment] 2015-09-22 01:47
@abronan @u2mejc 
```
[{"Id":"ac4cd73266362f3025748fb2f3a5d9a87a2627f64c7", SNIP}]
```
How this container created? without Names......

Just like @vieux say:https://github.com/docker/swarm/issues/985#issuecomment-122965344
> The issue looks like container.Names, we could add a check to prevent the panic, but I don't see how it could happen in the first place.

**Comment by u2mejc** [comment] 2015-09-23 18:16
Like others before me, this bug appears to have crawled back under the rock from which it emerged. I did whip up a quick branch and was going to submit a PR after documenting how to reproduce it. Here's the one liner to check the length before trying to trim the string: https://github.com/u2mejc/swarm/commit/a61c38cfb14b264d3bb317d5ecb8b99dc02334a7

I believe there could have been some older docker versions in my cluster (swarm nodes) since once an instance rebooted init would have started the existing binary instead of the dev version I downloaded. :confused: Hopefully this thread will help remind others to check the docker version and swarm version on every instance (host) in their cluster.

**Comment by abronan** [comment] 2015-09-23 18:36
@u2mejc No worries, thanks again for your posts and for your update. At least we narrowed it down quite a bit since the beginning of this thread. Let's close this issue for now as this seems to be due to a faulty docker `engine` version.

**Closed by abronan** 2015-09-23 18:36 UTC
Labels: kind/bug, priority/P1

**Comment by keith-** [comment] 2015-11-13 16:15
We are experiencing this issue. When we do a docker ps -a (through swarm), the following error is returned:
```
An error occurred trying to connect: Get https://localhost:2375/v1.21/containers/json?all=1: EOF
```
This error only seems to be occurring if the nodes in the swarm cluster have containers in a DEAD state.

Note: When docker ps -a is run outside of swarm it returns without error. Here is our version information:

docker version (not through swarm):

```
docker version
Client:
 Version:      1.9.0
 API version:  1.21
 Go version:   go1.4.2
 Git commit:   76d6bc9
 Built:        Tue Nov  3 18:00:05 UTC 2015
 OS/Arch:      linux/amd64

Server:
 Version:      1.9.0
 API version:  1.21
 Go version:   go1.4.2
 Git commit:   76d6bc9
 Built:        Tue Nov  3 18:00:05 UTC 2015
 OS/Arch:      linux/amd64
```
docker version (through swarm):
```
Client:
 Version:      1.9.0
 API version:  1.21
 Go version:   go1.4.2
 Git commit:   76d6bc9
 Built:        Tue Nov  3 18:00:05 UTC 2015
 OS/Arch:      linux/amd64

Server:
 Version:      swarm/1.0.0
 API version:  1.21
 Go version:   go1.5.1
 Git commit:   087e245
 Built:
 OS/Arch:      linux/amd64
```



Our swarm logs contain the following error:
```
2015/11/13 10:47:13 http: panic serving 10.140.18.251:49432: runtime error: index out of range
goroutine 881 [running]:
net/http.(*conn).serve.func1(0xc8204906e0, 0x7f2205266e88, 0xc82078f8c0)
        /usr/local/go/src/net/http/server.go:1287 +0xb5
github.com/docker/swarm/api.getContainersJSON(0xc82012ee00, 0x7f220521b118, 0xc8200f9d90, 0xc8209b56c0)
        /go/src/github.com/docker/swarm/api/handlers.go:272 +0x1adc
github.com/docker/swarm/api.NewPrimary.func1(0x7f220521b118, 0xc8200f9d90, 0xc8209b56c0)
        /go/src/github.com/docker/swarm/api/primary.go:128 +0x300
net/http.HandlerFunc.ServeHTTP(0xc8201bf5e0, 0x7f220521b118, 0xc8200f9d90, 0xc8209b56c0)
        /usr/local/go/src/net/http/server.go:1422 +0x3a
github.com/gorilla/mux.(*Router).ServeHTTP(0xc8201327d0, 0x7f220521b118, 0xc8200f9d90, 0xc8209b56c0)
        /go/src/github.com/docker/swarm/Godeps/_workspace/src/github.com/gorilla/mux/mux.go:98 +0x29e
github.com/docker/swarm/api.(*dispatcher).ServeHTTP(0xc820140700, 0x7f220521b118, 0xc8200f9d90, 0xc8209b56c0)
        /go/src/github.com/docker/swarm/api/server.go:32 +0x9f
net/http.serverHandler.ServeHTTP(0xc82031bda0, 0x7f220521b118, 0xc8200f9d90, 0xc8209b56c0)
        /usr/local/go/src/net/http/server.go:1862 +0x19e
net/http.(*conn).serve(0xc8204906e0)
        /usr/local/go/src/net/http/server.go:1361 +0xbee
created by net/http.(*Server).Serve
        /usr/local/go/src/net/http/server.go:1910 +0x3f6
2015/11/13 10:48:23 http: TLS handshake error from 10.140.18.251:53633: EOF
```

**Comment by aluzzardi** [comment] 2015-11-25 15:07
ping @docker/swarm-maintainers
