### ISSUE TITLE
“docker run swarm create” failed with error “503 Service Unavailable”

### ISSUE THREAD

**Issue by DevOps-IT** [docker/swarm#2686] opened 2017-04-28 09:50 UTC
My platform is Ubuntu-16.04 docker version: Docker version 1.12.6, build 78d1802

When I ran "docker run swarm create", it failed with following output:

Unable to find image 'swarm:latest' locally latest: Pulling from library/swarm ebe0176dcf9a: Pull complete 19f771faa982: Pull complete 902eeedf931a: Pull complete Digest: sha256:815fc8fd4617d866e1256999c2c0a55cc8f377f3dade26c3edde3f0543a70c04 Status: Downloaded newer image for swarm:latest
503 Service Unavailable
No server is available to handle this request.

I was doing POC on swarm to orchestrate different docker containers but not able to proceed. Please help in resolving this issue. Thanks in advance.

**Comment by allencloud** [comment] 2017-04-28 10:09
I think this is a duplicate of https://github.com/docker/swarm/issues/2675.
Maybe we can get more details there.
I am closing this, and feel free to tell us if you need more details.

**Closed by allencloud** 2017-04-28 10:09 UTC
