### ISSUE TITLE
Docker client via Swarm hangs for the first pull

### ISSUE THREAD

**Issue by chanwit** [docker/swarm#336] opened 2015-01-30 09:36 UTC
To reproduce, we need to prepare a **clean** 3-node cluster.
Then just `docker run`  via Swarm for a large image. Docker client will hang. I am quite sure it's waiting for Swarm to do image pulling. But an info message is not shown in Swarm.

Docker client without Swarm, of course, pull and run the image correctly.

However, after got the image pulled to every Docker instance, Docker client via Swarm just works fine.

**Comment by vieux** [comment] 2015-01-30 17:23
You are right, we need to add some debug, the not hanging, swarm is pulling the image ans there is no output.

Unlike the regular docker workflow, where docker is pulling the image where docker run returns a 404, it's swarm that is puling the image.

**Comment by chanwit** [comment] 2015-01-31 02:37
Sorry for calling this hang. It's just from a user's point of view. This bug would be a show stopper when someone's trying to use Swarm from scratch.

**Comment by vieux** [comment] 2015-02-02 18:39
@chanwit I agree, but I don't see an easy way to fix it. I'll make a PR to add daemon side logging. 
but besides this, I don't know how to fix it.

Ultimately, we should let the client pull it would solve many issues, but that's not easy.

**Comment by jpetazzo** [comment] 2015-02-26 20:39
Actually, sometimes, it's really hanging. Just got that on a fresh cluster, tried to run redis through swarm, and after a few minutes, nothing happened. I nuked the cluster (remove all images and all containers) and tried again, this time it worked.

In any case, I think it would be nice to have more debug info in Swarm to tell what's going on during the run/pull.

**Comment by anderssv** [comment] 2015-03-24 18:32
Getting same issue, just with two nodes. Haven't tested with just one. Not seen any real hangs yet though. :)

**Comment by yunspace** [comment] 2015-04-13 22:53
I also came across this issue in a fresh 2 node cluster deployed to azure using docker machine. Tried to run rancher/server (505mb) and the process was still not finished after 7 hours.

By opening up another terminal I can see that swarm has been downloading various images including a 505mb image but none of them have names or tags associated which is quite odd. 

I know my network is fine because I managed to download a 4gb installer image during the 7hours. I will try out the pull then run work around

**Comment by aluzzardi** [comment] 2015-05-27 22:51
I'm afraid we can't fix this due to an API limitation.

@vieux Any better idea on how we could fix it?

**Comment by anderssv** [comment] 2015-05-28 06:44
I really don't see how you can say this is something that won't be fixed, period. I understand it might be hard, or not solvable right now. But this is a major usability hurdle when getting started with Swarm, and something that will trip a lot of people up. For Swarm adaptation and ease of testing this might be really negative.

One of the first tings I noticed starting to work with Docker was it's easy getting started. It was so easy that I really doubted that anything was happening. ;) I was hoping for the same from Swarm (and Machine). My two cents. :)

**Comment by chanwit** [comment] 2015-05-28 06:53
I know that it's the API limitation but I still insist that this issue requires a fix. @aluzzardi could you please still open it as a reference?

**Comment by aluzzardi** [comment] 2015-05-31 00:05
Sorry about that - I was triaging bugs and closed it in a hurry without giving too much thought.

I spent more time thinking about the issue and I actually think we could fix this - it will require a Docker API change though (and docker engine change, and CLI change) - but it should work.

Right now the problem is that "create" (or "run") doesn't pull the image. The CLI tries to create the container, and if it doesn't work then it sends a "pull" to docker and tries again.

The problem is that if we do the same thing, we end up pulling on the ENTIRE cluster. As in, docker run redis would pull redis on every single node.

So the way we solved the issue was for swarm to do the create and pull on a single node when we receive the "create" request - with the downside of not seeing the pull logs since it's not the CLI pulling anymore but Swarm instead.

We could change the API so that the create call takes a "pull" option and streams back the logs. There are a few other changes that this will require such as authentication. Currently, you can pass credentials to "pull" in order to work with private registries and such, however "create" doesn't take any auth and we'd need to fix that too.

Thoughts ?

**Comment by jimmyxian** [comment] 2015-05-31 03:12
@aluzzardi @vieux 
Can we solve this as following temporary way:
Main Idea: Matain a table in store that mark whether need pull the image on a single node.
* CreateContainer in swarm: if not found image,  save a key/value(`need_pull_on_singe_node_xxxximage: node_addr`) in store, then return NO_FOUND to docker client.
* Docker client will send pull request. In Swarm pull, first check the key/value. If exists, just pull on a that node. If not exists, pull on every node. Pull in swarm will stream back some logs. Also, after check, remove that key/value.

**Comment by aluzzardi** [comment] 2015-05-31 03:48
Thanks for the suggestion, I appreciate it! I didn't think of that. It should work, although I'm afraid it will introduce many race conditions at the only benefit of getting a progress bar:

- if you send a create request for busybox then immediately after a pull request, instead of pulling on the entire cluster it will pull only on the machine selected by create.

- if you send a create through the API, get a 404 back, and decide **not** to pull (it's your right after all), then you won't be able to pull that image in the cluster

- right now we lock down the entire cluster when creating and pulling (we need to optimize that, but anyway). If we return after create and release the lock, then someone might create another container on that machine while we're pulling and the subsequent create request will fail (since there might not be enough resources anymore)

- if we fix that issue (as in, don't lock while pulling but mark the resources as taken so parallel scheduling works - there's a PR for that) it means that we would have to mark the resources as taken before returning the create call. If the user doesn't pull and actually create the container, then those resources would be **lost forever**

It's a complicated issue and I think our best option is to make changes to the Docker API.

Let's try to do that for the next (0.4) release - it's too late for 0.3.

On my phone right now so I can't make changes to the issue, but consider it as a P2 for 0.4.0.

**Comment by chanwit** [comment] 2015-05-31 06:19
thank you @aluzzardi I appreciate your hard work !!

**Comment by jimmyxian** [comment] 2015-05-31 08:12
@aluzzardi Thanks , totally agree!

**Comment by chanwit** [comment] 2015-10-14 14:31
@docker/swarm-maintainers I feel like we should address this by 1.0 to prevent uncomfortable user experiences of new Swarm users.

**Comment by ppadala** [comment] 2016-03-13 17:02
Any update on this? We have seen that that this trips up users quite a bit. They think that Swarm is hanging and often kill the pull.

**Comment by shenshouer** [comment] 2016-05-18 10:15
pull image with each node very fast, but via swarm too slow. and not any message to show. The http client will get time out if use swarm rest api .

**Comment by shenshouer** [comment] 2016-05-20 12:38
Any update on this?

**Comment by mostolog** [comment] 2017-02-28 18:09
Hi.

Actually we are facing some issues while pulling from docker hub on our swarm nodes. 
```
docker pull elasticsearch:5.2.1
Error response from daemon: manifest for elasticsearch:5.2.1 not found
```
Could our problem be related to this issue?

**Comment by tuwid** [comment] 2017-09-30 16:33
having the same issue

**Closed** 2020-02-03 08:40 UTC
Labels: kind/bug
