### ISSUE TITLE
Support tls in the consul discovery backend

### ISSUE THREAD

**Issue by crosbymichael** [docker/swarm#494] opened 2015-03-23 02:25 UTC
**Problem**

Support tls in the consul discovery backend

**Solution**

All the docker tools supports SSL/TLS, it should be possible to enable TLS to talk to the discovery service. Let's use `consuls://` and use the tlsconfig already provided

**Comment by aluzzardi** [comment] 2015-07-30 01:28
Duplicate of #404

**Closed by aluzzardi** 2015-07-30 01:28 UTC
Labels: area/discovery, area/TLS, kind/enhancement, priority/P2
