### ISSUE TITLE
docker images listing

### ISSUE THREAD

**Issue by electrical** [docker/swarm#753] opened 2015-05-08 10:28 UTC
Hi all,

At the moment with swarm when doing a `docker images` i get all the images form all the slaves which is nice but its not clear which image is living on which slave.
The `docker ps` command added the slave name to the listing, could we do something like the same with the images listing?

**Comment by vieux** [comment] 2015-05-14 00:52
Duplicate of #485

(Short answer: it's will be possible once with a change in the docker CLI)

**Closed by vieux** 2015-05-14 00:52 UTC
Labels: area/API, kind/question
