### ISSUE TITLE
event not work in 1.2.2

### ISSUE THREAD

**Issue by yank1** [docker/swarm#2237] opened 2016-05-13 02:37 UTC
event not work in 1.2.2.

`docker events`  work in 1.2.1, when I restart container.

BUT not in 1.2.2.
I think it's very critical.

**Comment by allencloud** [comment] 2016-05-13 02:40
@yank1 
Can you provide more details about this situation or how to reproduce this?

Actually I tried in my own environment, and It works for me.

**Comment by nishanttotla** [comment] 2016-05-13 18:52
@yank1 as @allencloud said, please provide a way to reproduce it. If we can reproduce, we'll bump up the priority.

**Comment by dongluochen** [comment] 2016-05-14 01:27
I cannot reproduce this issue with Swarm 1.2.2 either.

**Comment by realityone** [comment] 2016-05-17 14:23
Same issue here.
I have a node with swarm manager v1.2.2, a node with swarm agent v1.2.2, when I use `docker events --since 0`, display nothing.
But when I use swarm agent v1.2.0, it will receive some events.

**Comment by allencloud** [comment] 2016-05-17 16:47
@realityone 
If you can reproduce this bug?
Can you provide your procedure of how to reproduce it?

**Comment by realityone** [comment] 2016-05-18 03:15
@allencloud 
Finally, I found that when I restart the docker daemon on the agent node, 
swarm manager will have some reconnecting issue, and it can't receive events on that node.

**Comment by allencloud** [comment] 2016-05-18 04:33
@realityone 
Good Catch. I will try to find the details about reconnecting issue.

**Comment by allencloud** [comment] 2016-05-19 07:21
I think it has nothing to do with agent version.
Seems event listener added into Swarm will not do the reconnect thing with docker engine.

**Comment by allencloud** [comment] 2016-05-19 17:02
After we clarify this issue, it is very easy for us to reproduce it.
The root cause is docker engine's restart.

After docker engine's restart, an event of `engine-reconnect` will be emitted. While the previous event listener of Swarm can not listen the newly started docker engine. @vieux @dongluochen 

for instance:
1. start Swarm manager. It managed 2 nodes;
2.user uses `docker events` to listen swarm;
3. `docker run` on both nodes will make user receive events on each nodes;
4. restart node1;
5. `docker run ` on node1; user will receive no events on node1;
6. `docker run ` on node2; user will receive events on node2;

**Comment by dongluochen** [comment] 2016-05-19 18:02
Yes at `engine-reconnect` Swarm manager should restart event monitor for the node.

**Comment by allencloud** [comment] 2016-05-23 11:33
@dongluochen 
I did another experement and swarm will not miss events:
`$GOPATH/bin/swarm -l debug manage --engine-refresh-min-interval=1s --engine-refresh-max-interval=1s node//10.1.0.108:2376,10.1.0.112:2376`;
The refresh interval is 1s.

1. start Swarm manager. It managed 2 nodes;
2.user uses docker events to listen swarm;
3. docker run on both nodes will make user receive events on each nodes;
4. `service docker stop` on node1;
5. wait about 30s on node1;
6. `service docker start` on node1;
7. docker run on node1; user will receive events on node1;
8. docker run on node2; user will receive events on node2;

Maybe it can provide one more clue on this issue.

**Comment by dongluochen** [comment] 2016-05-23 22:51
@allencloud Swarm tries to restart event stream when broken https://github.com/docker/swarm/blob/master/cluster/engine.go#L196. But I'm not very sure how reliable/fast is the detection. 

Maybe we can add an explicit reconnect attempt after this line. Just an idea. 
https://github.com/docker/swarm/blob/master/cluster/engine.go#L401

**Comment by allencloud** [comment] 2016-05-31 08:08
@dongluochen 
I do not think adding an explicit reconnect attempt is useful. after this line https://github.com/docker/swarm/blob/master/cluster/engine.go#L401. 

The root reason is that only when docker engine's status is **stateUnhealthy** and Swarm connects Docker Engine again without err, Swarm will emit an event **engine_reconnect**.
```
if e.state == stateUnhealthy {
	log.WithFields(log.Fields{"name": e.Name, "id": e.ID}).Infof("Engine came back to life after %d retries. Hooray!", e.getFailureCount())
	e.emitEvent("engine_reconnect")
	e.setState(stateHealthy)
}
```

While when it turns  **stateUnhealthy**, some needs should be met `e.failureCount >= e.opts.FailureRetry`:
```
func (e *Engine) incFailureCount() {
	e.Lock()
	defer e.Unlock()
	e.failureCount++
	if e.state == stateHealthy && e.failureCount >= e.opts.FailureRetry {
		e.state = stateUnhealthy
		log.WithFields(log.Fields{"name": e.Name, "id": e.ID}).Errorf("Flagging engine as unhealthy. Connect failed %d times", e.failureCount)
		e.emitEvent("engine_disconnect")
	}
}
```

Swarm will wait at least **FailureRetry*flRefreshIntervalMin** time to become Unhealthy. And then if a request will trigger a connection to docker engine and the connection is no err in **Delta** time, Swarm will catch this connection and emit an event **e.emitEvent("engine_reconnect")**.

As a result, event policy will wake up after at least **FailureRetry*flRefreshIntervalMin + Delta**. During this period, any events on the docker engine will be lost.

**Comment by allencloud** [comment] 2016-05-31 10:00
@dongluochen 
I have already found the root cause of event reconnecting. It is some codes that do not work as we wish:
```
func (e *Engine) StartMonitorEvents() {
	log.WithFields(log.Fields{"name": e.Name, "id": e.ID}).Debug("Start monitoring events")
	ec := make(chan error)
	e.eventsMonitor.Start(ec)

	go func() {
		if err := <-ec; err != nil {
			if !strings.Contains(err.Error(), "EOF") {
				// failing node reconnect should use back-off strategy
				<-e.refreshDelayer.Wait(e.getFailureCount())
			}
			e.StartMonitorEvents()
		}
		close(ec)
	}()
}
```

I will put an inssue to describe the issue and how to reproduce this, then put a PR for this issue.

**Comment by allencloud** [comment] 2017-01-26 16:49
I think https://github.com/docker/swarm/pull/2547 fixed this, closing this.

**Closed by allencloud** 2017-01-26 16:49 UTC
Labels: area/discovery, kind/bug, priority/P1
