### ISSUE TITLE
Docker swarm doesn't work with latest 0.6.0 docker-machine.

### ISSUE THREAD

**Issue by himan-k** [docker/swarm#1767] opened 2016-02-08 02:27 UTC
After following the tutorial at https://docs.docker.com/swarm/install-w-machine/
here's the error,
$ eval $(docker-machine env swarm)
Host does not exist: "swarm"

Referred to bug https://github.com/docker/swarm/issues/1664 when i found my docker-machine version to be 0.5.6 and upgraded it. Still didn't solve the issue with latest 0.6.0

**Comment by nishanttotla** [comment] 2016-02-08 03:42
@himan-k sounds like the `swarm` VM isn't running/created?

Can you open VirtualBox and check all VMs that are running? Alternatively open command line and run `$ VBoxManage list vms` and report the output.

**Comment by himan-k** [comment] 2016-02-08 03:46
nope. VMs are fine,
$ docker-machine ls
NAME      ACTIVE   DRIVER       STATE     URL                         SWARM   DOCKER    ERRORS
agent1    -        virtualbox   Running   tcp://192.168.99.105:2376           v1.10.0
agent2    -        virtualbox   Running   tcp://192.168.99.106:2376           v1.10.0
default   -        virtualbox   Running   tcp://192.168.99.103:2376           v1.10.0
manager   -        virtualbox   Running   tcp://192.168.99.104:2376           v1.10.0

**Comment by himan-k** [comment] 2016-02-08 03:47
`$ docker-machine ls
NAME      ACTIVE   DRIVER       STATE     URL                         SWARM   DOCKER    ERRORS
agent1    -        virtualbox   Running   tcp://192.168.99.105:2376           v1.10.0
agent2    -        virtualbox   Running   tcp://192.168.99.106:2376           v1.10.0
default   -        virtualbox   Running   tcp://192.168.99.103:2376           v1.10.0
manager   -        virtualbox   Running   tcp://192.168.99.104:2376           v1.10.0
`

**Comment by nishanttotla** [comment] 2016-02-08 04:04
@himan-k no they're not. When you type the following command
```
$ eval $(docker-machine env swarm)
```
it points the Docker client to the machine (VM) named `swarm`. You don't have any called `swarm`. If you want to point to the `manager` machine, then instead use
```
$ eval $(docker-machine env manager)
```

**Comment by himan-k** [comment] 2016-02-08 04:14
I thought that too, but then just assumed that you could talk to the 'swarm' service like that too.
Can you tell me a way to verify swarm is working fine? I am at the stage in that document where it tried to connect to the 'swarm' (manager according to you).

I ran the docker hello-world too, but it didn't run on agent1 as the document says,

```
$ docker ps  -a
CONTAINER ID        IMAGE               COMMAND                  CREATED             STATUS                      PORTS                    NAMES
59f3c87df15f        hello-world         "/hello"                 18 seconds ago      Exited (0) 19 seconds ago                            sleepy_hypatia
```

**Comment by himan-k** [comment] 2016-02-08 05:09
Here's a way to check swarm status,
https://docs.docker.com/v1.6/swarm/

Here are node statuses; they say 'pending'. I don't think that is right.

```
$ docker -H tcp://192.168.99.104:2375 info
Containers: 0
Images: 0
Role: primary
Strategy: spread
Filters: health, port, dependency, affinity, constraint
Nodes: 2
 (unknown): 192.168.99.105:2375
   Status: Pending
   Containers: 0
   Reserved CPUs: 0 / 0
   Reserved Memory: 0 B / 0 B
   Labels:
   Error: Cannot connect to the docker engine endpoint
   UpdatedAt: 2016-02-08T03:15:11Z
 (unknown): 192.168.99.106:2375
   Status: Pending
   Containers: 0
   Reserved CPUs: 0 / 0
   Reserved Memory: 0 B / 0 B
   Labels:
   Error: Cannot connect to the docker engine endpoint
   UpdatedAt: 2016-02-08T03:16:11Z
Kernel Version: 4.1.17-boot2docker
Operating System: linux
CPUs: 0
Total Memory: 0 B
Name: 890b4b021fe1
```

**Comment by nishanttotla** [comment] 2016-02-08 05:52
@himan-k "swarm service" doesn't mean anything. If you followed the https://docs.docker.com/swarm/install-w-machine/ tutorial, then you started the swarm manager inside a Docker container using (something like) the following

```
$ eval $(docker-machine env manager)
$ docker run -d -p 2375:2375 -t swarm manage token://0ac50ef75c9739f5bfeeaf00503d4e6e
```

What this did was point your Docker client (on your host (Mac or Windows)) to the Docker engine running on the `manager` VM, and ran a container named `swarm`, which is actually running the Swarm manager code. Then when you run `swarm join` commands for the agents, they "join" the Swarm so that the manager can discover them.

Now, the command above

```
$ docker -H tcp://192.168.99.104:2375 info
```
is querying your Swarm manager (which is running in a Docker container on the VM called `manager`). This is good so far, but your Swarm manager is unable to connect to the Swarm agents. I suspect it's a port number issue. Can you run the `swarm join` commands with port 2376 instead? See below

```
$ docker run -d swarm join --addr=192.168.99.103:2376 token://0ac50ef75c9739f5bfeeaf00503d4e6e
```

**Comment by nishanttotla** [comment] 2016-02-08 05:53
cc @moxiegirl @dongluochen I think we might have to update port numbers on this tutorial https://docs.docker.com/swarm/install-w-machine/, since `docker-machine` exposes engines on port 2376, not 2375. I can submit a PR to do that if you agree.

**Comment by himan-k** [comment] 2016-02-08 05:55
I tried that as well yesterday, but it didn't work. I will try again now...

**Comment by himan-k** [comment] 2016-02-08 06:02
OK. This is what happens,
```
$ docker run -d -p 2376:2376 -t swarm manage token://<my token>
9ffac5db1db1d401617c0c0af6961b10e8cf8aedeea54d76d30cf7262bba577f
Error response from daemon: failed to create endpoint ecstatic_snyder on network bridge: Bind for 0.0.0.0:2376 failed: port is already allocated
```

**Comment by nishanttotla** [comment] 2016-02-08 06:07
That's not what I was talking about. Please run
```
$ docker run -d swarm join --addr=192.168.99.105:2376 token://<my token>
```
and
```
$ docker run -d swarm join --addr=192.168.99.106:2376 token://<my token>
```
on your Swarm agents respectively, then check the output of
```
$ docker -H tcp://192.168.99.104:2375 info
```
It should be able to connect to the nodes.

**Comment by himan-k** [comment] 2016-02-08 06:19
The other service from my previous command also seems to be running. Let me know if that is screwing it up, but otherwise, it's still not resolved.

```
$ docker -H tcp://192.168.99.104:2375 info
Containers: 0
Images: 0
Role: primary
Strategy: spread
Filters: health, port, dependency, affinity, constraint
Nodes: 4
 (unknown): 192.168.99.106:2376
   Status: Pending
   Containers: 0
   Reserved CPUs: 0 / 0
   Reserved Memory: 0 B / 0 B
   Labels:
   Error: (none)
   UpdatedAt: 2016-02-08T06:14:30Z
 (unknown): 192.168.99.105:2376
   Status: Pending
   Containers: 0
   Reserved CPUs: 0 / 0
   Reserved Memory: 0 B / 0 B
   Labels:
   Error: (none)
   UpdatedAt: 2016-02-08T06:14:30Z
 (unknown): 192.168.99.105:2375
   Status: Pending
   Containers: 0
   Reserved CPUs: 0 / 0
   Reserved Memory: 0 B / 0 B
   Labels:
   Error: Cannot connect to the docker engine endpoint
   UpdatedAt: 2016-02-08T03:15:11Z
 (unknown): 192.168.99.106:2375
   Status: Pending
   Containers: 0
   Reserved CPUs: 0 / 0
   Reserved Memory: 0 B / 0 B
   Labels:
   Error: Cannot connect to the docker engine endpoint
   UpdatedAt: 2016-02-08T03:16:11Z
Kernel Version: 4.1.17-boot2docker
Operating System: linux
CPUs: 0
Total Memory: 0 B
Name: 890b4b021fe1
```

I appreciate the help, btw.

**Comment by nishanttotla** [comment] 2016-02-08 06:29
It seems like your engines are still unable to connect. If you don't mind, can you please remove all your Docker machines, and redo the tutorial (clean slate), but this time taking the above things into account?

You can remove a Docker machine using
```
$ docker-machine rm <machine-name>
```

**Comment by himan-k** [comment] 2016-02-08 07:44
I am afraid I haven't gotten past this issue,

```
$ docker -H tcp://192.168.99.101:2375 info
Containers: 0
Images: 0
Role: primary
Strategy: spread
Filters: health, port, dependency, affinity, constraint
Nodes: 2
 (unknown): 192.168.99.102:2376
   Status: Pending
   Containers: 0
   Reserved CPUs: 0 / 0
   Reserved Memory: 0 B / 0 B
   Labels:
   Error: (none)
   UpdatedAt: 2016-02-08T07:38:06Z
 (unknown): 192.168.99.103:2376
   Status: Pending
   Containers: 0
   Reserved CPUs: 0 / 0
   Reserved Memory: 0 B / 0 B
   Labels:
   Error: (none)
   UpdatedAt: 2016-02-08T07:39:06Z
Kernel Version: 4.1.17-boot2docker
Operating System: linux
CPUs: 0
Total Memory: 0 B
Name: 2a30a8a357ea
```

Here's a snippet of my command history,

```
docker run --rm swarm create --> got the token
docker-machine ls
docker run -d -p 2375:2375 -t swarm manage token://<my token>
eval $(docker-machine env agent1)
docker-machine ls
docker run -d swarm join --addr=192.168.99.102:2376 token://<my token>
eval $(docker-machine env agent2)
docker run -d swarm join --addr=192.168.99.103:2376 token://<my token>
eval $(docker-machine env agent1)
docker -H tcp://192.168.99.101:2375 info
unset DOCKER_TLS_VERIFY
docker -H tcp://192.168.99.101:2375 info
```

**Comment by simonmittag** [comment] 2016-02-08 14:56
i think i have the same problem with docker-machine 0.6.0. i have already deleted the machines once and retraced all steps. this is what i'm running:

`#!/bin/bash
docker-machine restart manager
docker-machine restart agent1
docker-machine restart agent2

SWARM_TOKEN="$(docker -H $(docker-machine url manager) run --rm swarm create)"
AGENT1_IP="$(docker-machine ip agent1)"
AGENT2_IP="$(docker-machine ip agent2)"
MASTER_IP="$(docker-machine ip manager)"
AGENT1_PORT="2376"
AGENT2_PORT="2376"
MASTER_PORT="2375"
MASTER_PORT_EXT="2375"
echo "SWARM_TOKEN is ${SWARM_TOKEN}"

echo "launching swarm manager on ${MASTER_IP}:${MASTER_PORT_EXT}"
docker -H $(docker-machine url manager) run -d -p ${MASTER_PORT_EXT}:${MASTER_PORT} -t -debug swarm manage token://${SWARM_TOKEN}
docker -H $(docker-machine url agent1) run -d swarm join --addr=${AGENT1_IP}:${AGENT1_PORT} token://${SWARM_TOKEN}
docker -H $(docker-machine url agent2) run -d swarm join --addr=${AGENT2_IP}:${AGENT2_PORT} token://${SWARM_TOKEN}

echo "printing swarm nodes by talking to master IP docker-machine"
docker -H $(docker-machine url manager) run --rm swarm list token://${SWARM_TOKEN}

#echo "printing docker info by talking to swarm manage"
docker -H $(docker-machine url manager) info
`

**Comment by simonmittag** [comment] 2016-02-08 15:03
symptoms: i can't see the swarm machine, it's not being created

**Comment by nishanttotla** [comment] 2016-02-08 19:37
@simonmittag @himan-k thanks for the updates, I think the docs need to be fixed, there has been an issue with TLS certs in the latest release. I'll do that today, and you can try running the tutorial again. Thanks!

**Comment by nishanttotla** [comment] 2016-02-09 00:52
@simonmittag @himan-k I've fixed this doc in a new PR #1775. Please try the tutorial again once that's merged, it should work. Sorry for the previous issues!

**Comment by simonmittag** [comment] 2016-02-09 00:56
@nishanttotla thank you. Just to clarify the above. When I retrace the steps using the 2376 port on agent1 and agent2 and then run the info command on the manager, the output is:

1) there are no nodes visible in the info output.
2) docker-machine ls on the manager machine does not show the swarm machine

are you able to get a working swarm using these instructions with docker 1.10 and machine 0.6?

**Comment by nishanttotla** [comment] 2016-02-09 01:04
@simonmittag to remove any confusion, there is no `swarm` machine being created, so that was something incorrect in the docs. To connect to the manager, you have to either run `$ docker -H <manager-ip>:<manager-port> info` or set `DOCKER_HOST=<manager-ip>:<manager-port>` then run `docker info`.

The issue with the current doc was that TLS certs weren't being updated correctly for the manager. The PR fixes that. Does all this make sense?

**Comment by simonmittag** [comment] 2016-02-09 01:41
@nishanttotla. not totally sure yet.

192.168.99.100 is my manager machine IP

1) this does nothing. I assume that's correct it's not exposed.
```
docker -H tcp://192.168.99.100:2375 info 
Cannot connect to the Docker daemon. Is the docker daemon running on this host?
```
2) this is the existing docker-machine TCP socket for manager. it comes back with info for manager but i can't see the swarm inside.

```
docker -H tcp://192.168.99.100:2376 info 
Containers: 2
 Running: 1
 Paused: 0
 Stopped: 1
Images: 1
Server Version: 1.10.0
Storage Driver: aufs
 Root Dir: /mnt/sda1/var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 12
 Dirperm1 Supported: true
Execution Driver: native-0.2
Logging Driver: json-file
Plugins: 
 Volume: local
 Network: bridge null host
Kernel Version: 4.1.17-boot2docker
Operating System: Boot2Docker 1.10.0 (TCL 6.4.1); master : b09ed60 - Thu Feb  4 20:16:08 UTC 2016
OSType: linux
Architecture: x86_64
CPUs: 1
Total Memory: 996.2 MiB
Name: manager
ID: VRLL:THEQ:53EL:5TZF:FDMH:GF7B:5Z6Z:VSCI:R2J6:ACTS:F7KI:HWUM
Debug mode (server): true
 File Descriptors: 17
 Goroutines: 29
 System Time: 2016-02-09T01:30:45.204591964Z
 EventsListeners: 0
 Init SHA1: 
 Init Path: /usr/local/bin/docker
 Docker Root Dir: /mnt/sda1/var/lib/docker
Username: ***
Registry: https://index.docker.io/v1/
Labels:
 provider=virtualbox
```

3) This is the external port that was mapped by the manager app. It gives me a TLS related error. 
```
docker -H tcp://192.168.99.100:5001 info 
An error occurred trying to connect: Get https://192.168.99.100:5001/v1.22/info: tls: oversized record received with length 20527
```

which one of these do I want?

**Comment by nishanttotla** [comment] 2016-02-09 01:46
@simonmittag Can you wait for the new tutorial updates to be merged? That should fix all of these issues you're having.

To answer your questions above, (1) does nothing because port 2375 isn't exposed. (2) will only show info for the Docker engine on the `manager` machine, since 2376 is the port exposed by the Docker engine. Finally, assuming 5001 is your Swarm manager port, (3) is what you want to do. But you're getting TLS related errors, which you'll have to fix by mounting certs, as the updated doc will describe.

**Comment by simonmittag** [comment] 2016-02-09 01:48
yes that clarifies,thank you @nishanttotla :)

**Closed** 2016-02-09 02:13 UTC
Labels: kind/question

**Comment by nishanttotla** [comment] 2016-02-09 02:15
@simonmittag @himan-k try out the updated doc here: https://github.com/docker/swarm/blob/master/docs/install-w-machine.md

**Comment by himan-k** [comment] 2016-02-09 04:39
@nishanttotla Here's what I get,
```
$ docker info
An error occurred trying to connect: Get https://192.168.99.104:3376/v1.21/info: dial tcp 192.168.99.104:3376: ConnectEx tcp: No connection could be made because the target machine actively refused it.
```

**Comment by simonmittag** [comment] 2016-02-09 07:02
```
eval $(docker-machine env manager)

docker run -d -p 5001:3376 -t -v /var/lib/boot2docker:/certs:ro swarm manage -H 0.0.0.0:3376 --tlsverify --tlscacert=/certs/ca.pem --tlscert=/certs/server.pem --tlskey=/certs/server-key.pm token://7ba953a311e8e1ae38f9af634be67158
ba41c126f9abf41bee36a4aa8a1c70439ae90bd376d60d1a3230cf29b684d15d

docker ps
CONTAINER ID        IMAGE               COMMAND             CREATED             STATUS              PORTS               NAMES
```

i can't get that image up and running, it shuts down immediately

**Comment by simonmittag** [comment] 2016-02-09 07:07
```
docker run -i -p 3376:3376 -t -v /var/lib/boot2docker:/certs:ro swarm manage -H 0.0.0.0:3376 --tlsverify --tlscacert=/certs/ca.pem --tlscert=/certs/server.pem --tlskey=/certs/server-key.pm token://07b4f2c13d79c18b4f5c807484259d25

FATA[0000] Couldn't load X509 key pair (/certs/server.pem, /certs/server-key.pm): open /certs/server-key.pm: no such file or directory. Key encrypted? 
```

**Comment by nishanttotla** [comment] 2016-02-09 07:21
@simonmittag I think I made a typo in the PR. It should be `--tlskey=/certs/server-key.pem`. Sorry about that, I'll fix it.

**Comment by nishanttotla** [comment] 2016-02-09 07:29
@himan-k can you delete all machines and try afresh? The issue you're having seems unlikely to be a swarm/machine issue to me.

**Comment by joaofnfernandes** [comment] 2016-02-09 20:27
@himan-k I'm also running into this problem myself.

With my installation (made using Docker Toolbox), I don't have any certificates under `/certs`. I can find some certificates under `/Users/<user>/.docker/machine/machines/<machine-name>`.

So probably the issue is related to that.

**Comment by nishanttotla** [comment] 2016-02-09 20:31
@joaofnfernandes the `/certs` folder is being mounted into the container. The actual certs are in your VM, under the `/var/lib/boot2docker` folder. If you want to confirm, try ssh into the VM using `docker-machine ssh manager` and navigate to that folder.

**Comment by simonmittag** [comment] 2016-02-09 22:50
@joaofnfernandes the /var/lib/boot2docker folder is in the docker-machine as per above. 
@nishanttotla after fixing the typo (should've spotted that myself) it works fine and now using the swarm with the new instructions. Thanks again for fixing this. 

(The most confusing part in the old instructions was the commands that incorrectly suggested that swarm should appear as a docker-machine that can be selected with docker-machine env)

**Comment by nishanttotla** [comment] 2016-02-09 22:52
@simonmittag great, glad to know it finally worked! The older docs worked fine, but we wanted to get rid of some `docker-machine` magic and make things more explicit. Hope everything is clear now!
