### ISSUE TITLE
Swarm framework abort when Mesos master leaves.

### ISSUE THREAD

**Issue by gradywang** [docker/swarm#1730] opened 2016-02-02 07:50 UTC
According to my understanding, Swarm should detect the Mesos master automatically at runtime, and re-register to it when Mesos master recovery, but I found I am wrong after I tested this behaviour based on the latest code in community.

My test steps as below:

Step1: Prepare the Swarm + Mesos environment based on the latest code in community.

Step2: Run a task in Swarm cluster, and it started successfully.
$ docker -H gradyhost1.eng.platformlab.ibm.com:2375 run -d --cpu-shares 1 ubuntu:14.04 sleep 120
b8013e636cdc8d387b73d4ca252df7088e0f7d365db8ca609db34616e54df842

Step3: Then kill the Mesos master service, and I find some swarm error logs:

```
......
......
time="2016-02-02T07:29:46Z" level=debug msg="Removing offer" name=mesos offerID="&OfferID{Value:*9132caa4-a4a9-43ef-808a-ffe635f77db1-O4,XXX_unrecognized:[],}"
time="2016-02-02T07:29:46Z" level=debug msg="Offer \"9132caa4-a4a9-43ef-808a-ffe635f77db1-O4\" declined successfully" name=mesos
ERROR: logging before flag.Parse: I0202 07:29:46.726012       1 http_transporter.go:218] Failed to POST: Post http://9.111.255.10:5050/master/mesos.internal.LaunchTasksMessage: dial tcp 9.111.255.10:5050: getsockopt: connection refused
ERROR: logging before flag.Parse: I0202 07:29:46.726103       1 scheduler.go:1081] Aborting framework [&FrameworkID{Value:*9132caa4-a4a9-43ef-808a-ffe635f77db1-0000,XXX_unrecognized:[],}]
ERROR: logging before flag.Parse: I0202 07:29:46.726141       1 scheduler.go:1012] Stopping the scheduler driver
ERROR: logging before flag.Parse: I0202 07:29:46.726147       1 scheduler.go:1062] stopping messenger
ERROR: logging before flag.Parse: I0202 07:29:46.726154       1 messenger.go:269] stopping messenger..
ERROR: logging before flag.Parse: I0202 07:29:46.726160       1 http_transporter.go:476] stopping HTTP transport
ERROR: logging before flag.Parse: I0202 07:29:46.726167       1 scheduler.go:1065] Stop() complete with status DRIVER_STOPPED error <nil>
time="2016-02-02T07:29:46Z" level=error msg="Failed to send message mesos.internal.LaunchTasksMessage: Post http://9.111.255.10:5050/master/mesos.internal.LaunchTasksMessage: dial tcp 9.111.255.10:5050: getsockopt: connection refused" name=mesos
time="2016-02-02T07:29:46Z" level=error msg="Failed to send message mesos.internal.LaunchTasksMessage: Post http://9.111.255.10:5050/master/mesos.internal.LaunchTasksMessage: dial tcp 9.111.255.10:5050: getsockopt: connection refused" name=mesos
2016/02/02 07:29:46 Recv loop terminated: err=EOF
2016/02/02 07:29:46 Send loop terminated: err=<nil>
time="2016-02-02T07:29:46Z" level=debug msg="Mesos driver stopped unexpectedly, status/err DRIVER_ABORTED: <nil>"
time="2016-02-02T07:29:50Z" level=debug msg="Engine update succeeded" id="RJNG:KRN6:OUXI:Z6ND:MRN6:VC4A:3JRQ:F5XZ:4YIX:GEDZ:K5IF:PVHM" name=gradyhost3.eng.platformlab.ibm.com
time="2016-02-02T07:29:55Z" level=debug msg="Removing offer" name=mesos offerID="&OfferID{Value:*9132caa4-a4a9-43ef-808a-ffe635f77db1-O5,XXX_unrecognized:[],}"
time="2016-02-02T07:29:55Z" level=error msg="Error while declining offer \"9132caa4-a4a9-43ef-808a-ffe635f77db1-O5\": Unable to LaunchTasks, expected driver status DRIVER_RUNNING, but got DRIVER_ABORTED" name=mesos
time="2016-02-02T07:30:11Z" level=debug msg="Removing offer" name=mesos offerID="&OfferID{Value:*9132caa4-a4a9-43ef-808a-ffe635f77db1-O6,XXX_unrecognized:[],}"
time="2016-02-02T07:30:11Z" level=error msg="Error while declining offer \"9132caa4-a4a9-43ef-808a-ffe635f77db1-O6\": Unable to LaunchTasks, expected driver status DRIVER_RUNNING, but got DRIVER_ABORTED" name=mesos
time="2016-02-02T07:30:25Z" level=debug msg="Engine update succeeded" id="B6X2:KCUU:RYQC:ZR7T:6TKQ:TVFG:Z7HY:ASEM:CZC5:RKHM:AWS7:JPHP" name=gradyhost2.eng.platformlab.ibm.com
......
......
```

Step4: Restart the Mesos master service, Swarm framework does not re-register.

I am not sure whether it is a bug, because it does not always appear in my environment.

**Comment by doronp** [comment] 2016-03-06 13:56
Interesting. Is that consistent for you (Swarm never re-Register)?

**Comment by gradywang** [comment] 2016-03-15 09:35
@doronp Yes, today I have tried with some times again, and Swarm never re-register when Mesos master recovery. 

My steps as below:
- Start Mesos master with command:
```
# (./mesos-master.sh --ip=9.111.255.10 --work_dir=/tmp/mesos-master >> /tmp/mesos-master.log 2>&1 &)
```
- Start Swarm Manager with command:
```
# ./swarm --debug manage \
  -c mesos-experimental \
  --cluster-opt mesos.address=9.111.255.10 \
  --cluster-opt mesos.tasktimeout=10s \
  --cluster-opt mesos.user=root \
  --cluster-opt mesos.offertimeout=10m \
  --cluster-opt mesos.port=3375 \
  --cluster-opt mesos.enablerevocable=true \
  --host=0.0.0.0:4375 9.111.255.10:5050
```

- Kill the Mesos master
```
# ps -ef | grep mesos
root      2277     1  0 17:24 pts/0    00:00:00 /opt/mesos/build/src/.libs/lt-mesos-master --ip=9.111.255.10 --work_dir=/tmp/mesos-master
root      5299  7635  0 17:27 pts/0    00:00:00 ./swarm --debug manage -c mesos-experimental --cluster-opt mesos.address=9.111.255.10 --cluster-opt mesos.tasktimeout=10s --cluster-opt mesos.user=root --cluster-opt mesos.offertimeout=10m --cluster-opt mesos.port=3375 --cluster-opt mesos.enablerevocable=true --host=0.0.0.0:4375 9.111.255.10:5050
root      5677  2840  0 17:27 pts/4    00:00:00 grep --color=auto mesos
# kill -9 2277
```

- Restart the Mesos master:
```
# (./mesos-master.sh --ip=9.111.255.10 --work_dir=/tmp/mesos-master >> /tmp/mesos-master.log 2>&1 &)
```

-  After checking Mesos portal and logs, swarm never re-register.

Swarm logs:
```
DEBU[0000] Registering HTTP route                        method=DELETE route=/networks/{networkid:.*}
DEBU[0000] Registering HTTP route                        method=DELETE route=/volumes/{name:.*}
INFO[0000] Listening for HTTP                            addr=0.0.0.0:4375 proto=tcp
ERROR: logging before flag.Parse: E0315 17:27:45.170644    5299 standalone.go:180] Get http://9.111.255.10:5050/state.json: dial tcp 9.111.255.10:5050: getsockopt: connection refused
ERROR: logging before flag.Parse: E0315 17:28:15.170754    5299 standalone.go:180] Get http://9.111.255.10:5050/state.json: dial tcp 9.111.255.10:5050: getsockopt: connection refused
```

**Comment by doronp** [comment] 2016-03-15 20:45
It seems the problem is not necessarily in Swarm:
https://github.com/mesosphere/kubernetes-mesos/issues/344

Problem in mesos go which was not attended to.

**Comment by gradywang** [comment] 2016-03-15 23:20
Thanks @doronp, do we have the plan to fix this issue?

**Comment by doronp** [comment] 2016-03-16 09:19
@gradywang 
I've opened https://github.com/mesos/mesos-go/issues/231

Let see if we can get it looked at, otherwise I will try to.

**Comment by nishanttotla** [comment] 2018-05-30 18:07
Closing due to https://github.com/docker/swarm/pull/2853

**Closed by nishanttotla** 2018-05-30 18:07 UTC
Labels: area/mesos, kind/bug
