### ISSUE TITLE
Swarm manager intermittently unable to see newly joined docker host nodes

### ISSUE THREAD

**Issue by jsipprell** [docker/swarm#974] opened 2015-06-18 16:04 UTC
Using a test cluster of two docker hosts with _different_ /etc/docker/key.json files, swarm manager (running master branch, rev 174ea0c) occasionally is unable to see the advertisement of the second docker node once its been down past the ttl interval.

When this happens the container running `swarm agent` logs the following:

    time="2015-06-18T15:21:42Z" level=error msg="Discovery error: missing port in address \x01"  

Restarting the container running `swarm manage` "fixes" the issue and `info` accurately reports both nodes.

NB: discovery is an external production zookeeper 3.4.6 three-node cluster Both test hosts are advertised via `swarm join --advertise <external-ip>:2375 zk://$ZOOKEEPER_CLUSTER` and docker is running with `--tlsverify -H 0.0.0.0:2375` (swarm likewise configured and typically working as expected w/ tis). When this occurs the zk cluster has two nodes as expected under `/docker/swarm/nodes`, one for each test-host-ip:2375 tuple with matching node contents.

**Comment by abronan** [comment] 2015-06-18 18:47
Hi @jsipprell, thanks for reporting the issue. I managed to reproduce using the same setup and `v0.3.0`.

Zookeeper seems to give us back an empty value during the watch trigger so it returns the error because the discovery cannot parse an empty entry. It seems to be related to #417 somehow where we need to ignore empty values to let zookeeper report later when we change the content of the key by a new `Put` operation.

**Comment by abronan** [comment] 2015-06-19 19:53
I'll create a PR soon that depends on #924 (which includes many fixes on the separate `docker/libkv` repo). The issue is that we check `len(addr) == 0` to ignore empty values while zookeeper returns us `\x01` which bypasses the check and throws the error. The sync issue on nodes is actually an intermittent watch error on the discovery side which will be fixed as well.

**Closed** 2015-07-06 21:15 UTC
Labels: area/discovery, kind/bug
