### ISSUE TITLE
Unable to use --link while starting container (through swarm)

### ISSUE THREAD

**Issue by aku163** [docker/swarm#705] opened 2015-05-04 06:59 UTC
Hi,

I have two nodes out of which swarm manager is running on second node.
on 
host1 : 
    3 containers are running with name as name1, name2, name3
    docker deamon is running with port 2375
host2: 
    docker deamon is running with port 2375
    swarm manager is running with port 2376

Issue:
=================================================
While starting container on host2 with below command, i get the error.

docker -H tcp://host2:2376 \
-d \
--ipc=host  \
--privileged=true \
--name name4 \
-h host4.domain.com \
--link name1:alias1 \
-p 1000:22 \
centos:latest \
/usr/sbin/sshd -D

Error: FATA[0000] Error response from daemon: Unable to find a node fulfilling all dependencies: --link=name1:alias1

and while running from host2 with below command

docker -H tcp://host2:2375 \
-d \
--ipc=host  \
--privileged=true \
--name name4 \
-h host4.domain.com \
--link name1:alias1 \
-p 1000:22 \
centos:latest \
/usr/sbin/sshd -D

FATA[0000] Error response from daemon: Could not get container for name1.

**Comment by jimmyxian** [comment] 2015-05-04 09:07
@aku163 Can you provide the result of `docker -H tcp://host2:2376 info` and `docker -H tcp://host2:2376 ps`?

**Comment by aku163** [comment] 2015-05-04 09:45
Below outputs are without --link option.

Containers: 8
Strategy: spread
Filters: affinity, health, constraint, port, dependency
Nodes: 2
 node1: host1:2375
  └ Containers: 4
  └ Reserved CPUs: 0 / 8
  └ Reserved Memory: 0 B / 14.99 GiB
 node2: host2:2375
  └ Containers: 4
  └ Reserved CPUs: 0 / 8
  └ Reserved Memory: 0 B / 14.99 GiB

==========
CONTAINER ID	IMAGE		COMMAND		CREATED	 STATUS	  PORTS																									NAMES
0d52af4f1398	image1:latest	"/usr/sbin/sshd -D"	45 minutes ago		Up 45 minutes	host1:3001->22/tcp, host1:28006->8006/tcp																				ip-host1/product1							  
0567a3b213fc	image2:latest	"/usr/sbin/sshd -D"	About an hour ago	Up About an hour	 2809/tcp, 7272/tcp, 8000-8007/tcp, 8878/tcp, 9060/tcp, 9353/tcp, 9629/tcp, 9900/tcp, 10002-10005/tcp, 10009-10010/tcp, 10200/tcp, 10204-10206/tcp, 10210-10211/tcp, host1:10000-10001->10000-10001/tcp, 10213/tcp, host1:3003->22/tcp			ip-host1/product2							
6827d16b81ff	image3:latest	"/usr/sbin/sshd -D"	About an hour ago	Up About an hour	 2809/tcp, 7272/tcp, 8000-8007/tcp, 8878/tcp, 9060/tcp, 9353/tcp, 9629/tcp, 9900/tcp, 10002-10005/tcp, 10009-10010/tcp, 10200/tcp, 10204-10206/tcp, 10210-10211/tcp, 10213/tcp, 20000/tcp, host1:3002->22/tcp, host1:20000->10000/tcp, host1:20001->10001/tcp	ip-host1/product3							
c226621a68c2	image4:latest	 "/usr/sbin/sshd -D"	About an hour ago	Up About an hour	 host1:8887-8888->8887-8888/tcp, host1:3000->22/tcp																			  ip-host1/product4,ip-host1/product2/product4.domain.com,ip-host1/product3/product4.domain.com

**Comment by aluzzardi** [comment] 2015-05-06 03:10
Hi @aku163,

I'm unable to reproduce the issue.

Here's what I tried to run:

```
$ docker version | grep swarm
Server version: swarm/0.3.0

$ docker run -d --name name1 busybox sleep 1000
66cbc51e9c1bf1a1e0ae8f6374cb95547ee9e4f39eab7635dc5e6c7e341cd5e5

$ docker run -d --name name2 --link name1:alias1 busybox sleep 1000
f0027a84b0b446290f21557a21115b079af877ef00b87a5ce0c0ba50ab73ade8

$ docker inspect -f "{{ .HostConfig.Links }}" name2
[/name1:/name2/alias1]
```

Could you try to run those exact same commands, see if they work?

**Comment by aku163** [comment] 2015-05-06 20:13
Hi @aluzzardi  not sure if these two nodes belong to same swarm cluster on different nodes.

I recently came to a new issue, 

Existing issue as explained:
=========================================

Using swarm cluster i created two containers on different IPs say IP1, IP2

Usking --link prevents to start the container while putting reference to container on other node

New issue as explained:
=========================================

To overcome the first issue, I did manual host entries what --link does internally (pretty much i guess), It was my assumption that withing a cluster family, all the containers are having access to exposed ports by other containers, either on same IP or different;

BUT, it was not the same case. 

IP1 : container port 80 
IP2 : telnet IP1 80 gives output as connection timed out.


Have anyone seen this issue before?

**Comment by aluzzardi** [comment] 2015-05-27 22:41
@aku163 Linking doesn't work across hosts.

I'm still unable to reproduce: Could you provide all the commands / flags you used?

**Comment by kacole2** [comment] 2015-07-11 00:13
i'm experiencing the same issue as @aku163. 

I'm explicitly telling the two containers to run on a separate host by using the `affinity:container!=` flag. However, I'm receiving 
```
Error response from daemon: Unable to find a node fulfilling all dependencies: --link=docker_mysql:mysql
```
when running the following commands:
```
docker run -d --name docker_mysql -p 3306:3306 -e MYSQL_PASS="87654321" —e affinity:container!=*wordpress* tutum/mysql

docker run --name docker_wordpress01 --link docker_mysql:mysql -e WORDPRESS_DB_USER="admin" -e WORDPRESS_DB_PASSWORD="87654321" -e WORDPRESS_DB_NAME="docker_wordpress01" —e affinity:container!=*mysql* p 8080:80 -d wordpress 
```

I'm running swarm v0.3.0-rc2 and all hosts were provisioned using Docker Machine v0.3.0.

**Comment by aluzzardi** [comment] 2015-07-30 01:45
/cc @mavenugo 

Currently, linking can only be done on the same machine. `--link` and the `affinity` are conflicting on each other

**Comment by kacole2** [comment] 2015-07-30 01:55
I should have updated this... I read about cross-host networking being experimental. Will be looking forward to that being stable

**Comment by otzy007** [comment] 2015-09-15 08:57
I'm having the same trouble when trying to link kibana to an elastic search container:

```
$ docker run --link es:es -p 5601:5601 -e ELASTICSEARCH_URL=http://es:9200 -d kibana
Error response from daemon: Unable to find a node fulfilling all dependencies: --link=es:es
```

```
docker version
Client:
 Version:      1.8.1
 API version:  1.20
 Go version:   go1.4.2
 Git commit:   d12ea79
 Built:        Thu Aug 13 02:49:29 UTC 2015
 OS/Arch:      darwin/amd64

Server:
 Version:      swarm/0.4.0
 API version:  1.16
 Go version:   go1.4.2
 Git commit:   d647d82
 Built:        
 OS/Arch:      linux/amd64
```

**Comment by aieeeeeeeee** [comment] 2015-10-29 10:11
I'm also having the same issue when trying to link a django container with postgres:
```
$ docker run -d --name django --link django_postgres:db django_django:1.0
FATA[0002] Error response from daemon: Unable to find a node fulfilling all dependencies: --link=django_postgres:db
```

As said by kacole2, my understanding is that a swarm cluster behaves like a standalone node and therefore that all the names are shared accross the nodes. 
Nevertheless, I see 2 possible solutions:
- Either export all the names of the differents nodes to the cluster so names would be known everywhere
- Either specify that I want to run the new container on the same node as the postgres one

Is there any of this solution possible (or any other hint would be appreciated ;-) )?

**Comment by aluzzardi** [comment] 2015-10-29 10:16
@aieeeeeeeee Is `django_postgres` a container somewhere?

@mavenugo: Should we recommend to just use overlay instead of linking?

**Comment by aieeeeeeeee** [comment] 2015-10-29 10:19
```
$ docker ps
CONTAINER ID        IMAGE                 COMMAND                CREATED             STATUS              PORTS               NAMES
77d0aa4f48cc        django_postgres:1.0   "/docker-entrypoint.   23 minutes ago      Up 22 minutes       5432/tcp            swarm-node001/django_postgres
```

Isn't it correct?

**Comment by aluzzardi** [comment] 2015-10-29 10:25
Weird, it seems to be working here:

```
$ docker run -d --name redis redis
9c9ba1b78d30fe6840d25ec12c3762ac33954a051bef78942a0063df44a1caa0
$ docker ps
CONTAINER ID        IMAGE               COMMAND                CREATED             STATUS              PORTS               NAMES
9c9ba1b78d30        redis               "/entrypoint.sh redi   8 seconds ago       Up 7 seconds        6379/tcp            dev/redis
$ docker run -d --name nginx --link redis:db nginx
60172adeb15336229e3e954fe7225375457678e30216883214a00b6653d93d2a
```

Could you provide the output of a `docker info` please?

**Comment by aieeeeeeeee** [comment] 2015-10-29 10:28
```
$ docker info
Containers: 3
Images: 10
Storage Driver:
Role: primary
Strategy: spread
Filters: affinity, health, constraint, port, dependency
Nodes: 2
 swarm-node001: 10.0.0.6:2375
  └ Containers: 2
  └ Reserved CPUs: 0 / 1
  └ Reserved Memory: 0 B / 1.718 GiB
  └ Labels: executiondriver=native-0.2, kernelversion=4.2.0-16-generic, operatingsystem=Ubuntu 15.10, storagedriver=aufs
 swarm-node002: 10.0.0.5:2375
  └ Containers: 1
  └ Reserved CPUs: 0 / 1
  └ Reserved Memory: 0 B / 1.718 GiB
  └ Labels: executiondriver=native-0.2, kernelversion=4.2.0-16-generic, operatingsystem=Ubuntu 15.10, storagedriver=aufs
Execution Driver:
Kernel Version:
Operating System:
CPUs: 2
Total Memory: 3.437 GiB
Name: c2ed48aad2f8
ID:
Http Proxy:
Https Proxy:
No Proxy:
```

**Comment by aluzzardi** [comment] 2015-10-29 10:29
Also, how was `django_postgres` started?

Same question for you, @otzy007: how was elastic search started?

`--link` can only work if the two containers run on the same machine.

docker 1.9 and swarm 1.0 are introducing a new multi-host network features that allows containers to talk to reach other on different hosts without the need of linking.

**Comment by aieeeeeeeee** [comment] 2015-10-29 10:33
@aluzzardi: `django_postgres` has been started as follows:
```
$ docker run -d -name django_postgres django_postgres:1.0
```

**Comment by aieeeeeeeee** [comment] 2015-10-29 13:47
@aluzzardi: I've tried your example with redis and nginx which is indeed working. Are you able to make the following works (I use public containers so you can try to reproduce the issue)

```
$ docker run -d --name nginx_hello -P kitematic/hello-world-nginx
$ docker run -d --name nginx_hello_2 -P kitematic/hello-world-nginx

$ docker ps
CONTAINER ID        IMAGE                                COMMAND             CREATED              STATUS              PORTS                    NAMES
e58223760f4c        kitematic/hello-world-nginx:latest   "sh /start.sh"      About a minute ago   Up About a minute   10.0.0.6:32768->80/tcp   swarm-node001/nginx_hello_2
2d91f0f5bac6        kitematic/hello-world-nginx:latest   "sh /start.sh"      6 minutes ago        Up 6 minutes        10.0.0.5:32768->80/tcp   swarm-node002/nginx_hello
```

And then while linking things I get the same error as before:
```
$ docker run -d -P --link nginx_hello:web1 --link nginx_hello_2:web2 tutum/haproxy
FATA[0000] Error response from daemon: Unable to find a node fulfilling all dependencies: --link=nginx_hello:web1 --link=nginx_hello_2:web2 
```

**Comment by mavenugo** [comment] 2015-10-29 13:59
@aluzzardi thats correct. linking is a pure single-host concept. Overlay networking provides inbuilt service discovery for the containers with --name. So, I would recommend using pure overlay networking in swarm instead of linking (which doesnt work cross-host).

**Comment by kacole2** [comment] 2015-10-29 14:51
@mavenugo quick question for you... I've got overlay networking properly working. How would you take the existing Wordpress Dockerfile image and have it point to a mysql instance without using `--links`? If I'm not mistaken, the official Wordpress image requires the use of `--links`. Just didn't know if there was a work-around. thanks!

**Comment by schmunk42** [comment] 2015-10-29 15:15
@kacole2 I have the same question. Currently `--link` is not only used for network service discovery, it also shares environment variables, eg. database credentials. How will this work in the future when links become deprecated.

@mavenugo Did you use consul for overlay networking? Is consul, zookeeper or etcd mandatory for overlay networking?

**Comment by mavenugo** [comment] 2015-10-29 15:26
@schmunk42 do you mean for testing ? I use either of the 3 you mentioned. And yes, we need atleast 1 of these to have overlay networking working. We also have e2e multi-host Integration-Tests in libnetwork project using all these 3 stores. Please check it out.

You also brought up some of the short-term pain with migrating away from links. `Links` is an awesome feature with some limitations. one such thing is the static nature of unidirectional connectivity and static env variable settings. I believe the correct solution is to provide proper dynamic Service Discovery mechanism out of the box which will address all the features (though with issues mentioned above) and more. We are not there yet.

**Comment by schmunk42** [comment] 2015-10-29 16:26
@mavenugo Thank you. I will try to check out the integration tests.

I saw in another issue, that someone reported a 404 error, when trying to use overlay networking without a kv-store, and I had the same error without getting the problem in the first place.
And since I found not much documentation about it I thought I ask in advance :) before trying it out.

**Comment by kacole2** [comment] 2015-10-29 16:28
@schmunk42 i just got an entire lab ready for WebSummit next week where we are demo'ing the networking in 1.9. Take a look here and adjust as necessary for your needs. 

[EMC {code} Docker Workshop at WebSummit 2015](https://github.com/emccode/training/tree/master/docker-workshop/websummit)

**Comment by schmunk42** [comment] 2015-11-02 12:20
@kacole2 Thank you, that's looking great.

**Comment by abronan** [comment] 2015-12-17 19:47
Please take a look at this [comment](https://github.com/docker/swarm/issues/1272#issuecomment-165531564). Links are deprecated from now on to use networking (libnetwork is now fully integrated to docker since `1.9`) and the overlay driver to link containers across hosts. You can refer to the [docker networking documentation](https://docs.docker.com/engine/userguide/networking/dockernetworks/) for more informations on how to use the overlay driver. If using docker-compose please refer to this [documentation](https://docs.docker.com/compose/networking/).

Feel free to comment below or open a new issue if you have any trouble linking containers across hosts using overlay networking. Closing. Thanks!

**Closed by abronan** 2015-12-17 19:47 UTC
Labels: area/network, priority/P3
