### ISSUE TITLE
swarm join heartbeat should be an interval

### ISSUE THREAD

**Issue by aluzzardi** [docker/swarm#1353] opened 2015-10-29 08:54 UTC
When starting a bunch of machines at the same time it hits hard the store.

**Comment by dongluochen** [comment] 2015-11-12 23:12
The problem is synchronized registration when nodes are added in batch mode. Adding a random delay at `swarm join` should reduce the spike to store.

**Comment by abronan** [comment] 2016-01-04 20:29
Closed by #1410

**Closed by abronan** 2016-01-04 20:29 UTC
Labels: area/discovery
