### ISSUE TITLE
docker run --rm swarm --create not working

### ISSUE THREAD

**Issue by garrypolley** [docker/swarm#790] opened 2015-05-14 19:17 UTC
Currently whenever I attempt to setup a swarm instance using the guide here:

http://docs.docker.com/swarm/

I get the following output on a RHEL 7 node: 

```sh
[root@garry-docker-machine ~]# docker run swarm --create
Timestamp: 2015-05-14 15:15:43.822554043 -0400 EDT
Code: System error

Message: [/usr/bin/tar -cf /var/lib/docker/tmp/6091c0b586f1c4636bc5523c3b301396ae3fc598f567ca64323b15ebd122a98d060876981/_tmp.tar -C /var/lib/docker/devicemapper/mnt/6091c0b586f1c4636bc5523c3b301396ae3fc598f567ca64323b15ebd122a98d/rootfs/tmp .] failed: /usr/bin/tar: /var/lib/docker/devicemapper/mnt/6091c0b586f1c4636bc5523c3b301396ae3fc598f567ca64323b15ebd122a98d/rootfs/tmp: Cannot chdir: No such file or directory
/usr/bin/tar: Error is not recoverable: exiting now
: exit status 2

Frames:
---
0: setupRootfs
Package: github.com/docker/libcontainer
File: rootfs_linux.go@30
---
1: Init
Package: github.com/docker/libcontainer.(*linuxStandardInit)
File: standard_init_linux.go@52
---
2: StartInitialization
Package: github.com/docker/libcontainer.(*LinuxFactory)
File: factory_linux.go@223
---
3: initializer
Package: github.com/docker/docker/daemon/execdriver/native
File: init.go@35
---
4: Init
Package: github.com/docker/docker/pkg/reexec
File: reexec.go@26
---
5: main
Package: main
File: docker.go@29
---
6: main
Package: runtime
File: proc.go@63
---
7: goexit
Package: runtime
File: asm_amd64.s@2232
FATA[0000] Error response from daemon: : exit status 2
```

**Comment by abronan** [comment] 2015-05-14 19:26
Hi @garrypolley, thanks for reporting the issue. As you are using RHEL it seems to be a duplicate of #781. I'll close this one but feel free to comment on the other issue so we can concentrate our effort there.

**Closed by abronan** 2015-05-14 19:26 UTC

**Comment by garrypolley** [comment] 2015-05-14 20:00
Thanks! I didn't see the other issue when I was searching around.  I appreciate the linking.
