### ISSUE TITLE
Support tls in the etcd discovery backend

### ISSUE THREAD

**Issue by crosbymichael** [docker/swarm#496] opened 2015-03-23 02:26 UTC
**Problem**

Support tls in the etcd discovery backend

**Solution**

All the docker tools supports SSL/TLS, it should be possible to enable TLS to talk to the discovery service. Let's use `etcds://` and use the tlsconfig already provided

**Comment by david-guenault** [comment] 2015-03-23 05:54
isn't this a duplicate of #404 ?

**Comment by timfallmk** [comment] 2015-03-26 01:45
:+1:

**Comment by packetcollision** [comment] 2015-03-26 07:23
#dibs

**Comment by timfallmk** [comment] 2015-03-26 18:03
Hi @packetcollision, you mind if I take this one? I already fixed it at the party but haven't double checked my work.

**Comment by packetcollision** [comment] 2015-03-27 05:42
@timfallmk go for it!

**Comment by aluzzardi** [comment] 2015-07-30 01:28
Duplicate of #404

**Closed by aluzzardi** 2015-07-30 01:28 UTC
Labels: area/discovery, area/TLS, priority/P2
