### ISSUE TITLE
Docker swarm master not in sync with nodes

### ISSUE THREAD

**Issue by coffenbacher** [docker/swarm#844] opened 2015-05-26 01:20 UTC
My Swarm master seems to lose track of what my nodes are doing after some use. It reports non-existent containers. I destroyed and recreated ts02 within the last two weeks, perhaps that has something to do with the below example? I see this behavior fairly often.

1) Is there a known issue for why this happens?
2) Is there a workaround? Destroying and recreating the master Swarm machine (docker-machine) resolved it for me, but a simpler "refresh" command would be ideal.

Docker client connected to swarm master ->

    $ docker ps | grep 'simulator'
    a4170c...  coffenbacher/simulator:latest   "/bin/sh -c 'python    2 weeks ago   Pending ts02/furious_galileo

SSH directly to the referenced node ->

    $ docker-machine ssh ts02
    c@ts02:~# docker ps -a | grep 'simulator'
    c@ts02:~#

Versions:

    $ docker -v
    Docker version 1.6.2, build 7c8fca2

    c@ts02:~# docker -v
    Docker version 1.6.2, build 7c8fca2

    c@ts-master:~# docker -v
    Docker version 1.6.2, build 7c8fca2

**Comment by abronan** [comment] 2015-05-28 20:17
Hi @coffenbacher, thanks for reporting. I see that you are using `docker-machine` which uses swarm `0.2.0`. There were huge changes since `0.2.0` to the latest `0.3.0-rc1`. In your case it is indeed the Manager not refreshing correctly.

I have a cluster up with `0.3.0rc1` and I will keep an eye on this but so far I cannot seem to reproduce the issue.

In the meantime you can probably try using the latest `0.3.0-rc1` and see if that solves the issue.

**Comment by abronan** [comment] 2015-05-29 20:00
@coffenbacher By the way, which one of the driver are you using with `docker-machine`? I'd like to get as close as I can to your setup using the latest version of machine and swarm.

**Comment by coffenbacher** [comment] 2015-06-02 18:10
Great, thanks for the response. I'll experiment with updating us to 0.3.0-rc1 and see if I can still repro.

We're using the digital ocean driver.

**Comment by abronan** [comment] 2015-06-16 20:33
@coffenbacher Did you managed to reproduce it somehow? I couldn't reproduce on my side, I tried with local VMs, on GCE and on Digital Ocean using `swarm` or `machine/swarm` with the latest `rc`'s (also destroying and re-creating instances).

**Comment by kubenstein** [comment] 2015-06-25 14:41
hi, i have similar issue, my swarm contains only virtualboxed hosts on local machine. When i remove one node, master still reports it in the swarm. here are steps to reproduce it:
```
sid=$(docker-swarm create)

docker-machine create -d virtualbox --swarm --swarm-master --swarm-discovery token://$sid swarm-master
docker-machine create -d virtualbox --swarm --swarm-discovery token://$sid swarm-node-01
docker-machine create -d virtualbox --swarm --swarm-discovery token://$sid swarm-node-02

eval "$(docker-machine env --swarm swarm-master)"

docker info # OK reported nodes: swarm-master swarm-node-01 swarm-node-02
docker-machine rm swarm-node-02
docker info # BAD! swarm-node-02 should not be here, but still is. reported nodes are again: swarm-master swarm-node-01 swarm-node-02
```
 tools im using:
```
docker -v         # Docker version 1.7.0, build 0baf609
docker-machine -v # docker-machine version 0.3.0 (HEAD)
docker-swarm -v   # docker-swarm version 0.2.0 (HEAD)
```

i thought maybe starting container on non existing node will refresh node list but i only get proper error and list stays the same.

**Comment by abronan** [comment] 2015-06-25 22:37
Hi @kubenstein, you need to use swarm `v0.3.0` with Consul, Etcd or Zookeeper in order to see nodes removed from the cluster.

If you want to use the latest version of swarm with machine, you need to specify the flag: 
```
docker-machine [...] --swarm-image swarm:0.3.0 [...]
```

This means that you will also have to use the `--swarm-discovery` flag using a custom Consul, Etcd or Zookeeper if you want your nodes to be removed from the cluster.

**Comment by abronan** [comment] 2015-06-29 20:25
I'm closing this for now, @coffenbacher please feel free to re-open if you still manage to reproduce the sync issue with `swarm:0.3.0`.

**Closed by abronan** 2015-06-29 20:25 UTC
Labels: kind/bug, priority/P1

**Comment by coffenbacher** [comment] 2015-06-30 19:18
Great, thanks @abronan. I just got back from vacation - on Swarm 0.3.0 now and nothing but good so far.

**Comment by abronan** [comment] 2015-06-30 21:40
Great :smile: :tropical_drink: feel free to re-open this one or open new issues if something goes wrong.
