### ISSUE TITLE
Swarm can not unregister node manually

### ISSUE THREAD

**Issue by resouer** [docker/swarm#323] opened 2015-01-28 07:52 UTC
Currently, we can not unregister or remove a node from a cluster. Although filter will make sure unhealthy node will not be served, but we really need to remove some nodes, for example it has failed or been destroyed. There's also complain from group.

So I think we should have this function in swarm. But that requires refactor of discovery interface.
I'm happy to give this a shot if this makes sense.

**Comment by aluzzardi** [comment] 2015-01-29 22:18
Duplicate of https://github.com/docker/swarm/issues/197

It's going to be a priority soon for us.

**Closed by aluzzardi** 2015-01-29 22:18 UTC
