### ISSUE TITLE
Compose UP in Docker Swarm Node Added Problem

### ISSUE THREAD

**Issue by yank1** [docker/swarm#2273] opened 2016-05-25 01:33 UTC
When I use a one node. 
I can use `compose up` to up a image like `jenkins`.
And then I `compose down`

But when I add a node to swarm, And `compose up`  again.
There would be a error `can not find image`.

**Comment by yank1** [comment] 2016-05-25 01:33
@allencloud is there any way to fix it

**Comment by allencloud** [comment] 2016-05-25 02:11
I will try to reproduce this, and find the root cause of this issue.
@yank1

**Comment by allencloud** [comment] 2016-05-25 15:46
@yank1 
If you solved this issue, please close this issue.

**Closed** 2016-05-26 02:32 UTC
