### ISSUE TITLE
Docker Swarm usage

### ISSUE THREAD

**Issue by gdmurali** [docker/swarm#1075] opened 2015-07-20 06:33 UTC
Hi,

I am new to docker swarm.

First I followed instructions below to create cluster, swarm Manager and swarm Agent on one Host.
https://docs.docker.com/swarm/install-manual/
Every thing is fine.
I see one manager contaienr running and one agent container ( for a docker host ) running 

versa@gdlxc2:~$ docker ps
CONTAINER ID        IMAGE               COMMAND                CREATED             STATUS              PORTS                    NAMES
e04a58c93f84        swarm               "/swarm manage token   2 days ago          Up 2 days           0.0.0.0:2375->2375/tcp   sick_hypatia         
3508772ea036        swarm               "/swarm join --addr=   2 days ago          Up 2 days           2375/tcp                 condescending_pare   

I was able to list and create containers.

Now when when to next page in documentation
 https://docs.docker.com/swarm/discovery/
I see commands like below where swarm command is used from shell directly.
 "swarm create"
How is this possible ? Are there any swarm binaries available using which we need not create manager and agent containers as mentioned at https://docs.docker.com/swarm/install-manual/ ?

Sequence of documentation ( for Docker Swarm ) is little confusing.

**Comment by UserTaken** [comment] 2015-07-20 07:38
The discrepancy in the documentation is a [known issue](https://github.com/docker/docker/issues/14721) that should be fixed. The `swarm` image contains a statically linked `swarm` binary from [swarm-library-image](https://github.com/docker/swarm-library-image) which you can use outside of Docker.

**Comment by gdmurali** [comment] 2015-07-20 11:37
Thanks for update.

**Comment by aluzzardi** [comment] 2015-07-30 01:48
Thanks @gdmurali 

This is a dupe of #722

**Closed by aluzzardi** 2015-07-30 01:48 UTC
Labels: area/doc
