### ISSUE TITLE
swarm 1.1.0-rc1 removes node, after it came back to life

### ISSUE THREAD

**Issue by schmunk42** [docker/swarm#1656] opened 2016-01-19 06:51 UTC
Engine came back to life, but was removed right afterwards, running with `-experimental`

```
time="2016-01-19T06:46:20Z" level=error msg="Update engine specs failed: Cannot connect to the docker engine endpoint" id="IS2F:AT37:YVL4:ZRS5:C737:23KD:P6UP:73SW:2Y3R:2N46:3IF3:V4OK" name=tiho-a5 
time="2016-01-19T06:46:52Z" level=info msg="Engine came back to life after 14 retries. Hooray!" id="IS2F:AT37:YVL4:ZRS5:C737:23KD:P6UP:73SW:2Y3R:2N46:3IF3:V4OK" name=tiho-a5 
time="2016-01-19T06:47:02Z" level=info msg="Removed Engine tiho-a5" 
```

**Comment by dongluochen** [comment] 2016-01-19 07:06
@schmunk42 I think the engine came back and engine removed events are not directly related. Engine reachability is monitored by swarm with retries. You can verify it with `docher -H node_ip:node_port info`. Engine removal is triggered by discovery, which can be verified by `swarm list #discovery#`.

**Comment by dongluochen** [comment] 2016-01-19 07:09
And thanks for trying swarm 1.1.0-rc1.

**Comment by schmunk42** [comment] 2016-01-19 14:57
Sorry, I had already restarted to node manually. But I will try to provide more information if it occurs again. Also looked a bit like a race-condition to me.

**Comment by abronan** [comment] 2016-01-19 17:59
Thanks for trying this out @schmunk42, I'll try to reproduce too. This indeed looks like a race in the monitoring/retry process.

**Comment by vieux** [comment] 2016-01-26 22:52
any news on this @abronan ?

**Comment by abronan** [comment] 2016-01-26 23:03
@vieux I think this is fixed by #1658 and #1662 

@dongluochen Can you confirm?

**Comment by dongluochen** [comment] 2016-01-26 23:25
@abronan I didn't have enough info to reproduce the issue when it was reported. I still think engine came back and engine removed events were not directly related.

**Comment by dongluochen** [comment] 2016-01-28 18:23
@schmunk42 I close this issue since there is no repro. Feel free to reopen if you see it again.

**Closed by dongluochen** 2016-01-28 18:23 UTC
Labels: area/discovery, kind/bug
