### ISSUE TITLE
Docker-Swarm and ETCD 

### ISSUE THREAD

**Issue by vandita31** [docker/swarm#988] opened 2015-06-22 20:33 UTC
Hi,

I am trying to attempt set up Docker Swarm on some hosts and instead of generating tokens , I am trying to use ETCD to bring up the Swarm Manager.  Swarm Join with ETCD currently breaks and throws the following error - 

[root@dcavm-ch2-122p ssl]# ~/gocode/bin/swarm manage --tlsverify --tlscacert=/app/support/docker/ssl/ca.pem --tlscert=/app/support/doer/ssl/dockerhost-cert.pem --tlskey=/app/support/docker/ssl/dockerhost-key.pem --H=dcavm-ch2-122p.sys.comcast.net:2376 etcd://172.28.143.251:2379
INFO[0000] Listening for HTTP                            addr=dcavm-ch2-122p.sys.comcast.net:2376 proto=tcp
ERRO[0000] Discovery error: 501: All the given peers are not reachable (failed to propose on members [http://172.28.143.251:2379] twice [last error: Get http://172.28.143.251:2379/v2/keys/docker/swarm/nodes?quorum=false&recursive=true&sorted=true: malformed HTTP response "\x15\x03\x01\x00\x02\x02"]) [0] 
ERRO[0000] Discovery error: Unexpected watch error

The ETCD version running is - 
etcd Version: 2.0.12
Git SHA: 5686c33
Go Version: go1.4.2
Go OS/Arch: linux/amd64

I tried to test it with multiple IP's ( using all the nodes of the 3 node ETCD cluster) but it produces the same error. Can i get some insight on the reason behind the "Unexpected watch error" and suggestions on how to get it to work would be great!

Thanks,

Vandita

**Comment by abronan** [comment] 2015-06-22 21:44
Hi @vandita31, can you provide the commands you used to spin up that `etcd` cluster? Usually this error is brought up when the `--advertise-client-urls` and `listen-client-urls` are not properly configured. In this case, swarm will have trouble to get back the discovery informations from the `etcd` cluster.

**Comment by vandita31** [comment] 2015-06-26 14:56
Thanks @abronan for your response. I have a 3 node ETCD cluster set up. This is how the ETCD process is running on one of the nodes ..

 /usr/bin/etcd -name cdaetcd1 -data-dir /var/lib/etcd/automation -peer-ca-file=/etc/etcd/ssl/ca.crt -peer-cert-file=/etc/etcd/ssl/cdaetcd-ch2-1p.sys.comcast.net.crt -peer-key-file=/etc/etcd/ssl/cdaetcd-ch2-1p.sys.comcast.net.key.insecure -ca-file=/etc/etcd/ssl/ca.crt -cert-file=/etc/etcd/ssl/cdaetcd-ch2-1p.sys.comcast.net.crt -key-file=/etc/etcd/ssl/cdaetcd-ch2-1p.sys.comcast.net.key.insecure -advertise-client-urls https://172.28.178.251:2379 -listen-client-urls https://172.28.178.251:2379 -initial-advertise-peer-urls https://172.28.178.251:2380 -listen-peer-urls https://172.28.178.251:2380 -initial-cluster cdaetcd1=https://172.28.178.251:2380,cdaetcd2=https://172.28.143.25:2380,cdaetcd3=https://172.28.143.251:2380 -initial-cluster-token automation-1 -initial-cluster-state new -cors * -heartbeat-interval=1000 -election-timeout=30000 -snapshot-count=10000

the --advertise-client-urls and listen-client-urls are both set to :  https://172.28.143.25:2379
This is the IP of the node itself where the etcd process is running. 

These are the 3 nodes -

-initial-cluster cdaetcd1=https://172.28.178.251:2380,cdaetcd2=https://172.28.143.25:2380,cdaetcd3=https://172.28.143.251:2380

Is there any setting that looks misconfigured?

**Comment by abronan** [comment] 2015-06-29 16:46
Ok taking a step back and looking at the logs, this is actually due to TLS. Swarm currently does not support secure communication with discovery/storage (which must be behind a secured network configuration).

We need to add proper flags to point to cert files for the discovery/storage (separately from the docker daemon certs). See #496.

**Comment by aluzzardi** [comment] 2015-08-05 00:04
Thanks @vandita31 

This is planned for `0.5.0` and is a duplicate of #404

**Closed by aluzzardi** 2015-08-05 00:04 UTC
Labels: area/discovery, area/TLS, priority/P2
