### ISSUE TITLE
[Get Started with Docker Swarm] Unable to connect to the swarm-master

### ISSUE THREAD

**Issue by whites11** [docker/swarm#1664] opened 2016-01-21 17:02 UTC
Following the "Get Started with Docker Swarm" tutorial.
I have successfully created the "local", "swarm-master", "swarm-agent-00" and "swarm-agent-01" machines:

```
$ docker-machine ls
NAME             ACTIVE   URL          STATE     URL                         SWARM                   DOCKER   ERRORS
local            -        virtualbox   Running   tcp://192.168.99.107:2376                           v1.9.1   
swarm-agent-00   -        virtualbox   Running   tcp://192.168.99.109:2376   swarm-master            v1.9.1   
swarm-agent-01   -        virtualbox   Running   tcp://192.168.99.110:2376   swarm-master            v1.9.1   
swarm-master     *        virtualbox   Running   tcp://192.168.99.108:2376   swarm-master (master)   v1.9.1
```

when I try to run the following command:
```
eval $(docker-machine env --swarm swarm-master)
```

I get this error:
```
Error checking TLS connection: Connection to Swarm cannot be checked but the certs are valid. Maybe swarm is not started
```

So I got into the "swarm-master" VM  (through virtualbox) and checked what's going on:

```
CONTAINER ID        IMAGE               COMMAND                  CREATED             STATUS                         PORTS               NAMES
b3606d929777        swarm:latest        "/swarm join --advert"   32 minutes ago      Up 19 minutes                                      swarm-agent
f9efdbb1cc83        swarm:latest        "/swarm manage --tlsv"   32 minutes ago      Restarting (1) 5 minutes ago                       swarm-agent-master
```

You can notice that the "swarm-agent-master container is restarting.
I tried to have a look at the logs, and that's what I found:

```
root@swarm-master:~# docker logs swarm-agent-master
time="2016-01-21T16:28:27Z" level=fatal msg="Leader election is only supported with consul, etcd and zookeeper discovery." 
time="2016-01-21T16:28:27Z" level=fatal msg="Leader election is only supported with consul, etcd and zookeeper discovery." 
time="2016-01-21T16:28:28Z" level=fatal msg="Leader election is only supported with consul, etcd and zookeeper discovery." 
time="2016-01-21T16:28:29Z" level=fatal msg="Leader election is only supported with consul, etcd and zookeeper discovery." 
time="2016-01-21T16:28:30Z" level=fatal msg="Leader election is only supported with consul, etcd and zookeeper discovery." 
time="2016-01-21T16:28:34Z" level=fatal msg="Leader election is only supported with consul, etcd and zookeeper discovery."
....
many more lines all similar
```

Any hints how to proceed further?

**Comment by abronan** [comment] 2016-01-21 19:30
Hi @whites11,

Did you try to start the `swarm-agent-master` with docker-machine using the `--replication` flag? Could you please output the exact commands to spin up your cluster in the first place using **docker-machine**? Thanks!

The log saying `Leader election is only supported with consul, etcd and zookeeper discovery.` says that it tries to run in High-Availability mode and tries to elect a Leader but it does not seem that you are using Consul in this case.

**Comment by whites11** [comment] 2016-01-21 19:36
Hi @abronan and thanks for your answer.

The exact command I executed (after installing docker-machine) are the following:

```
docker-machine create -d virtualbox local
eval "$(docker-machine env local)"
docker run swarm create
docker-machine create -d virtualbox --swarm --swarm-master --swarm-discovery token://<my token here> swarm-master
docker-machine create -d virtualbox --swarm --swarm-discovery token://<my token here> swarm-agent-00
docker-machine create -d virtualbox --swarm --swarm-discovery token://<my token here> swarm-agent-01
eval $(docker-machine env --swarm swarm-master)
```

The latest one fails as stated in my question above.

Can you please tell me exactly how I can restart my swarm-master to add the --replication flag?

thanks

**Comment by abronan** [comment] 2016-01-21 20:02
Thanks for the logs!

Seems there is something wrong indeed, because those commands seems right to me. Not sure why the `swarm-agent-master` tries to run in HA mode. You shouldn't use `--replication` with docker-machine as it's not well supported yet.

Usually those logs about Leader Election would only appear if you start the Swarm Manager with `--replication` and `--advertise`. Probably an issue with **docker-machine** but not sure.

Also last thing, could you also provide the output of `swarm version` and `docker-machine version`?

/cc @nathanleclaire sorry for the ping, any idea on this one?

**Comment by pschirch** [comment] 2016-01-24 19:35
Hi,

I also stuck on this issue. I followed the steps in this [Install and Create a Docker Swarm Tutorial](https://docs.docker.com/swarm/install-w-machine/). Running this command

```bash
eval $(docker-machine env --swarm swarm-master)
```

throws this error

```bash
Error checking TLS connection: Connection to Swarm cannot be checked but the certs are valid. Maybe swarm is not started
```

**swarm version:** swarm version 1.0.1 (744e3a3)
**docker-machine version:**  docker-machine version 0.6.0-rc1, build 174e390

Any advice?

**Comment by whites11** [comment] 2016-01-25 13:30
Sorry for late response.
Same version of docker-machine as pschirch
I don't know where to check for the "swarm" version.
Any hints how to proceed anyway?

**Comment by pschirch** [comment] 2016-01-25 14:16
This issue also exists in swarm version 1.1.0-rc2 (5cb6f21).

**Comment by pschirch** [comment] 2016-01-25 14:31
Maybe this issue is a clone of this one: https://github.com/docker/machine/issues/2903 ?

**Comment by pschirch** [comment] 2016-01-25 14:58
Yap - it's a docker-machine addressed issue. I have builded the binary for the current docker-machine master version (`docker-machine version 0.6.0-rc2-dev, build 01f4ffd`) and the `--replication` flag isn't configured any more if you use the token discovery. All works fine now.

**Comment by whites11** [comment] 2016-01-25 15:53
I can confirm it works with the master branch of docker-machine

**Comment by vieux** [comment] 2016-01-25 20:02
@nathanleclaire can you please take a look ?

**Comment by nathanleclaire** [comment] 2016-01-27 02:14
If the `--replication` flag is to blame we should be good to go.  Maybe we should release an RC2 to address this issue.  @dgageot @jeanlaurent FYI

**Comment by amitshukla** [comment] 2016-02-03 01:47
@whites11 thank you for helping us identify this issue. Can we close it if no further action is needed?

**Comment by whites11** [comment] 2016-02-03 06:48
Yes, issue closed for me

Thanks

Il giorno mer 3 feb 2016, 02:48 Amit Shukla <notifications@github.com> ha
scritto:

**Closed** 2016-02-03 07:05 UTC
Labels: kind/question

**Comment by himan-k** [comment] 2016-02-07 00:45
wait, can you tell me how to fix the issue? I am running into it now, but don't see a solution above. Thanks.

**Comment by himan-k** [comment] 2016-02-08 02:22
Guys,
I tried running swarm with docker-machine version 0.5.6 and the latest 0.6.0 after I looked up this issue.
I am using virtualbox on windows with docker toolbox. Can you please let me know how to get around this issue? I thought installing latest 0.6.0 virtual-machine.exe would solve the issue, but it didn't. Thanks.

**Comment by himan-k** [comment] 2016-02-08 02:23
BTW, 
Here's the error,
$ eval $(docker-machine env swarm)
Host does not exist: "swarm"

**Comment by nathanleclaire** [comment] 2016-02-08 18:49
@himan-k Looks like `swarm` machine doesn't exist --  I highly suggest opening another issue with exact steps to reproduce.

**Comment by casertap** [comment] 2016-04-12 11:08
Hi guys I have the same issue right now:
docker-machine version 0.6.0, build e27fb87

I upgraded my docker-machine:
docker-machine version 0.7.0-rc3, build d6c595f

Destroy all the machine and retry again. I still have the same trouble:
```
eval "$(docker-machine env --swarm machine-smaster)"
Error checking TLS connection: Connection to Swarm cannot be checked but the certs are valid. Maybe swarm is not started
```

I opened an issue on stackoverflow (I am not sure if it is a bug or if I am doing something wrong): http://stackoverflow.com/questions/36560681/can-not-connect-nodes-to-docker-swarm-master-using-zookeeper

**Comment by nathanleclaire** [comment] 2016-04-12 19:02
@casertap Please see my answer on StackOverflow.  In general I prefer to use the `--swarm-*` flags for Machine if experimenting with Swarm, it's much easier.

**Comment by tombusby** [comment] 2016-04-30 19:38
I'm having the same issue, but I didn't use the --replication flag.
