### ISSUE TITLE
Swarm agent not registering to Swarm master

### ISSUE THREAD

**Issue by smakam** [docker/swarm#874] opened 2015-05-30 16:58 UTC
Hi 
I tried 2 approaches to create Swarm cluster:
Approach 1(https://docs.docker.com/machine/#using-docker-machine-with-docker-swarm). This approach uses integrated machine/swarm and it worked fine for me.
Approach 2(https://docs.docker.com/swarm/#set-up-swarm-nodes). Here the Swarm cluster is created manually. With approach 2, I could not get Swarm nodes to register with master.

Following are more details with how I did Approach 2. 
Created token using dockerhub:
docker run --rm swarm create

Created 2 nodes using docker machine.

On each node, did the following:
docker run -d swarm join --addr=<ip>:2375 token://

On my Ubuntu machine, I ran the swarm master:
docker run -d -p 2375:2375 swarm manage token://

When I did info, I dont see any node registered:
docker -H tcp://0.0.0.0:2375 info
Containers: 0
Strategy: spread
Filters: affinity, health, constraint, port, dependency
Nodes: 0

I must be missing something obvious here....
Appreciate any help.

Thanks
Sreenivas

**Comment by aluzzardi** [comment] 2015-06-02 08:03
Thanks for the report, @smakam.

This is a problem with our docs and flag names / help text, we are working on them.

Actually, would you mind if I try out the changes we made recently to our flag names/docs with you?

What if I told you that `--addr` is gone and now there's a flag named `--advertise` instead with the following help text:
>   --advertise 	Address of the Docker Engine joining the cluster. Swarm managers MUST be able to reach Docker at this address. [$SWARM_ADVERTISE]

Does it help figuring out what the problem is / would you have done things differently?

Note that only the flag name / help message changed, it still does exactly the same thing (so you can try out with `--addr` on your version)

Please don't spend more than a few seconds thinking about it - if it's not instantly obvious then we need to improve the process.

Thanks!

/cc @moxiegirl

**Comment by smakam** [comment] 2015-06-02 14:48
hi @aluzzardi 
Sorry, I couldnt follow you completely....

Does the --advertise option need a new swarm version?
When you mention that I can try without --addr in the current swarm version that I am using, do you mean I can skip that option itself?

Thanks
Sreenivas

**Comment by mklatsky** [comment] 2015-08-27 16:04
I am seeing a similar problem. I can set up a swarm if I create the machines and swarm at creation (docker-machine create -d digitalocean --swarm --swarm-discovery token://${SWARM_TOKEN} mysswarm-01).

However- I am unable to create and add existing systems, created by docker-machine, into a swarm. I have created a paste with more details at http://pastie.org/private/vhqef1oabeyi0voun9qt0g. Any help would be great, as I am now actively exploring swarm alternatives since I am unable to get this to work- but I would rather have it work.

**Comment by abronan** [comment] 2015-09-10 18:53
Sorry for the late response @mklatsky, I guess you figured this out in the meantime but if using `docker-machine` you should use `docker-machine env --swarm swarm-master` instead to point and set the proper environment variables. It is in the docker-machine [documentation](https://github.com/docker/machine/blob/e054d06163d6559ee5417fc577ea14befbd456ff/docs/get-started-cloud.md).

The reason is that it sets the proper `DOCKER_CERT_PATH` environment variable which is the missing step because you are directly pointing to the swarm without going through `docker-machine`.

**Comment by abronan** [comment] 2015-09-10 19:01
I'll close this one for now, feel free to re-open if there is still an issue with swarm registering node.

**Closed by abronan** 2015-09-10 19:01 UTC
Labels: area/doc
