### ISSUE TITLE
[compile error]: warm/cluster/node.go:368: not enough arguments in call to n.client.RemoveContainer

### ISSUE THREAD

**Issue by therealprologic** [docker/swarm#431] opened 2015-02-27 12:34 UTC
Getting a compile error with ``0.1.0`` tag:

```#!bash
prologic@daisy
Fri Feb 27 22:21:20
~/contrib/docker-swarm
$ pkgmk -d
=======> WARNING: Packages should be built as root.
=======> Building '/data/packages/docker-swarm#0.1.0-1.pkg.tar.gz'.
bsdtar -p -o -C /home/prologic/contrib/docker-swarm/work/src -xf /data/sources/swarm-0.1.0.tar.gz
+ build
++ pwd
+ export GOPATH=/home/prologic/contrib/docker-swarm/work/src
+ GOPATH=/home/prologic/contrib/docker-swarm/work/src
+ cd swarm-0.1.0
+ go get -d
+ go build
# github.com/docker/swarm/cluster
/home/prologic/contrib/docker-swarm/work/src/src/github.com/docker/swarm/cluster/node.go:368: not enough arguments in call to n.client.RemoveContainer
=======> ERROR: Building '/data/packages/docker-swarm#0.1.0-1.pkg.tar.gz' failed.
```

**Comment by bacongobbler** [comment] 2015-02-27 15:58
dupe of #419

**Closed** 2015-03-06 21:49 UTC
