### ISSUE TITLE
"docker info" returns "Nodes: 1" while I joined 2 nodes

### ISSUE THREAD

**Issue by phuna** [docker/swarm#563] opened 2015-04-02 23:57 UTC
I'm not sure why when I run "docker info" it returns only the the node which joined 1st. I tried to run "docker info" several times to ensure it's not caused by discovery delay but result still the same.

```
ubuntu@ip-172-31-8-160:~$ docker info
Containers: 5
Nodes: 1
 ip-172-31-15-185: 172.31.15.185:2375
  └ Containers: 5
  └ Reserved CPUs: 0 / 1
  └ Reserved Memory: 0 B / 992.5 MiB
```
Commands I used to create cluster and join nodes:
```
ubuntu@ip-172-31-8-160:~$ docker run --rm swarm create
d68fa52c47e905a2ee8df1ad7681aa0d
ubuntu@ip-172-31-8-160:~$ docker run -d -p 2375:2375 swarm manage token://d68fa52c47e905a2ee8df1ad7681aa0d
bd702e00a85faef977cc4c894c18d52390ade72ced35eb59fad16ddac2027fc8
ubuntu@ip-172-31-8-160:~$ export DOCKER_HOST=tcp://127.0.0.1:2375

# On node 1
ubuntu@ip-172-31-15-185:~$ docker run -d swarm join --addr=172.31.15.185:2375 token://d68fa52c47e905a2ee8df1ad7681aa0d

# On node 2
ubuntu@ip-172-31-4-94:~$ docker run -d swarm join --addr=172.31.4.94:2375 token://d68fa52c47e905a2ee8df1ad7681aa0d
```

**Comment by abronan** [comment] 2015-04-03 00:22
Hi @phuna,

Could you please give us the log output on the Manager? It seems that you probably created the agent VMs with the same hostname.

**Comment by phuna** [comment] 2015-04-03 16:01
Hi @abronan,
here's the log from manager:
```
time="2015-04-03T16:00:30Z" level=error msg="ID duplicated. KE47:6RTV:HP4L:XF3U:6RJU:SFQG:MHMK:5LHW:MXQU:YYTA:FHM4:RLG4 shared by 172.31.15.185 and 172.31.4.94"
time="2015-04-03T16:00:30Z" level=error msg="node was already added to the cluster"
```

**Comment by abronan** [comment] 2015-04-03 18:21
@phuna You duplicated the VM right? :D The problem is that docker generates a single ID when you install the daemon. If you duplicate the VM you will end up with two different hosts and their own IP address but with a duplicate ID from docker that swarm uses. You should reinstall the docker daemon on the second node :)

**Comment by phuna** [comment] 2015-04-04 00:38
@abronan : Yes, you're right I duplicated it :) I'll reinstall it now. Thank you for help :)

**Comment by phuna** [comment] 2015-04-04 02:05
For those who finding solution like me:
I tried to remove & install again lxc-docker but still does not help as ID stays the same. I need to remove ```/etc/docker/key.json``` per answer here https://github.com/docker/swarm/issues/362, then ```sudo docker restart```

**Comment by abronan** [comment] 2015-04-07 01:16
@phuna Yes you should remove the key as well. I'll close the issue for now as it seems to be solved on your side :)

**Closed by abronan** 2015-04-07 01:16 UTC
Labels: question

**Comment by pdonorio** [comment] 2015-11-22 15:24
Ah! This issued saved me from getting crazy :)

Please take a note about the ID problem for duplicated images inside the swarm documentation... it may be a common situation.

Thanks for the great work!
