### ISSUE TITLE
Swarm doesn't check implicit :latest tag for private registry images on /image/{name}/* API calls

### ISSUE THREAD

**Issue by frol** [docker/swarm#876] opened 2015-05-31 08:41 UTC
Reproduction:

```bash
$ curl --cacert ~/.docker/ca.pem --cert ~/.docker/cert.pem --key ~/.docker/key.pem \
    https://swarm.company.com:2377/v1.18/images/private.registry.com:5000/test/json
No such image: private.registry.com:5000/test

$ curl --cacert ~/.docker/ca.pem --cert ~/.docker/cert.pem --key ~/.docker/key.pem \
    https://swarm.company.com:2377/v1.18/images/private.registry.com:5000/test:latest/json
<valid JSON>
```

Docker daemon handles these requests well and returns valid JSON for both.

This bug affects docker-py `client.inspect_image()` and, as a result, docker-compose (where I have started my investigations).

```
Client version: 1.6.2
Client API version: 1.18
Go version (client): go1.4.2
Git commit (client): 7c8fca2
OS/Arch (client): linux/amd64
Server version: swarm/0.3.0
Server API version: 1.16
Go version (server): go1.3.3
Git commit (server): 84652ed
OS/Arch (server): linux/amd64
```

Workaround for docker-compose is to specify `:latest` tag explicitly.

**Comment by frol** [comment] 2015-05-31 12:26
You may even get such error with `docker-compose up`:

```
Traceback (most recent call last):
  File "<string>", line 3, in <module>
  File "/code/build/docker-compose/out00-PYZ.pyz/compose.cli.main", line 32, in main
  File "/code/build/docker-compose/out00-PYZ.pyz/compose.cli.docopt_command", line 21, in sys_dispatch
  File "/code/build/docker-compose/out00-PYZ.pyz/compose.cli.command", line 34, in dispatch 
  File "/code/build/docker-compose/out00-PYZ.pyz/compose.cli.docopt_command", line 24, in dispatch 
  File "/code/build/docker-compose/out00-PYZ.pyz/compose.cli.command", line 66, in perform_command
  File "/code/build/docker-compose/out00-PYZ.pyz/compose.cli.main", line 470, in up
  File "/code/build/docker-compose/out00-PYZ.pyz/compose.project", line 230, in up
  File "/code/build/docker-compose/out00-PYZ.pyz/compose.service", line 333, in execute_convergence_plan 
  File "/code/build/docker-compose/out00-PYZ.pyz/compose.service", line 380, in recreate_container
  File "/code/build/docker-compose/out00-PYZ.pyz/compose.service", line 216, in create_container
  File "/code/build/docker-compose/out00-PYZ.pyz/compose.service", line 525, in _get_container_create_options
  File "/code/build/docker-compose/out00-PYZ.pyz/compose.service", line 413, in config_hash
  File "/code/build/docker-compose/out00-PYZ.pyz/compose.service", line 418, in config_dict
TypeError: 'NoneType' object has no attribute '__getitem__'
```

Once you explicitly specify `:latest`, the issue goes away.

**Comment by chanwit** [comment] 2015-05-31 12:36
AFAIK, I do not think it's Swarm bug as I clearly see that Swarm will append the missing tag (:latest) in the current code.

Probably
1. You've been running the 0.2.0 version of Swarm?
2. It's a Docker Compose issue.

**Comment by frol** [comment] 2015-05-31 12:40
@chanwit I provided docker info output, which clearly states:

```
Server version: swarm/0.3.0
```

It is not Docker Compose issue as I queried Swarm via curl!

**Comment by frol** [comment] 2015-05-31 12:41
@chanwit Please, point me out to the code where it adds `:latest`. From my tests, it only fails to work with private registry!

**Comment by chanwit** [comment] 2015-05-31 12:42
Here it is:
https://github.com/docker/swarm/blob/master/cluster/engine.go#L422

**Comment by chanwit** [comment] 2015-05-31 12:43
So is it possible to be the registry bug then?

**Comment by frol** [comment] 2015-05-31 12:47
@chanwit Are you kidding? Why do you try to find bug elsewhere if I clearly stated:

1. It reproduces on the remote API level to Swarm.
1. "Docker daemon handles these requests well and returns valid JSON for both." => it means Docker Swarm handles same requests differently.
1. I clearly use Docker Swarm and it is clear that it is 0.3.0 (ok, it is not clear that it is 0.3.0-rc1)

**Comment by chanwit** [comment] 2015-05-31 12:51
@frol  Well, sorry for that. It's just counter my belief as I see the :latest prefix appended there in the code.

Maybe you're right that Swarm handles the request differently.

**Comment by frol** [comment] 2015-05-31 12:56
@chanwit My apologies also.

Your link goes to Pull method. It seems to me that `/images/(name)/json` should be handled somewhere else. Where is it? (I'm sorry, I'm not that familiar with the code base and I cannot still find appropriate code)

**Comment by frol** [comment] 2015-05-31 12:59
@chanwit https://github.com/docker/swarm/blob/master/cluster/engine.go#L493 Here it is. There is no `:latest`-specific code at all though it somehow works for Docker Hub images.

**Comment by chanwit** [comment] 2015-05-31 13:02
@frol good catch !! I am about to tell you that the bug should be there.
But I think it's also possible to be in the `image.Match` problem.

Let's see for a bit where it should be fixed.

**Comment by chanwit** [comment] 2015-05-31 13:06
It's broken here:
https://github.com/docker/swarm/blob/master/cluster/image.go#L26

Image name is split by a colon and your image's name contains ":5000" as it's from a private registry.

**Comment by frol** [comment] 2015-05-31 13:12
@chanwit Yay! BTW, `Pull` will be broken also!

**Comment by chanwit** [comment] 2015-05-31 14:20
@frol I'll fix the matching case first, then will try to reproduce what's breaking `Pull` later in a different PR.

**Comment by frol** [comment] 2015-05-31 18:37
@chanwit The fix works for the original issue. However, I cannot make `Pull` fail, which is good from some point, but it would be better to understand why it works when it seems it shouldn't.

**Comment by chanwit** [comment] 2015-05-31 18:49
@frol I think It uses query parameters separately, e.g. `fromImage` and `repo`. So the image name is already in a short form, say `name:latest`. Maybe this is the reason it's still working fine.

**Comment by frol** [comment] 2015-05-31 18:52
@chanwit Good guess.

It was a pleasure to work with you! Thank you for the fix!

**Comment by chanwit** [comment] 2015-05-31 19:00
@frol no problem. Thank you for your patience to my wrong guesses at the beginning too.

**Comment by aluzzardi** [comment] 2015-06-02 07:51
Should we close this down since the PR was merged?

**Closed** 2015-06-02 07:52 UTC
