### ISSUE TITLE
Start container command not forwarding the HostConfig to the container

### ISSUE THREAD

**Issue by sboschman** [docker/swarm#1781] opened 2016-02-09 10:06 UTC
Client tools (Docker plugin for Jenkins in our case) that rely on passing (additional) HostConfig in the start container command do not work since 1.1.0. For example the port bindings are not passed and the container is inaccessible.

I believe the commit for 'Add support for container rescheduling on node failure.' (https://github.com/docker/swarm/commit/13f60212f57dae8ba480c28bf26261bd7331ea4) broke this flow.

From the Docker Remote API docs:
> 
Start a container:
For backwards compatibility, this endpoint accepts a HostConfig as JSON-encoded request body.
Reference: https://docs.docker.com/engine/reference/api/docker_remote_api_v1.22/#start-a-container

**Comment by nishanttotla** [comment] 2016-02-09 20:21
@sboschman can you provide more details about your setup, and how to reproduce this issue?

**Comment by sboschman** [comment] 2016-02-10 14:39
added a testcase to the integration tests (https://github.com/sboschman/swarm/blob/master/test/integration/api/start.bats) to reproduce this issue

it passes on the 1.0.1 swarm tag, but fails on swarm master

Start container function from github.com/samalba/dockerclient:
`func (client *DockerClient) StartContainer(id string, config *HostConfig) error`

Function call in container.go implemented in the earlier mentioned commit 13f6021:
`return c.Engine.client.StartContainer(c.Id, nil)`

**Comment by nishanttotla** [comment] 2016-02-12 03:21
@sboschman thanks, I'm looking into it.

**Comment by nishanttotla** [comment] 2016-02-17 00:39
@sboschman I'm fixing this now, do you mind if I include your commit (for the test) into my PR, so that you get credit?

**Comment by nishanttotla** [comment] 2016-02-17 01:33
@sboschman if you want me to include your commits, you'll have to sign them. Do you mind either creating new commits, or signing them?

I'll then port over those commits to my fork (https://github.com/nishanttotla/swarm/tree/1781-pass-hostconfig) and submit a PR to Swarm so you get credit. We'd like for this to be done by tonight, so please let me know if you can get the tests in.

Thanks,

**Comment by sboschman** [comment] 2016-02-17 07:58
timezone delay :)   thanks for fixing the issue

I made a new commit and signed it off: https://github.com/sboschman/swarm/commit/395a5fa6ddad6a5daf1e1a9fc2b59ed92cf629b7; hope it is oke like that

**Comment by nishanttotla** [comment] 2016-02-17 09:24
@sboschman thanks!

**Comment by nishanttotla** [comment] 2016-02-17 09:32
@sboschman if you don't mind, can you rebase your branch on top of the latest swarm master? That way, I can update my current PR with the fewest extra commits. I'm trying to figure how to add your commit to my PR. If that isn't feasible eventually, I'll open a separate PR for your commit.

**Comment by sboschman** [comment] 2016-02-17 10:13
@nishanttotla rebased the branch

**Comment by nishanttotla** [comment] 2016-02-18 01:56
Reopening issue since the PR had to be reverted due to docker-compose related issues.

**Comment by nfoonf** [comment] 2016-03-10 14:45
Hi, 

is there any idea, how to fix/workaround this issue?

**Comment by nishanttotla** [comment] 2016-03-11 22:24
@nfoonf if you don't really need to do it, the support for passing `HostConfig` at `/start` is deprecated, so not recommended. We're trying to figure out how to best fix this until then.

**Comment by nfoonf** [comment] 2016-03-12 11:26
I know it is deprecated.  But I am nailed on using it because the docker-build-steps plug in and probably also shipyard are bitten by this bug. I therefore would highly appreciate a fix,  even if it is obviously wrong to use it like this in the first place

**Comment by nishanttotla** [comment] 2016-03-13 01:40
@nfoonf the reason I asked you is because I think Docker Engine will stop supporting this in the next release (in less than a month), after which Swarm will not be able to.

@thaJeztah can you confirm that, or suggest what can be done?

**Comment by nfoonf** [comment] 2016-03-14 10:31
@nishanttotla to hear, that this won't be supported in the near future is good news in my eyes. 
So People will have to fix their code anyway.

**Comment by thaJeztah** [comment] 2016-03-14 11:04
Hm, yes, it is scheduled to be removed in docker 1.12 (see https://github.com/docker/docker/pull/17799). Not sure what's best here, fix the regression, or document it as a difference between the Docker API and the Swarm API (because there's already some differences); guess it depends on how difficult it is to fix

**Comment by nishanttotla** [comment] 2016-03-14 23:48
@vieux WDYT?

**Comment by vieux** [comment] 2016-03-15 00:15
@nishanttotla looking into in now

**Comment by vieux** [comment] 2016-03-15 01:31
it is an easy fix, see #1972

**Comment by calavera** [comment] 2016-03-15 21:06
The host configuration should be sent when the container is created, never after. This behavior has been deprecated in the docker engine for very very long time and you should not rely on it. Please, consider also dropping supported engine versions from Swarm if the only reason to do this is to keep compatibility with them.

**Closed** 2016-03-17 00:19 UTC
Labels: area/API, kind/bug

**Comment by phagunbaya** [comment] 2016-08-05 06:39
I'm still facing having this issue. HostConfig I sent while creating a container is not considered when running the container. It gets reset to the default.

Creating the container:
`[POST] http://localhost:2375/container/create?name={id}`
```
    {
    "Env": [
            "env1=val1"
       ],
       "Cmd": [
           "/Run.sh",
           "launch
        ],
       "Image": "<image>",
       "Volumes": {
           "/tmp" : {}
       },
       "HostConfig": {
         "NetworkMode": "my-net"
       }
    }
```
Response of `$docker inspect`:
```
    "HostConfig": {
        "Binds": null,
        "ContainerIDFile": "",
        "LogConfig": {
            "Type": "json-file",
            "Config": {}
        },
        "NetworkMode": "my-net",
        "PortBindings": null,
        "RestartPolicy": {
            "Name": "",
            "MaximumRetryCount": 0
        },
        "AutoRemove": false,
        "VolumeDriver": "",
        "VolumesFrom": null,
    }
```
This creates container with networkMode as `my-net`. But when I run
the container using the rest API [POST]
`http://localhost:2375/containers/{id}/start` networkMode changes to
`default`.

Response of `$docker inspect`:
```
    "HostConfig": {
        "Binds": null,
        "ContainerIDFile": "",
        "LogConfig": {
            "Type": "json-file",
            "Config": {}
        },
        "NetworkMode": "default",
        "PortBindings": null,
        "RestartPolicy": {
            "Name": "",
            "MaximumRetryCount": 0
        },
        "AutoRemove": false,
        "VolumeDriver": "",
        "VolumesFrom": null,
    }
```

**Comment by phagunbaya** [comment] 2016-08-05 12:48
So, there is definitely gap between the docker start and create API. To configure networkMode, we need to pass hostConfig object as payload to container start API.

Example:
```
{
  "NetworkMode": "my-net",
  "PublishAllPorts": true
}
```

But this creates problem when I want to bind a host volume. After I put `Binds` property in the above payload, volume mounting does not work at all.
