### ISSUE TITLE
The documentation is unclear what will happen if you run different daemon versions

### ISSUE THREAD

**Issue by aidanhs** [docker/swarm#593] opened 2015-04-08 16:05 UTC
> Note: The only requirement for Swarm nodes is they all run the same release Docker daemon (version 1.4.0 and later), configured to listen to a tcp port that the Swarm manager can access.

To me, this suggests that swarm does not offer any guarantees about what will happen if you try and use daemons of different patch versions, which implies that all daemons must be upgraded in lockstep, which means I have to take down my cluster on every docker upgrade.

Can you clarify in the documentation what happens when you run multiple version of docker (>= 1.4.0)? Is it
a) "swarm has undefined behaviour when running on different versions of docker and may do anything, up to and including completely refusing to work" or
b) "swarm is guaranteed to work for any operations common to all versions of docker in your cluster, but may fail for operations with discrepancies across versions"

**Comment by vieux** [comment] 2015-04-08 21:30
It is not entirely swarm related, the issue is the relationship between the docker client and docker daemon.
Uou cannot use a client newer than a daemon.

So, let's say you have a swarm cluster with 2 nodes, one with the daemon `1.4.0` and the other `1.5.0`

If you use docker client `1.4.0` -> no problem
If you use docker client `1.5.0` -> almost all operations will fail on the `1.4.0` node (same as if you would connect directly)

**Comment by aidanhs** [comment] 2015-04-09 09:41
That makes sense. So would you be happy with a doc update along the lines of: "Different versions of the docker daemon may be used in your cluster, with the caveat that the docker client version must match the *lowest* version in your cluster."

**Comment by aluzzardi** [comment] 2015-04-10 20:50
ping @SvenDowideit @fredlf

**Comment by fredlf** [comment] 2015-04-11 00:04
That sounds reasonable to me, but I think I would word it a little more strongly, and give an example for more clarity:

We don't recommend running different versions of the Docker daemon in your cluster, but if it is absolutely necessary, the version of the Docker client you are running must be the same as the lowest version of the Docker daemon you are running. For example, if you are running Docker daemon 1.4.0, all your clients must also be 1.4.0 or lower.

@aluzzardi, @vieux Do I have that correct?

**Comment by vieux** [comment] 2015-04-11 00:39
I think the sentence is reverse `all your clients` -> there is only one docker client, but multiple daemons.

**Comment by fredlf** [comment] 2015-04-11 20:34
Ah, right. That always kind of confuses me. So...

We don't recommend running different versions of the Docker daemon in your cluster, but if it is absolutely necessary, the version of the Docker client you are running must be the same as the lowest version of the Docker daemon you are running. For example, if you are running Docker client 1.4.0, all daemons must also be 1.4.0 or lower.

**Comment by aidanhs** [comment] 2015-04-12 00:07
Well, the new sentence is incorrect (a lower docker daemon won't work). Perhaps turn the old sentence

> For example, if you are running Docker daemon 1.4.0, all your clients must also be 1.4.0 or lower.

into

> For example, if you have a Docker daemon 1.4.0 in your cluster, any clients must be 1.4.0 or lower.

**Comment by amitshukla** [comment] 2016-01-30 06:41
Resolving since docs have been updated

**Comment by abronan** [comment] 2016-01-31 00:09
@amitshukla Re-opening it if you don't mind, this point is still relevant and not well explained in the documentation. Also relevant to the topic of rolling-upgrades of engines and Swarm which is impacted by such details.

**Comment by amitshukla** [comment] 2016-02-01 17:36
@rolfedh can you please look into this?

**Comment by rolfedh** [comment] 2016-02-04 18:35
I'll gladly add it to the documentation. However, mentioning it the doc will only help one out of every hundred customers who run into this error condition. You really have to do something about it in the software. This is a completely detectable condition. At a minimum, give them an error message that tells them how to solve the problem.

**Comment by rolfedh** [comment] 2016-02-07 00:00
@moxiegirl Where should we place this information in the doc?

**Comment by nishanttotla** [comment] 2018-05-30 18:19
Closing due to lack of activity. Please reopen if you wish to continue discussing it.

**Closed by nishanttotla** 2018-05-30 18:19 UTC
Labels: area/doc, priority/P2
