### ISSUE TITLE
Scheduler health filter issue? or manage? 

### ISSUE THREAD

**Issue by bryantidd** [docker/swarm#325] opened 2015-01-28 20:07 UTC
I join servers a, b, and c to Swarm cluster with Consul discovery at path A
I start a manage session from server d.
I terminate the joined servers and remove the key values from Consul leaving path A
I join a new server e to the same path A in Consul
I list server e correctly from server d.
I attempt a Docker run command from server d and receive:
Error response from daemon: No healthy node available in the cluster

Is this a problem with the health filter? Why does it seem to have a stale list.
How are we suppose to manage clusters that may be scaling in or out, or in transitional state?
What about housekeeping? Managing joins and leaves (especially with no leave command)?
Thanks looking forward to answers...

**Comment by resouer** [comment] 2015-01-29 15:15
The same issue https://github.com/docker/swarm/issues/323 I'm trying to address this.

**Comment by aluzzardi** [comment] 2015-01-29 22:18
Duplicate of https://github.com/docker/swarm/issues/197

It's going to be a priority soon for us.

**Closed by aluzzardi** 2015-01-29 22:18 UTC
