### ISSUE TITLE
swarm never tries to reconnect when it gets a dial tcp i/o timeout error

### ISSUE THREAD

**Issue by ekristen** [docker/swarm#1527] opened 2015-12-10 13:25 UTC
It appears that if a swarm master gets a `dial tcp 10.10.xxx.xxx:2376: i/o timeout` it never attempts to reconnect.

**Comment by ekristen** [comment] 2015-12-10 13:45
You have to restart the swarm master to get it to try again, I believe it should retry automatically with a backoff.

**Comment by dongluochen** [comment] 2015-12-10 20:08
@ekristen Thanks for reporting issue. It's a duplicate of #1185. Work item #1486 plans to fix this issue.

**Closed** 2015-12-10 20:09 UTC
Labels: kind/duplicate
