### ISSUE TITLE
swarm manage doesnt update swarm hosts

### ISSUE THREAD

**Issue by oba11** [docker/swarm#491] opened 2015-03-22 16:39 UTC
Try to manage swarm cluster from my local machine using etcd service discovery with below command
`docker run -d -p 2375:2375 --name swarm swarm manage -H tcp://0.0.0.0:2375 etcd://etcd:4001/swarm`

I have 3 hosts in the cluster which works fine with docker info

```
docker -H tcp://0.0.0.0:2375 info
Containers: 7
Nodes: 3
 ip-1-1-1-1: 1.1.1.1:2375
  └ Containers: 2
  └ Reserved CPUs: 0 / 1
  └ Reserved Memory: 0 B / 1.957 GiB
 ip-1-1-1-2: 1.1.1.2:2375
  └ Containers: 3
  └ Reserved CPUs: 0 / 1
  └ Reserved Memory: 128 MiB / 1.957 GiB
 ip-1-1-1-3: 1.1.1.3:2375
  └ Containers: 2
  └ Reserved CPUs: 0 / 1
  └ Reserved Memory: 0 B / 1.957 GiB
```

If I terminate one of the instances and the key is removed from etcd, swarm manage doesnt update the swarm host list unless I restart the swarm manage container.

**Comment by oba11** [comment] 2015-03-22 16:49
NB: Adding hosts work but not cleanup of stale of hosts

**Comment by abronan** [comment] 2015-03-22 20:09
Hey @oba11. We are aware of this, it's a duplicate of #197. It'll come very soon.

**Closed** 2015-03-22 20:10 UTC
Labels: duplicate

**Comment by oba11** [comment] 2015-03-23 05:49
Thanks @abronan
