### ISSUE TITLE
Docker network options not showing up in Swarm event stream

### ISSUE THREAD

**Issue by fredhsu** [docker/swarm#2008] opened 2016-03-22 19:07 UTC
I'm trying to get information about the networks created from `docker network create` from swarm.  Right now it doesn't appear that the network options are being sent in the event stream on swarm.  Here are the output of the swarm events and the commands used to create the network.  Specifically we will need access to macvlan/ipvlan options when those networks are created.  Since those are new features we verified with the standard docker bridge driver:

https://gist.github.com/fredhsu/0a6b90c03afc85094d86

**Comment by dongluochen** [comment] 2016-03-23 17:45
Network events are generated by Docker Engine, not Swarm. Is there something changed in the events? Or you want extra info?

**Comment by mavenugo** [comment] 2016-03-23 18:22
@dongluochen it seems the network options is not passed to the docker engine. is it possible that the swarm APIs are not complete for `docker network create` and not take care of all the UX options ?

**Comment by dongluochen** [comment] 2016-03-23 18:43
@mavenugo I can see the option in docker inspect. What might be missing? 

```
ubuntu@manager:~$ docker -H manager:2378 network create -d bridge -o com.docker.network.bridge.name=mynet mynet
301c4baf1c6ff0a2a93b546a6bf60a509db42fbfe79056ee4962722e3ac1176e
ubuntu@manager:~$ docker -H manager:2378 network ls | grep -i mynet
301c4baf1c6f        ip-172-19-109-234/mynet             bridge
ubuntu@manager:~$ docker -H manager:2378 network inspect mynet
[
    {
        "Name": "mynet",
        "Id": "301c4baf1c6ff0a2a93b546a6bf60a509db42fbfe79056ee4962722e3ac1176e",
        "Scope": "local",
        "Driver": "bridge",
        "IPAM": {
            "Driver": "default",
            "Options": {},
            "Config": [
                {
                    "Subnet": "172.21.0.0/16",
                    "Gateway": "172.21.0.1/16"
                }
            ]
        },
        "Containers": {},
        "Options": {
            "com.docker.network.bridge.name": "mynet"
        }
    }
]
```

The events from manager is: 
```
ubuntu@manager:~$ docker -H manager:2378 events
2016-03-23T18:38:15.508375122Z network create 301c4baf1c6ff0a2a93b546a6bf60a509db42fbfe79056ee4962722e3ac1176e (node.ip=172.19.109.234, node.name=ip-172-19-109-234, type=bridge, name=mynet, node.addr=172.19.109.234:2377, node.id=UEU6:6XMS:Y5IG:HPAS:7GCY:F3W2:S5S6:I4XT:COVL:4K73:GT4Y:PEEU)
```

Docker info output:
```
ubuntu@manager:~$ docker -H manager:2378 version
Client:
 Version:      1.10.2
 API version:  1.22
 Go version:   go1.5.3
 Git commit:   c3959b1
 Built:        Mon Feb 22 21:40:35 2016
 OS/Arch:      linux/amd64

Server:
 Version:      swarm/1.1.3
 API version:  1.22
 Go version:   go1.5.3
 Git commit:   7e9c6bd
 Built:        Wed Mar  2 00:15:12 UTC 2016
 OS/Arch:      linux/amd64
```

**Comment by mavenugo** [comment] 2016-03-23 20:03
@dongluochen can you try the same use-case without swarm in picture ?  (directly in docker engine) and see if the event has the options properly ?

**Comment by nerdalert** [comment] 2016-03-23 20:19
I think the question is if Swarm event streams are supposed to be truncated to notify about the event on an element, and then if you need the details you then query the API for the details.


In @fredhsu example, he wants to see network events so he watches the API events:
```
./docker-latest -H tcp://0.0.0.0:2376 events
```

Then an event occurs, but the stream does not show all of the details about the new network (specifically `--options`):

```
(event stream output) network create 2995fc449e7f220a0b3d048286895b43b38e532dbcaed69b2c0b39599b4e00d5 (name=mcv, type=macvlan)
```

If he wants to get all of the details about the network you would then need to do a GET on the net_id from the event stream:

```
$ curl http://localhost:2375/networks/2995fc449e7f220a0b3d048286895b43b38e532dbcaed69b2c0b39599b4e00d5
```

The GET on `networks/id` returns all of the information about the network that was not included in the event stream.
 
```
{"Name":"mcv","Id":"2995fc449e7f220a0b3d048286895b43b38e532dbcaed69b2c0b39599b4e00d5","Scope":"local","Driver":"macvlan","EnableIPv6":false,"IPAM":{"Driver":"default","Options":{},"Config":[{"Subnet":"172.16.86.0/24","Gateway":"172.16.86.2"}]},"Internal":false,"Containers":{},"Options":{"parent":"eth0"}}
```

Just checking if that is by design to limit the chattiness of the event stream to truncate it to some fields but not others or just something that needs to be added.

Thanks!

**Comment by dongluochen** [comment] 2016-03-23 20:43
@mavenugo Event from Docker Engine is the same for network create. 

```
ubuntu@ip-172-19-26-146:~$ docker network create -d bridge -o com.docker.network.bridge.name=testnet testnet
73118cd1d3ae2eb1c1fbbadf2998b776130707f907f87b41876cc63ad585a593
```

```
ubuntu@ip-172-19-26-146:~$ docker events
2016-03-23T20:40:53.904679456Z network create 73118cd1d3ae2eb1c1fbbadf2998b776130707f907f87b41876cc63ad585a593 (name=testnet, type=bridge)

ubuntu@ip-172-19-26-146:~$ docker network inspect testnet
[
    {
        "Name": "testnet",
        "Id": "73118cd1d3ae2eb1c1fbbadf2998b776130707f907f87b41876cc63ad585a593",
        "Scope": "local",
        "Driver": "bridge",
        "EnableIPv6": false,
        "IPAM": {
            "Driver": "default",
            "Options": {},
            "Config": [
                {
                    "Subnet": "172.20.0.0/16",
                    "Gateway": "172.20.0.1/16"
                }
            ]
        },
        "Internal": false,
        "Containers": {},
        "Options": {
            "com.docker.network.bridge.name": "testnet"
        }
    }
]
```

**Comment by amitshukla** [comment] 2016-03-24 17:33
Closing since this is not a Swarm issue. The behavior of Swarm and Engine is the same.

**Closed by amitshukla** 2016-03-24 17:33 UTC
Labels: kind/question
