### ISSUE TITLE
No retries when Consul is unreachable for watch and never participates to re-election

### ISSUE THREAD

**Issue by ahmetalpbalkan** [docker/swarm#1088] opened 2015-07-26 20:56 UTC
I have three swarm manager nodes (deployed at nearly the same times) each of them spin up a `progrium/consul` container and a `swarm manage` container (using docker-compose). All this happens automatically. And these containers  have `restart: always`.

All containers come up successfully, however (probably) during bootstrapping of the Consul cluster, consul containers becomes sort of unavailable and 'some' Swarm Managers get `connection refused` error. 

After they point, they totally don't retry and just fail to respond requests with `No elected primary cluster manager` all the time. The consul cluster becomes available after a while (because all managers eventually know about all nodes) however they do not re-join election nor attempt to discover if they're a leader or replica.

When these manager containers get restarted, they just work fine and discover the leader. I think we are missing retries around access to Consul.

Here are logs from managers:

### swarm manager 1

this works fine 

```
root@swarm-master-0:~# docker logs -f compose_swarm_1
time="2015-07-26T20:39:47Z" level=info msg="Listening for HTTP" addr=":2375" proto=tcp
time="2015-07-26T20:39:47Z" level=info msg="Cluster leadership lost"
time="2015-07-26T20:39:47Z" level=info msg="New leader elected: 10.0.0.4:2376"
time="2015-07-26T20:39:47Z" level=info msg="Cluster leadership acquired"
time="2015-07-26T20:39:51Z" level=info msg="Registered Engine swarm-node-1 at 192.168.0.4:2375"
time="2015-07-26T20:39:52Z" level=info msg="Registered Engine swarm-node-3 at 192.168.0.9:2375"
time="2015-07-26T20:39:57Z" level=info msg="Registered Engine swarm-node-5 at 192.168.0.8:2375"
time="2015-07-26T20:39:57Z" level=info msg="Registered Engine swarm-node-0 at 192.168.0.7:2375"
time="2015-07-26T20:39:57Z" level=info msg="Registered Engine swarm-node-2 at 192.168.0.6:2375"
time="2015-07-26T20:40:01Z" level=info msg="Registered Engine swarm-node-4 at 192.168.0.5:2375"
```

### swarm manager 2

```
azureuser@swarm-master-1:~$ docker logs -f compose_swarm_1
time="2015-07-26T20:39:31Z" level=info msg="Listening for HTTP" addr=":2375" proto=tcp
time="2015-07-26T20:39:31Z" level=info msg="Cluster leadership lost"
time="2015-07-26T20:39:32Z" level=error msg="consul: Get http://10.0.0.4:8500/v1/kv/docker/swarm/leader?wait=15000ms: dial tcp 10.0.0.4:8500: connection refused"
time="2015-07-26T20:39:32Z" level=error msg="consul: Get http://10.0.0.4:8500/v1/kv/docker/swarm/leader?wait=15000ms: dial tcp 10.0.0.4:8500: connection refused"
time="2015-07-26T20:39:32Z" level=error msg="failed to create session: Put http://10.0.0.4:8500/v1/session/create: dial tcp 10.0.0.4:8500: connection refused"
time="2015-07-26T20:39:32Z" level=error msg="consul: Get http://10.0.0.4:8500/v1/kv/nodes/docker/swarm/nodes?recurse=&wait=15000ms: dial tcp 10.0.0.4:8500: connection refused"
time="2015-07-26T20:39:32Z" level=error msg="Discovery error: Unexpected watch error"
time="2015-07-26T20:39:53Z" level=info msg="Registered Engine swarm-node-1 at 192.168.0.4:2375"
time="2015-07-26T20:39:53Z" level=info msg="Registered Engine swarm-node-3 at 192.168.0.9:2375"
time="2015-07-26T20:39:57Z" level=info msg="Registered Engine swarm-node-5 at 192.168.0.8:2375"
time="2015-07-26T20:39:57Z" level=info msg="Registered Engine swarm-node-0 at 192.168.0.7:2375"
time="2015-07-26T20:39:57Z" level=info msg="Registered Engine swarm-node-2 at 192.168.0.6:2375"
time="2015-07-26T20:40:01Z" level=info msg="Registered Engine swarm-node-4 at 192.168.0.5:2375"

(when request comes) time="2015-07-26T20:43:59Z" level=error msg="HTTP error: No elected primary cluster manager" status=500
```

### swarm manager 3

```
azureuser@swarm-master-2:~$ docker logs -f compose_swarm_1
time="2015-07-26T20:39:38Z" level=info msg="Listening for HTTP" addr=":2375" proto=tcp
time="2015-07-26T20:39:38Z" level=info msg="Cluster leadership lost"
time="2015-07-26T20:39:38Z" level=error msg="consul: Get http://10.0.0.4:8500/v1/kv/docker/swarm/leader?wait=15000ms: dial tcp 10.0.0.4:8500: connection refused"
time="2015-07-26T20:39:38Z" level=error msg="consul: Get http://10.0.0.4:8500/v1/kv/docker/swarm/leader?wait=15000ms: dial tcp 10.0.0.4:8500: connection refused"
time="2015-07-26T20:39:38Z" level=error msg="failed to create session: Put http://10.0.0.4:8500/v1/session/create: dial tcp 10.0.0.4:8500: connection refused"
time="2015-07-26T20:39:38Z" level=error msg="consul: Get http://10.0.0.4:8500/v1/kv/nodes/docker/swarm/nodes?recurse=&wait=15000ms: dial tcp 10.0.0.4:8500: connection refused"
time="2015-07-26T20:39:38Z" level=error msg="Discovery error: Unexpected watch error"
time="2015-07-26T20:39:58Z" level=info msg="Registered Engine swarm-node-5 at 192.168.0.8:2375"
time="2015-07-26T20:39:58Z" level=info msg="Registered Engine swarm-node-3 at 192.168.0.9:2375"
time="2015-07-26T20:39:58Z" level=info msg="Registered Engine swarm-node-1 at 192.168.0.4:2375"
time="2015-07-26T20:39:58Z" level=info msg="Registered Engine swarm-node-0 at 192.168.0.7:2375"
time="2015-07-26T20:39:58Z" level=info msg="Registered Engine swarm-node-2 at 192.168.0.6:2375"
time="2015-07-26T20:40:01Z" level=info msg="Registered Engine swarm-node-4 at 192.168.0.5:2375"
time="2015-07-26T20:43:27Z" level=error msg="HTTP error: No elected primary cluster manager" status=500
```

**Comment by abronan** [comment] 2015-07-27 07:24
Hi @ahmetalpbalkan, thanks for reporting back the issue. There is already a PR: #1078 to fix this :)

This also looks like a duplicate of #1025.

**Comment by ahmetalpbalkan** [comment] 2015-07-27 14:38
Ah neat, feel free to close.

**Closed** 2015-07-27 16:41 UTC
Labels: kind/duplicate
