### ISSUE TITLE
Swarm node disconnects after SSH terminal closes

### ISSUE THREAD

**Issue by doronl** [docker/swarm#1343] opened 2015-10-27 09:19 UTC
Hi,

  I set up a swarm cluster, when I run on the host\node:

  docker daemon -H tcp://0.0.0.0:2375 I get the daemon output to the console and everything works fine but when I close the terminal or the SSH connection disconnects I get:

  Error response from daemon: dial tcp <node IP>:2375: connection refused

  when runing commands on the cluster manager.

  It seems the deamon is not listing to the port anymore… running on the host netstat -an|grep :2375 shows nothing is listening to 2375 .

  Isn’t a daemon supposed to listen after terminal closes and SSH session disconnects ?

Thanks,
 Doron

**Comment by abronan** [comment] 2015-10-27 16:12
Hi @doronl, not if the daemon process is attached to your terminal session. Make sure you run the daemon as a background process using `nohuo`/`&`. This way it will keep running when you close your terminal session.

**Comment by doronl** [comment] 2015-10-27 21:20
Thanks @abronan! it looks like it did the trick… funny it was not mentioned in any example I have seen so far…

A small feedback if I may, lMO this should be built in capability rather than using a wrapper command, when I run something in daemon mode I expect it run in the background.

**Comment by aluzzardi** [comment] 2015-10-29 08:23
Hey @doronl - sorry about that. It's a documentation problem.

You should just update your docker startup configuration to add the right `-H` flag.

The problem is, that configuration depends on which operating system you are using, therefore it's tough to document.

On Ubuntu, that would be `/etc/default/docker` (`DOCKER_OPTS` I believe)

**Comment by doronl** [comment] 2015-11-01 07:46
OK, thanks @aluzzardi! this should cover it :+1:  ... but IMO this aspect should be more visible.

**Comment by abronan** [comment] 2016-01-31 00:25
@amitshukla Why closing? There is a reference to this issue in #1568 that will close it automatically when the PR is merged. It is still not merged yet so I'm re-opening to make sure this is dealt with.

**Closed** 2016-02-01 17:09 UTC
Labels: area/doc, kind/question

**Comment by amitshukla** [comment] 2016-02-04 19:36
@abronan I must have accidentally closed it - sorry
