### ISSUE TITLE
swarm docker ps shows container Up, node docker ps shows container Exited

### ISSUE THREAD

**Issue by alexebird** [docker/swarm#1383] opened 2015-11-05 19:26 UTC
We have been seeing this intermittently on 0.4.0 and now 1.0.0. We're running a single swarm manager. 

```
# talking to swarm
my-laptop $ docker ps -a | grep d3fe34257a69
d3fe34257a69 grnds/tp_ci:latest "/bin/bash -c 'git cl" 2 hours ago Up 2 hours ...

# talking to node's docker-engine
core@node1 ~ $ docker ps -a | grep d3fe34257a69
d3fe34257a69 grnds/tp_ci:latest "/bin/bash -c 'git c 2 hours ago Exited (1) 2 hours ago ...
```

```
# talking to swarm
my-laptop $ docker version
Client:
 Version:      1.9.0
 API version:  1.21
 Go version:   go1.4.2
 Git commit:   76d6bc9
 Built:        Tue Nov  3 17:43:42 UTC 2015
 OS/Arch:      linux/amd64

Server:
 Version:      swarm/1.0.0
 API version:  1.21
 Go version:   go1.5.1
 Git commit:   087e245
 Built:        
 OS/Arch:      linux/amd64
```

```
# talking to swarm manager's docker-engine
core@swarm-manager ~ $ docker version
Client version: 1.7.1
Client API version: 1.19
Go version (client): go1.4.2
Git commit (client): df2f73d-dirty
OS/Arch (client): linux/amd64
Server version: 1.7.1
Server API version: 1.19
Go version (server): go1.4.2
Git commit (server): df2f73d-dirty
OS/Arch (server): linux/amd64
```

```
# talking to node's docker-engine
core@node1 ~ $ docker version
Client version: 1.7.1
Client API version: 1.19
Go version (client): go1.4.2
Git commit (client): df2f73d-dirty
OS/Arch (client): linux/amd64
Server version: 1.7.1
Server API version: 1.19
Go version (server): go1.4.2
Git commit (server): df2f73d-dirty
OS/Arch (server): linux/amd64
```

We can get expected behavior by restarting the swarm manager.

Let me know if I can provide any more info!

**Comment by abronan** [comment] 2015-11-05 21:57
Hi @alexebird, thank you for reporting the issue. Just curious, does it show up the same output if you use docker `1.9`? I'm keeping an eye on this as I'm using `1.9` and haven't seen this behavior before.

**Comment by alexebird** [comment] 2015-11-05 22:35
Thanks for the quick response. Unfortunately we'll have to get back to you on that as we're using CoreOS stable (without fleet/etcd) and won't have access to docker 1.9 until they include it.

**Comment by chromerobv** [comment] 2015-11-19 21:14
i see this same thing on docker 1.8.2, stuck in the same boat as above have to wait until there is an official 1.9 package on centOS.

**Comment by Spritekin** [comment] 2015-12-04 03:04
I'm also using CoreOS and had the same problem. Restarting the master solved the problem and I haven't seen it since. I think it was because some mesos node configuration (and restart) problem.

**Comment by alexebird** [comment] 2015-12-17 19:31
We haven't been seeing this since moving to Ubuntu 15.10, docker 1.9, swarm 1.0.0.

**Comment by abronan** [comment] 2015-12-17 19:35
Thanks for the heads up @alexebird, I'll close this one but feel free to comment below if you can reproduce or have any steps to reproduce.

**Closed by abronan** 2015-12-17 19:35 UTC
Labels: kind/bug
