### ISSUE TITLE
test failure "zk discovery: watch for changes"

### ISSUE THREAD

**Issue by dongluochen** [docker/swarm#2575] opened 2016-12-21 00:59 UTC
This failure happens frequently where Swarm join may be rejected by zookeeper. 

```
not ok 17 zk discovery: watch for changes
# (from function `retry' in file discovery/../helpers.bash, line 80,
#  in test file discovery/zk.bats, line 61)
#   `retry 10 1 discovery_check_swarm_info' failed
# d86d35f590ca3a21bd132623e84f3961bf2f6def14a338315b99690fdd84347f
# time="2016-12-20T23:51:18Z" level=debug msg="Initializing discovery service" name=zk uri="127.0.0.1:7779/test"
# time="2016-12-20T23:51:18Z" level=info msg="Initializing discovery without TLS"
# 2016/12/20 23:51:18 Connected to 127.0.0.1:7779
# time="2016-12-20T23:51:18Z" level=debug msg="Initializing strategy" name=spread
# time="2016-12-20T23:51:18Z" level=debug msg="Initializing filter" name=health
# time="2016-12-20T23:51:18Z" level=debug msg="Initializing filter" name=port
# time="2016-12-20T23:51:18Z" level=debug msg="Initializing filter" name=containerslots
# time="2016-12-20T23:51:18Z" level=debug msg="Initializing filter" name=dependency
# time="2016-12-20T23:51:18Z" level=debug msg="Initializing filter" name=affinity
# time="2016-12-20T23:51:18Z" level=debug msg="Initializing filter" name=constraint
# time="2016-12-20T23:51:18Z" level=debug msg="Initializing cluster" name=swarm
# time="2016-12-20T23:51:18Z" level=debug msg="Registering HTTP route" method=HEAD route="/containers/{name:.*}/archive"
# 2016/12/20 23:51:18 Authentication failed: read tcp 127.0.0.1:50360->127.0.0.1:7779: read: connection reset by peer
# time="2016-12-20T23:51:18Z" level=error msg="Discovery error: zk: could not connect to a server"
...
# time="2016-12-20T23:51:19Z" level=debug msg="HTTP request received" method=GET uri="/_ping"
# time="2016-12-20T23:51:19Z" level=debug msg="HTTP request received" method=GET uri="/v1.24/info"
# 2016/12/20 23:51:19 Connected to 127.0.0.1:7779
# 2016/12/20 23:51:19 Authenticated: id=97142563086663680, timeout=10000
# time="2016-12-20T23:51:19Z" level=debug msg="Watch triggered with 0 nodes" discovery=zk
# Swarm join #0: 127.0.0.1:5310 zk://127.0.0.1:7779/test
# time="2016-12-20T23:51:21Z" level=debug msg="Initializing discovery service" name=zk uri="127.0.0.1:7779/test"
# time="2016-12-20T23:51:21Z" level=info msg="Initializing discovery without TLS"
# time="2016-12-20T23:51:21Z" level=info msg="Registering on the discovery service every 1s..." addr="127.0.0.1:5310" discovery="zk://127.0.0.1:7779/test"
# 2016/12/20 23:51:21 Connected to 127.0.0.1:7779
# 2016/12/20 23:51:21 Authenticated: id=97142563086663681, timeout=10000
# Swarm join #1: 127.0.0.1:5311 zk://127.0.0.1:7779/test
# time="2016-12-20T23:51:21Z" level=debug msg="Initializing discovery service" name=zk uri="127.0.0.1:7779/test"
# time="2016-12-20T23:51:21Z" level=info msg="Initializing discovery without TLS"
# time="2016-12-20T23:51:21Z" level=info msg="Registering on the discovery service every 1s..." addr="127.0.0.1:5311" discovery="zk://127.0.0.1:7779/test"
# 2016/12/20 23:51:21 Connected to 127.0.0.1:7779
# 2016/12/20 23:51:21 Authenticated: id=97142563086663682, timeout=10000
# time="2016-12-20T23:51:21Z" level=debug msg="Watch triggered with 1 nodes" discovery=zk
# time="2016-12-20T23:51:21Z" level=debug msg="Start monitoring events" id="VJFH:LVOI:XAWC:6JBY:TCYO:EBOY:PPI3:HVEV:XZ5C:EWC4:AJBO:VJTH" name=node-0
# time="2016-12-20T23:51:21Z" level=info msg="Registered Engine node-0 at 127.0.0.1:5310"
# time="2016-12-20T23:51:21Z" level=debug msg="removing duplicate containers from Node VJFH:LVOI:XAWC:6JBY:TCYO:EBOY:PPI3:HVEV:XZ5C:EWC4:AJBO:VJTH"
# time="2016-12-20T23:51:21Z" level=debug msg="HTTP request received" method=GET uri="/_ping"
# time="2016-12-20T23:51:21Z" level=debug msg="HTTP request received" method=GET uri="/v1.24/info"
# Containers: 0 Running: 0 Paused: 0 Stopped: 0 Images: 0 Server Version: swarm/1.2.5 Role: primary Strategy: spread Filters: health, port, containerslots, dependency, affinity, constraint Nodes: 1 node-0: 127.0.0.1:5310 └ ID: VJFH:LVOI:XAWC:6JBY:TCYO:EBOY:PPI3:HVEV:XZ5C:EWC4:AJBO:VJTH └ Status: Healthy └ Containers: 0 (0 Running, 0 Paused, 0 Stopped) └ Reserved CPUs: 0 / 2 └ Reserved Memory: 0 B / 4.053 GiB └ Labels: kernelversion=3.19.0-25-generic, operatingsystem=Debian GNU/Linux 8 (jessie) (containerized), storagedriver=aufs └ UpdatedAt: 2016-12-20T23:51:21Z └ ServerVersion: 1.14.0-dev Plugins: Volume: Network: Swarm: NodeID: Is Manager: false Node Address: Kernel Version: 3.19.0-25-generic Operating System: linux Architecture: amd64 CPUs: 2 Total Memory: 4.053 GiB Name: b4c8ee4c2f59 Docker Root Dir: Debug Mode (client): false Debug Mode (server): false WARNING: No kernel memory limit support Experimental: true Live Restore Enabled: false
# time="2016-12-20T23:51:21Z" level=debug msg="HTTP request received" method=GET uri="/_ping"
# time="2016-12-20T23:51:21Z" level=debug msg="HTTP request received" method=GET uri="/v1.24/info"
# time="2016-12-20T23:51:22Z" level=info msg="Registering on the discovery service every 1s..." addr="127.0.0.1:5310" discovery="zk://127.0.0.1:7779/test"
# time="2016-12-20T23:51:22Z" level=info msg="Registering on the discovery service every 1s..." addr="127.0.0.1:5311" discovery="zk://127.0.0.1:7779/test"
...
# time="2016-12-20T23:51:31Z" level=info msg="Registering on the discovery service every 1s..." addr="127.0.0.1:5311" discovery="zk://127.0.0.1:7779/test"
# Command "discovery_check_swarm_info" failed 10 times. Output: WARNING: No kernel memory limit support
# Stopping 84abe0ef4c5fe423c4062df7e623c657eef4428ab15b0b7c179609e3d800d64a
# /go/src/github.com/docker/swarm/test/integration/discovery/../helpers.bash: line 48: 24262 Terminated              "$SWARM_BINARY" -l debug -experimental manage -H "$host" --heartbeat=1s $discovery
# /go/src/github.com/docker/swarm/test/integration/discovery/../helpers.bash: line 48: 25177 Terminated              "$SWARM_BINARY" -l debug join --heartbeat=1s --ttl=10s --advertise="$h" "$addr"
# /go/src/github.com/docker/swarm/test/integration/discovery/../helpers.bash: line 48: 25205 Terminated              "$SWARM_BINARY" -l debug join --heartbeat=1s --ttl=10s --advertise="$h" "$addr"
# Stopping 2c65540e20f7ef17eabb543fdac8177991aabaada362910c7a5620e25faecb17
# swarm_integration_zk
```

**Comment by nishanttotla** [comment] 2017-01-11 16:19
This failure is happening much more frequently in the CI now.

**Comment by dongluochen** [comment] 2017-01-12 23:08
The problem seems to be zookeeper doesn't publish node list update in the test. Where there are 2 nodes join zk, it only triggers 1 node update. 

```
# Swarm join #0: 127.0.0.1:5476 zk://127.0.0.1:7276/test
...
# Swarm join #1: 127.0.0.1:5477 zk://127.0.0.1:7276/test
...
# time="2017-01-11T23:49:58Z" level=debug msg="Watch triggered with 1 nodes" discovery=zk 
... 
# time="2017-01-11T23:49:58Z" level=info msg="Registered Engine node-0 at 127.0.0.1:5476" 
```

Full log is attached. The issue is I cannot reproduce it locally. 

```
# 2017/01/11 23:49:55 Connected to 127.0.0.1:7276
# time="2017-01-11T23:49:55Z" level=debug msg="Registering HTTP route" method=POST route="/containers/{name:.*}/copy" 
# 2017/01/11 23:49:55 Authentication failed: EOF
# time="2017-01-11T23:49:55Z" level=error msg="Discovery error: zk: could not connect to a server" 
# time="2017-01-11T23:49:55Z" level=debug msg="Registering HTTP route" method=POST route="/networks/{networkid:.*}/disconnect" 
# time="2017-01-11T23:49:55Z" level=debug msg="Registering HTTP route" method=POST route="/containers/{name:.*}/kill" 
# time="2017-01-11T23:49:55Z" level=debug msg="Registering HTTP route" method=POST route="/containers/{name:.*}/pause" 
# time="2017-01-11T23:49:55Z" level=debug msg="Registering HTTP route" method=POST route="/containers/{name:.*}/rename" 
# time="2017-01-11T23:49:55Z" level=debug msg="Registering HTTP route" method=POST route="/containers/{name:.*}/wait" 
# time="2017-01-11T23:49:55Z" level=debug msg="Registering HTTP route" method=POST route="/containers/create" 
# time="2017-01-11T23:49:55Z" level=debug msg="Registering HTTP route" method=POST route="/networks/create" 
# time="2017-01-11T23:49:55Z" level=debug msg="Registering HTTP route" method=POST route="/volumes/create" 
# time="2017-01-11T23:49:55Z" level=debug msg="Registering HTTP route" method=POST route="/containers/{name:.*}/update" 
# time="2017-01-11T23:49:55Z" level=debug msg="Registering HTTP route" method=POST route="/containers/{name:.*}/exec" 
# time="2017-01-11T23:49:55Z" level=debug msg="Registering HTTP route" method=POST route="/networks/{networkid:.*}/connect" 
# time="2017-01-11T23:49:55Z" level=debug msg="Registering HTTP route" method=POST route="/build" 
# time="2017-01-11T23:49:55Z" level=debug msg="Registering HTTP route" method=POST route="/images/create" 
# time="2017-01-11T23:49:55Z" level=debug msg="Registering HTTP route" method=PUT route="/containers/{name:.*}/archive" 
# time="2017-01-11T23:49:55Z" level=debug msg="Registering HTTP route" method=DELETE route="/containers/{name:.*}" 
# time="2017-01-11T23:49:55Z" level=debug msg="Registering HTTP route" method=DELETE route="/images/{name:.*}" 
# time="2017-01-11T23:49:55Z" level=debug msg="Registering HTTP route" method=DELETE route="/networks/{networkid:.*}" 
# time="2017-01-11T23:49:55Z" level=debug msg="Registering HTTP route" method=DELETE route="/volumes/{name:.*}" 
# time="2017-01-11T23:49:55Z" level=debug msg="Watchdog enabled" 
# time="2017-01-11T23:49:55Z" level=info msg="Listening for HTTP" addr="127.0.0.1:6677" proto=tcp 
# time="2017-01-11T23:49:56Z" level=debug msg="HTTP request received" method=GET uri="/v1.24/info" 
# time="2017-01-11T23:49:56Z" level=debug msg="HTTP request received" method=GET uri="/v1.24/info" 
# time="2017-01-11T23:49:56Z" level=debug msg="HTTP request received" method=GET uri="/v1.24/info" 
# time="2017-01-11T23:49:56Z" level=debug msg="HTTP request received" method=GET uri="/v1.24/info" 
# 2017/01/11 23:49:56 Connected to 127.0.0.1:7276
# 2017/01/11 23:49:57 Authenticated: id=97267128495243264, timeout=10000
# 2017/01/11 23:49:57 Re-submitting `0` credentials after reconnect
# time="2017-01-11T23:49:57Z" level=debug msg="Watch triggered with 0 nodes" discovery=zk 
# Swarm join #0: 127.0.0.1:5476 zk://127.0.0.1:7276/test
# time="2017-01-11T23:49:58Z" level=debug msg="Initializing discovery service" name=zk uri="127.0.0.1:7276/test" 
# time="2017-01-11T23:49:58Z" level=info msg="Initializing discovery without TLS" 
# time="2017-01-11T23:49:58Z" level=info msg="Registering on the discovery service every 1s..." addr="127.0.0.1:5476" discovery="zk://127.0.0.1:7276/test" 
# 2017/01/11 23:49:58 Connected to 127.0.0.1:7276
# Swarm join #1: 127.0.0.1:5477 zk://127.0.0.1:7276/test
# 2017/01/11 23:49:58 Authenticated: id=97267128495243265, timeout=10000
# 2017/01/11 23:49:58 Re-submitting `0` credentials after reconnect
# time="2017-01-11T23:49:58Z" level=debug msg="Initializing discovery service" name=zk uri="127.0.0.1:7276/test" 
# time="2017-01-11T23:49:58Z" level=info msg="Initializing discovery without TLS" 
# time="2017-01-11T23:49:58Z" level=info msg="Registering on the discovery service every 1s..." addr="127.0.0.1:5477" discovery="zk://127.0.0.1:7276/test" 
# 2017/01/11 23:49:58 Connected to 127.0.0.1:7276
# 2017/01/11 23:49:58 Authenticated: id=97267128495243266, timeout=10000
# 2017/01/11 23:49:58 Re-submitting `0` credentials after reconnect
# time="2017-01-11T23:49:58Z" level=debug msg="Watch triggered with 1 nodes" discovery=zk 
# time="2017-01-11T23:49:58Z" level=debug msg="Start monitoring events" id="I22Z:VV2V:UCNL:JXYX:TYH6:SUUE:BC4I:YWWT:FRGS:JTFL:GBHN:K3FO" name=node-0 
# time="2017-01-11T23:49:58Z" level=info msg="Registered Engine node-0 at 127.0.0.1:5476" 
# time="2017-01-11T23:49:58Z" level=debug msg="removing duplicate containers from Node I22Z:VV2V:UCNL:JXYX:TYH6:SUUE:BC4I:YWWT:FRGS:JTFL:GBHN:K3FO" 
# time="2017-01-11T23:49:58Z" level=debug msg="HTTP request received" method=GET uri="/v1.24/info" 
# time="2017-01-11T23:49:59Z" level=info msg="Registering on the discovery service every 1s..." addr="127.0.0.1:5476" discovery="zk://127.0.0.1:7276/test" 
# time="2017-01-11T23:49:59Z" level=info msg="Registering on the discovery service every 1s..." addr="127.0.0.1:5477" discovery="zk://127.0.0.1:7276/test" 
# time="2017-01-11T23:49:59Z" level=debug msg="HTTP request received" method=GET uri="/v1.24/info" 
```

**Comment by nishanttotla** [comment] 2017-01-13 04:17
@dongluochen you're right! Just tried reproducing locally but it doesn't work. Let's track it for a few more days, we might have to adjust parameters again.

**Comment by nishanttotla** [comment] 2017-06-21 00:13
Closing because I haven't seen failures for a while.

**Closed by nishanttotla** 2017-06-21 00:13 UTC
Labels: area/discovery
