### ISSUE TITLE
docker rm makes the cluster unresponsive 

### ISSUE THREAD

**Issue by kevinsimper** [docker/swarm#1173] opened 2015-08-27 15:05 UTC
Sometimes if you do a `docker rm` on multiple containers from the commandline, the swarm cluster will be unresponsive for some time after, so a request like `docker info` hangs. After some time it is back to normal without any problems.
 
I tried to find out if you could debug the `swarm manage` process, but doing `docker logs` did not show anything.

Any help to figure out why the cluster stales?

It is started via docker-machine
```
docker-machine create \
-d virtualbox \
--swarm \
--swarm-master \
--swarm-discovery token://$SWARM_ID \
swarm-master
```

**Comment by kevinsimper** [comment] 2015-08-31 14:49
I also found that this command makes it unresponsiveable, doing something that does a lot in a row.

`docker kill $(docker ps -q)`

**Comment by vieux** [comment] 2015-08-31 21:57
@jimmyxian can you please take a look ? Thanks.

**Comment by jimmyxian** [comment] 2015-09-01 06:15
@vieux Yeah..

**Comment by jimmyxian** [comment] 2015-09-01 06:29
@kevinsimper 
Can you provide the following info?
- swarm --version
- `docker -H <swarm address> info`
- `docker -H <docker address> info`

**Comment by kevinsimper** [comment] 2015-09-02 20:23
I tested it today, but of cause i could not reproduce today, so that is good i think.

I will post again if I experience it again.
```
$ docker -H 192.168.99.106:3376 info
Containers: 67
Images: 15
Role: primary
Strategy: spread
Filters: affinity, health, constraint, port, dependency
Nodes: 3
 swarm-agent-00: 192.168.99.107:2376
  └ Containers: 23
  └ Reserved CPUs: 0 / 1
  └ Reserved Memory: 0 B / 1.022 GiB
  └ Labels: executiondriver=native-0.2, kernelversion=4.0.5-boot2docker, operatingsystem=Boot2Docker 1.7.0 (TCL 6.3); master : 7960f90 - Thu Jun 18 18:31:45 UTC 2015, provider=virtualbox, storagedriver=aufs
 swarm-agent-01: 192.168.99.108:2376
  └ Containers: 22
  └ Reserved CPUs: 0 / 1
  └ Reserved Memory: 0 B / 1.022 GiB
  └ Labels: executiondriver=native-0.2, kernelversion=4.0.5-boot2docker, operatingsystem=Boot2Docker 1.7.0 (TCL 6.3); master : 7960f90 - Thu Jun 18 18:31:45 UTC 2015, provider=virtualbox, storagedriver=aufs
 swarm-master: 192.168.99.106:2376
  └ Containers: 22
  └ Reserved CPUs: 0 / 1
  └ Reserved Memory: 0 B / 1.022 GiB
  └ Labels: executiondriver=native-0.2, kernelversion=4.0.5-boot2docker, operatingsystem=Boot2Docker 1.7.0 (TCL 6.3); master : 7960f90 - Thu Jun 18 18:31:45 UTC 2015, provider=virtualbox, storagedriver=aufs
CPUs: 3
Total Memory: 3.065 GiB
Name: 59a586acbed2
MacBook-Pro-2:blackbeardapp kevinsimper$ docker -H 192.168.99.106:2376 info
Containers: 22
Images: 59
Storage Driver: aufs
 Root Dir: /mnt/sda1/var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 103
 Dirperm1 Supported: true
Execution Driver: native-0.2
Logging Driver: json-file
Kernel Version: 4.0.5-boot2docker
Operating System: Boot2Docker 1.7.0 (TCL 6.3); master : 7960f90 - Thu Jun 18 18:31:45 UTC 2015
CPUs: 1
Total Memory: 996.2 MiB
Name: swarm-master
ID: WM4O:7PI5:RMGJ:SCIG:35NP:7VPN:FULR:3NRI:RBUS:LGQZ:CGGI:PPLO
Debug mode (server): true
File Descriptors: 59
Goroutines: 94
System Time: 2015-09-02T11:55:08.614636343Z
EventsListeners: 1
Init SHA1:
Init Path: /usr/local/bin/docker
Docker Root Dir: /mnt/sda1/var/lib/docker
Username: kevinsimper
Registry: https://index.docker.io/v1/
Labels:
 provider=virtualbox
```
![swarm](https://cloud.githubusercontent.com/assets/1126497/9643270/34c8dd30-51c1-11e5-9d22-300dac79e186.gif)

**Comment by jimmyxian** [comment] 2015-09-06 01:03
@kevinsimper OK

**Comment by chanwit** [comment] 2015-09-06 02:12
@kevinsimper is it possible to be caused by another process or at the OS-level? Like when we're doing something bulky, our machine looks hanging.

**Comment by kevinsimper** [comment] 2015-09-06 11:33
@chanwit It could most likely! It was just a little too long time, so I did not thought it was that.

**Comment by chanwit** [comment] 2015-09-06 11:44
@jimmyxian shall we close this issue then?

@kevinsimper please feel free to re-open it when you find something strange again.

**Comment by jimmyxian** [comment] 2015-09-06 12:38
@vieux Yeah

**Closed by jimmyxian** 2015-09-06 12:38 UTC
Labels: area/API
