### ISSUE TITLE
support for volume labels 

### ISSUE THREAD

**Issue by wallnerryan** [docker/swarm#2245] opened 2016-05-16 19:11 UTC
Volume labels were recently added to docker. See https://github.com/docker/docker/pull/21270

Creating  a label via docker to swarm.

```
docker volume create -d flocker --label owner=ryan --name test4 -o size=75G
```

Output 
```
$ docker volume inspect test4
[
    {
        "Name": "test4",
        "Driver": "flocker",
        "Mountpoint": "",
        "Labels": null
    }
]
```

Expected response 

```
$ docker volume inspect test4
[
    {
        "Name": "test4",
        "Driver": "flocker",
        "Mountpoint": "",
        "Labels": {
            "owner": "ryan"
        }
    }
]
```

The only way to see the label is to SSH to the node and run `inspect` on the local docker daemon.

```
docker-machine ssh mha-demo1
root@mha-demo1:~# docker volume inspect test4
[
    {
        "Name": "test4",
        "Driver": "flocker",
        "Mountpoint": "/flocker/8c22e40c-2519-4db6-9e9b-904bbbb6ea98",
        "Labels": {
            "owner": "ryan"
        }
    }
]
```

`docker version` to swarm from client
```
Client:
 Version:      1.11.1
 API version:  1.23
 Go version:   go1.5.4
 Git commit:   5604cbe
 Built:        Wed Apr 27 00:34:20 2016
 OS/Arch:      darwin/amd64

Server:
 Version:      swarm/1.2.2
 API version:  1.22
 Go version:   go1.5.4
 Git commit:   34e3da3
 Built:        Mon May  9 17:03:22 UTC 2016
 OS/Arch:      linux/amd64
```

`docker version` from a docker host in the swarm cluster.
```
docker version
Client:
 Version:      1.11.1
 API version:  1.23
 Go version:   go1.5.4
 Git commit:   5604cbe
 Built:        Tue Apr 26 23:30:23 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.11.1
 API version:  1.23
 Go version:   go1.5.4
 Git commit:   5604cbe
 Built:        Tue Apr 26 23:30:23 2016
 OS/Arch:      linux/amd64
```

**Comment by allencloud** [comment] 2016-05-19 18:05
I reproduced this issue.
Actually I think this is an issue of Docker Engine.
@wallnerryan @nishanttotla 

As I call `192.168.0.11:2376/volumes` against docker engine with no labels:
```
{
  "Volumes": [
    {
      "Name": "allen",
      "Driver": "local",
      "Mountpoint": "/var/lib/docker/volumes/allen/_data",
      "Labels": null
    },
    {
      "Name": "test5",
      "Driver": "local",
      "Mountpoint": "/var/lib/docker/volumes/test5/_data",
      "Labels": null
    }
  ],
  "Warnings": null
}
```

while calling `192.168.0.11:2376/volumes/test5` has label details:
```
{
  "Name": "test5",
  "Driver": "local",
  "Mountpoint": "/var/lib/docker/volumes/test5/_data",
  "Labels": {
    "owner": "ryan"
  }
}
```

I will try t report this in docker/docker.

**Comment by alexmavr** [comment] 2016-05-19 18:52
An appropriate bump in the engine-api vendoring should fix this by properly vendoring a newer version of the `types.Volume` struct which includes the `Labels` field. 

Speficially, the `engine-api` vendor of swarm needs to include the following two commits in order to support labels for volumes and networks:
https://github.com/docker/engine-api/commit/37d4a7ad84d56164b127b12d1c720ad430143973
https://github.com/docker/engine-api/commit/95cfeb66ab637e09d14fab3a8eeae7da052697f4

**Comment by dongluochen** [comment] 2016-05-19 19:21
@allencloud This work is tracked under #2253.

**Comment by allencloud** [comment] 2016-05-20 02:32
@dongluochen  
I am afraid more work needs to be done ranther than https://github.com/docker/swarm/issues/2253.
Because docker engine's api did not provide labels in `/volumes/{*name}`, while this has no relationship with engine-api's docker client.

More infomation : 
https://github.com/docker/docker/issues/22838
https://github.com/docker/docker/pull/22077

**Comment by alexmavr** [comment] 2016-05-20 03:05
@dongluochen @allencloud I believe this issue has surfaced two separate problems:
- GET `/volumes/id` does not return the labels for a specific volume, even though the engine does so. I believe that's what the engine-api bump would resolve in this case but feel free to correct me if that's not the case
- GET `/volumes` does not return the labels for any volume, and the engine fails to do so either

**Comment by nishanttotla** [comment] 2016-07-19 23:59
@wallnerryan This should work if you use a recent CLI and Docker Engine with Docker Swarm, as confirmed by @alexmavr. We'll close the issue today, please comment if you're unable to get it to work.

**Closed** 2016-07-19 23:59 UTC
Labels: area/volume, kind/enhancement, priority/P1

**Comment by wallnerryan** [comment] 2016-07-25 15:48
thanks @nishanttotla will try this out soon !
