### ISSUE TITLE
standard out (docker exec [-it] ...)

### ISSUE THREAD

**Issue by peebles** [docker/swarm#792] opened 2015-05-15 00:14 UTC
Seems like STDOUT isn't eactly perfect using docker talking to a swarm master.  I have a swarm cluster running in AWS.  The swarm master is running on an AWS machine.  I run docker on my laptop.  I will do something like:

    docker exec -it my-container compile-something-command

where "compile-something-command" is someting that produces maybe 100 or 200 lines of stdout.  When exec is run with "-it", seems like I get to the last line or maybe second-to-last, and *appears* to "hang", but if I hit <cr> once or twice it shows the last lines and I get my terminal prompt back.  Without "-it" it is worse ,,, it will stop producing stdout like half way and I have to hit ^C to get my prompt back, although the compile within the contain has completed.

Something strange with passing stdout around, buffering ...?

**Comment by aluzzardi** [comment] 2015-05-27 22:34
ping @jimmyxian

**Comment by jimmyxian** [comment] 2015-05-28 01:33
HI @peebles 
I tested locally, it's OK.I'm unable to reproduce the issue.
Here's what I tried to run:

```
vi /home/echo.sh
#!/bin/bash
for i in `seq 1 10`;do
  echo `date`
  sleep 1
done
```

```
[root@localhost home]# docker -H 127.0.0.1:2222 version
Client version: 1.6.0
Client API version: 1.18
Go version (client): go1.4.2
Git commit (client): 8aae715/1.6.0
OS/Arch (client): linux/amd64
Server version: swarm/0.3.0
Server API version: 1.16
Go version (server): go1.3.3
Git commit (server): HEAD
OS/Arch (server): linux/amd64

[root@localhost home]# docker -H 127.0.0.1:2222 run -d -v /home/echo.sh:/home/echo.sh --name test_container --privileged=true busybox sleep 10000
2f93091beb58dd0b7282fdc8d78bc84f3c8f659cc81856bce088abe774e39a91

[root@localhost home]# 
[root@localhost home]# docker -H 127.0.0.1:2222 exec -it test_container sh /home/echo.sh 
Thu May 28 01:44:32 UTC 2015
Thu May 28 01:44:33 UTC 2015
Thu May 28 01:44:34 UTC 2015
Thu May 28 01:44:35 UTC 2015
Thu May 28 01:44:36 UTC 2015
Thu May 28 01:44:37 UTC 2015
Thu May 28 01:44:38 UTC 2015
Thu May 28 01:44:39 UTC 2015
Thu May 28 01:44:40 UTC 2015
Thu May 28 01:44:41 UTC 2015

[root@localhost home]# docker -H 127.0.0.1:2222 exec test_container sh /home/echo.sh 
Thu May 28 01:44:50 UTC 2015
Thu May 28 01:44:51 UTC 2015
Thu May 28 01:44:52 UTC 2015
Thu May 28 01:44:53 UTC 2015
Thu May 28 01:44:54 UTC 2015
Thu May 28 01:44:55 UTC 2015
Thu May 28 01:44:56 UTC 2015
Thu May 28 01:44:57 UTC 2015
Thu May 28 01:44:58 UTC 2015
Thu May 28 01:44:59 UTC 2015
[root@localhost home]#
```
Can you provide a reproducible use case? Or try those cmd, see if they work?

**Comment by peebles** [comment] 2015-05-28 19:56
# eval $(docker-machine env --swarm staging-cluster)
# docker run -it busybox echo hello
hello

At this point I do not get back the prompt.  I must hit <CR> two times to
get the prompt back.  Both <CR>s are not echo'd back to the screen.  In
other words, after the two <CR>s my terminal looks like this:

# docker run -it busybox echo hello
hello
#

I could not try your example with the mapped volume because my cluster and
swarm master are running in AWS.

$ docker info

Containers: 34

Strategy: spread

Filters: affinity, health, constraint, port, dependency

Nodes: 3

 staging-cnode1: 172.30.0.101:2376

  └ Containers: 11

  └ Reserved CPUs: 0 / 2

  └ Reserved Memory: 3.25 GiB / 4.052 GiB

  └ Labels: executiondriver=native-0.2, kernelversion=3.13.0-40-generic,
operatingsystem=Ubuntu 14.04.1 LTS, provider=amazonec2, storagedriver=aufs

 staging-cnode2: 172.30.0.193:2376

  └ Containers: 11

  └ Reserved CPUs: 0 / 2

  └ Reserved Memory: 3.75 GiB / 4.052 GiB

  └ Labels: executiondriver=native-0.2, kernelversion=3.13.0-40-generic,
operatingsystem=Ubuntu 14.04.1 LTS, provider=amazonec2, storagedriver=aufs

 staging-cnode3: 172.30.0.231:2376

  └ Containers: 12

  └ Reserved CPUs: 0 / 2

  └ Reserved Memory: 3.75 GiB / 4.052 GiB

  └ Labels: executiondriver=native-0.2, kernelversion=3.13.0-40-generic,
operatingsystem=Ubuntu 14.04.1 LTS, provider=amazonec2, storagedriver=aufs

$ docker version

Client version: 1.6.0

Client API version: 1.18

Go version (client): go1.4.2

Git commit (client): 4749651

OS/Arch (client): darwin/amd64

Server version: swarm/0.3.0

Go version (server): go1.3.3

Git commit (server): 38a1708

OS/Arch (server): linux/amd64

**Comment by jimmyxian** [comment] 2015-05-30 00:15
Please include:

* swarm --version
* docker -H <swarm address> info
* docker -H <docker address> info
* entire swarm manage command-line (with options)
* entire swarm join command-line (with options)
* Where is swarm running?
* Where is docker running?
* Are they on the same machine?
What's the address of the Docker engine?

**Comment by peebles** [comment] 2015-05-30 02:51
I am not using a "swarm" binary, I am using the swarm container (see
below).

So I start out by creating four machines using docker-machine, like this:

    docker-machine create --driver amazonec2 \

                   --amazonec2-access-key $AWS_KEY \

                   --amazonec2-secret-key $AWS_SECRET \

                   --amazonec2-vpc-id $VPC \

                   --amazonec2-region $REGION \

                   --amazonec2-zone $ZONE \

                   --amazonec2-security-group $PRIVATE_SG \

                   --amazonec2-instance-type $ITYPE \

                   $NODE1_NAME

Three of these will act as my cluster, the forth will act as the swarm
master.  I run Consul on all four nodes.  I then run the following command
on each one of the three cluster nodes:

docker run --restart=always -d --name=swarm-agent -v
/etc/docker:/etc/docker swarm:master join --addr=${NODE1}:2376
consul://${NODE1}:8500/swarm

and on the fourth machine:

docker run --restart=always -d -p 3376:3376 --name=swarm-master \

       -v /etc/docker:/etc/docker swarm:master manage \

       --tlscacert=/etc/docker/ca.pem --tlscert=/etc/docker/server.pem \

       --tlskey=/etc/docker/server-key.pem --tls \

       -H tcp://0.0.0.0:3376 consul://${NODE1}:8500/swarm

If I "ssh" into one of these "swarm containers" and run "swarm
--version": swarm
version 0.3.0 (38a1708)

The version of docker running on the cluster nodes in AWS is 1.6.0.

Now, when I run docker commands against this cluster in AWS, I am running
docker 1.6.0 on my Mac OS X macbook pro.  First I:

  # eval $(docker-machine env --swarm staging-cluster)

Then

  # docker exec -it <container> <command>

On my laptop:

  # docker info

Containers: 34

Strategy: spread

Filters: affinity, health, constraint, port, dependency

Nodes: 3

 staging-cnode1: 172.30.0.101:2376

  └ Containers: 11

  └ Reserved CPUs: 0 / 2

  └ Reserved Memory: 3.25 GiB / 4.052 GiB

  └ Labels: executiondriver=native-0.2, kernelversion=3.13.0-40-generic,
operatingsystem=Ubuntu 14.04.1 LTS, provider=amazonec2, storagedriver=aufs

 staging-cnode2: 172.30.0.193:2376

  └ Containers: 11

  └ Reserved CPUs: 0 / 2

  └ Reserved Memory: 3.75 GiB / 4.052 GiB

  └ Labels: executiondriver=native-0.2, kernelversion=3.13.0-40-generic,
operatingsystem=Ubuntu 14.04.1 LTS, provider=amazonec2, storagedriver=aufs

 staging-cnode3: 172.30.0.231:2376

  └ Containers: 12

  └ Reserved CPUs: 0 / 2

  └ Reserved Memory: 3.75 GiB / 4.052 GiB

  └ Labels: executiondriver=native-0.2, kernelversion=3.13.0-40-generic,
operatingsystem=Ubuntu 14.04.1 LTS, provider=amazonec2, storagedriver=aufs

**Comment by jimmyxian** [comment] 2015-06-01 01:14
@peebles 
Can you try this in fourth machine(swarm manager):
Using `--net=host` instead of `-p 3376:3376 `, and see if it works.
```
docker run --restart=always -d --net=host --name=swarm-master \
	-v /etc/docker:/etc/docker swarm:master manage \
	--tlscacert=/etc/docker/ca.pem --tlscert=/etc/docker/server.pem \
	--tlskey=/etc/docker/server-key.pem --tls \
	-H tcp://0.0.0.0:3376 consul://${NODE1}:8500/swarm
```

**Comment by peebles** [comment] 2015-06-01 16:33
I get the same result.  Does not seem to make any difference.
a

**Comment by peebles** [comment] 2015-06-07 17:11
Any input on this topic?  The stdio things is starting to really give me
grief when trying to script docker commands for the cluster.  The commands
fired with -it will not complete.
a

**Comment by jimmyxian** [comment] 2015-06-08 00:28
@peebles I'm trying to reproduce locally, but can not.
Can you provide the debug info about swarm and docker deamon.

**Comment by TMaddox** [comment] 2015-06-25 16:41
Wondering if I'm hitting the issue described here. If I try to do something like:
```
tar -cv * | docker run -i -w /tmp --volumes-from=data busybox tar -xv
```
Here's the output:
```
# tar -cv * | docker run -i -w /tmp --volumes-from=data busybox tar -xv
a testdir
a testdir/file1
a testdir/file2

```
It just hangs here and never completes.

This works fine when talking to a remote Docker API, but not when talking to a Swarm cluster.

**Comment by aluzzardi** [comment] 2015-08-06 00:58
@peebles @thomasem Where is your client running (as in, OSX or whatnot)?

**Comment by peebles** [comment] 2015-08-06 02:17
OSX.  Stock terminal app. Still having same problem with docker 1.7.1.

**Comment by thomasem** [comment] 2015-08-06 14:50
I'm pretty sure I've seen this on my client on both Ubuntu and OS X. This particular reproduction was on OS X, however. I'll confirm the other and report back. :)

**Comment by micheletedeschi** [comment] 2015-10-28 11:01
Same problem. I have two nodes on virtualbox created with docker machine on OSX. I use Weave works on top of Swarm.

```bash
# docker `docker-machine config --swarm cluster-1` version
Client:
 Version:      1.8.1
 API version:  1.20
 Go version:   go1.4.2
 Git commit:   d12ea79
 Built:        Thu Aug 13 02:49:29 UTC 2015
 OS/Arch:      darwin/amd64

Server:
 Version:      swarm/0.4.0
 API version:  1.16
 Go version:   go1.4.2
 Git commit:   d647d82
 Built:
 OS/Arch:      linux/amd64
```

```bash
# docker `docker-machine config --swarm cluster-1` info
Containers: 15
Images: 26
Role: primary
Strategy: spread
Filters: affinity, health, constraint, port, dependency
Nodes: 2
 cluster-1: 192.168.99.100:12375
  └ Containers: 6
  └ Reserved CPUs: 0 / 1
  └ Reserved Memory: 0 B / 1.022 GiB
  └ Labels: executiondriver=native-0.2, kernelversion=4.0.9-boot2docker, operatingsystem=Boot2Docker 1.8.1 (TCL 6.3); master : 7f12e95 - Thu Aug 13 03:24:56 UTC 2015, provider=virtualbox, storagedriver=aufs
 cluster-2: 192.168.99.101:12375
  └ Containers: 9
  └ Reserved CPUs: 0 / 1
  └ Reserved Memory: 0 B / 1.022 GiB
  └ Labels: executiondriver=native-0.2, kernelversion=4.0.9-boot2docker, operatingsystem=Boot2Docker 1.8.1 (TCL 6.3); master : 7f12e95 - Thu Aug 13 03:24:56 UTC 2015, provider=virtualbox, storagedriver=aufs
CPUs: 2
Total Memory: 2.043 GiB
Name: cluster-1
```

I've create a test container with this command:
```bash
docker run -d --name=pingme gliderlabs/alpine nc -p 4000 -ll -e echo 'Hello, Weave!'
```

if I use swarm endpoint the command execute, I see the command output but I need to send **Enter** twice to see the prompt, no problem with other endpoints.

```bash
$ docker `docker-machine config --swarm cluster-1` exec -it pingme ls
bin      etc      lib      media    proc     run      sys      usr      w
dev      home     linuxrc  mnt      root     sbin     tmp      var
```

If I run exec with weave or docker endpoint all working fine
```bash
$ docker `docker-machine config cluster-1` exec -it pingme ls
bin      etc      lib      media    proc     run      sys      usr      w
dev      home     linuxrc  mnt      root     sbin     tmp      var
$
```

I've tried with --host or -p 3376:3376 on swarm master but the problem persit.

I run swarm master with this command:
```bash
docker run -d --restart=always --name=/swarm-agent-master --net=host -v /var/lib/boot2docker:/var/lib/boot2docker swarm manage --tlsverify --tlscacert=/var/lib/boot2docker/ca.pem --tlscert=/var/lib/boot2docker/server.pem --tlskey=/var/lib/boot2docker/server-key.pem -H tcp://0.0.0.0:3376 --strategy spread token://f1ff6179c64367b16d126e65a8e7e547
```

**Comment by cpuguy83** [comment] 2015-10-28 13:39
This should be fixed in 1.0.0-rc2 (and master)

**Comment by abronan** [comment] 2015-10-28 15:01
Yes this one should indeed be fixed (thanks @cpuguy83 :), closing this one for now but feel free to comment if you have any more issues related to `exec`/`attach`. Thanks!

**Closed by abronan** 2015-10-28 15:01 UTC
Labels: area/API, kind/bug, priority/P2

**Comment by micheletedeschi** [comment] 2015-10-28 15:16
Thanks!

**Comment by aluzzardi** [comment] 2015-10-28 20:36
@micheletedeschi Hey, you can try the latest master build by running `docker run dockerswarm/swarm:master` instead of `docker run swarm`

**Comment by micheletedeschi** [comment] 2015-10-29 15:02
@aluzzardi With dockerswarm/swarm:master works!

**Comment by peebles** [comment] 2015-10-29 18:32
Works for me too.
a
