### ISSUE TITLE
Tight loop due to duplicated "/etc/docker/key.json"

### ISSUE THREAD

**Issue by thefallentree** [docker/swarm#657] opened 2015-04-22 08:11 UTC
Hi,

We ran into a issue where multiple docker machines have same /etc/docker/key,json , caused by cloning. 

And swarm doesn't handle this issue well, it will use ~30% cpu keep looping containers from those machines, driving docker daemon cpu to 100%.

While it is a issue with configuration, but it would be nice to fix the tight loop.

Cheers.

**Comment by vieux** [comment] 2015-06-11 22:11
@thefallentree I cannot reproduce the problem, can you still reproduce with 0.3.0-rc2 ?

Althouth I found an issue that might help your problem: #657

**Comment by aluzzardi** [comment] 2015-08-04 23:52
ping @vieux

**Comment by vieux** [comment] 2015-08-06 00:50
@thefallentree can you try with swarm 0.4-rc1 ? it seems fixed to me.

**Comment by vieux** [comment] 2015-08-06 00:51
I see I asked this already for 0.3, I'm going to close this issue. please reopen if the problem persists.

**Closed by vieux** 2015-08-06 00:51 UTC
Labels: kind/bug, priority/P1
