### ISSUE TITLE
Discovery - sync nodes and not just add the new of them.

### ISSUE THREAD

**Issue by xcrezd** [docker/swarm#486] opened 2015-03-20 16:27 UTC
cluster.go

In the source code of newEntries func i see that its only adds new nodes to the cluster
For example if i use FileDiscovery and have 3 nodes in nodes.txt file
172.54.12.5:2375
172.54.12.6:2375
172.54.12.7:2375

newEntries will add them to the cluster. We have situation then we need to remove our node(we dont want to use it again) so the new nodes.txt will be like this

172.54.12.5:2375
172.54.12.6:2375

newEntries will not remove the latest node (172.54.12.7:2375) from the cluster.

----NEXT----

So in our situation we just terminated the last node by our will - we dont want to use him again.

node.go
refreshLoop func will mark the node as not healthy, and will loop the func again and again for dead node.

What are the right approach to hande this type of situation?
Maybe we should add the logic for removing nodes that are not in the list of discovery service?

**Comment by vieux** [comment] 2015-03-20 16:52
It's a duplicate of https://github.com/docker/swarm/issues/197, it's in our roadmap, it'll come very soon.

**Closed** 2015-03-20 16:52 UTC
Labels: duplicate
