### ISSUE TITLE
swarm hangs in some cases

### ISSUE THREAD

**Issue by riuvshin** [docker/swarm#2208] opened 2016-05-04 12:31 UTC
Hi guys!
we have problems with swarm it just hangs every 10-20 mins.

Output of ```docker version```:

```
docker -H localhost:23750 version
Client:
 Version:      1.8.2
 API version:  1.20
 Package Version: docker-1.8.2-7.el7.centos.x86_64
 Go version:   go1.4.2
 Git commit:   bb472f0/1.8.2
 Built:        
 OS/Arch:      linux/amd64

Server:
 Version:      swarm/1.2.1
 API version:  1.22
 Package Version: 
 Go version:   go1.6.2
 Git commit:   584e10c
 Built:        Sat Apr 23 05:13:23 UTC 2016
 OS/Arch:      linux/amd64
```
Output of ```docker info```:
```
docker -H localhost:23750 info
Containers: 0
Images: 27
Role: primary
Strategy: spread
Filters: health, port, dependency, affinity, constraint
Nodes: 2
 node1-intest.codenvy-stg.com: node1.intest.codenvy-stg.com:2375
  └ Status: Healthy
  └ Containers: 0
  └ Reserved CPUs: 0 / 4
  └ Reserved Memory: 0 B / 28.85 GiB
  └ Labels: executiondriver=native-0.2, kernelversion=3.10.0-327.4.5.el7.x86_64, operatingsystem=CentOS Linux 7 (Core), storagedriver=devicemapper
  └ Error: (none)
  └ UpdatedAt: 2016-05-04T12:10:38Z
  └ ServerVersion: 1.8.2
 node2-intest: node2.intest.codenvy-stg.com:2375
  └ Status: Healthy
  └ Containers: 0
  └ Reserved CPUs: 0 / 4
  └ Reserved Memory: 0 B / 28.85 GiB
  └ Labels: executiondriver=native-0.2, kernelversion=3.10.0-327.4.5.el7.x86_64, operatingsystem=CentOS Linux 7 (Core), storagedriver=devicemapper
  └ Error: (none)
  └ UpdatedAt: 2016-05-04T12:10:25Z
  └ ServerVersion: 1.8.2
Kernel Version: 3.10.0-327.4.5.el7.x86_64
Operating System: linux
CPUs: 8
Total Memory: 57.7 GiB
Name: intest
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
We can reproduce this on aws, azure, VBox + vagrant
We have 2 nodes connected using discovery by file
We run swarm like this ```/usr/local/swarm/swarm --log-level debug manage -H 0.0.0.0:23750 file:///usr/local/swarm/node_list 2>> /var/log/swarm.log``` (no as container)

**Steps to reproduce:**
We still trying to reproduce it on plain swarm/docker without our application. For now we can only explain what is happening within integration. But we can describe what we actually do with our integration. So basically we invoke swarm API to launch containers and execute execs inside with logs streaming of execs. our use case looks like:

-  create container
-  start container
-  create exec
-  start exec (we stream exec logs here to the client)
-  stop container
-  remove container

While we continuously running that scenario for some amount of users like ~20 in same time, swam just hangs and became unresponsive it is not possible even execute ```curl localhost:23750/info``` it just hangs. **Only swarm restart helps** and it looks like some leak or lock.

Here is swarm log output in debug mode:
http://pastebin.com/raw/jrw1N93b

**Important**
Once swarm is hang it does not respond on any API call each request just freeze for a while but in swarm logs we can see that swarm accept those calls like
```time="2016-05-04T12:27:20Z" level=debug msg="HTTP request received" method=GET uri="/info"```

It looks like swarm become unresponsive when we perform stopping / starting containers

Please feel free to ask any questions.

**Comment by dongluochen** [comment] 2016-05-04 16:56
Thanks for reporting the issue! I'll run test to see if I can reproduce.

**Comment by allencloud** [comment] 2016-05-04 17:36
can you use `curl localhost:23750/_ping` ?
Any response?
@riuvshin

**Comment by riuvshin** [comment] 2016-05-04 18:13
@allencloud Hi, huge thanks for the attention here
executing ```curl localhost:23750/_ping``` gives ```OK```
while ```curl localhost:23750/info``` hangs forever.

**Comment by garagatyi** [comment] 2016-05-04 18:17
BTW docker API on all nodes responds to all requests even when Swarm hangs.

**Comment by dongluochen** [comment] 2016-05-04 23:17
@riuvshin @garagatyi What resources do your containers use? Do they involve network endpoints like overlay? 

I've been running similar workload for more than an hour without reproduce. If it's easy for you to reproduce, can you start swarm manager with `debug` option (not loglevel) like `swarm --debug manage ...`? You can use the following command to print goroutine stack `curl swarm-manager:port/debug/pprof/goroutine?debug=1`. It'd be very helpful if you can provide the call stack.

**Comment by riuvshin** [comment] 2016-05-05 05:32
Hi @dongluochen  here is the trace:
http://pastebin.com/raw/D4Eqx8Pn

**Comment by garagatyi** [comment] 2016-05-05 06:43
We use default network + add 2 volumes with default impl into each container

**Comment by riuvshin** [comment] 2016-05-05 06:53
@dongluochen here is some more info, to reproduce this locally on vagrant based environment we run that scenario for ~5 hrs while on cloud environment both azure and aws it takes ~2mins. Maybe some latency somehow related here...

**Comment by dongluochen** [comment] 2016-05-05 07:27
@riuvshin @garagatyi Thanks a lot for the call stack and information! I can create a deadlock consistently by inserting some delay in code. It's caused by a race condition on the use of Swarm Cluster.RWMutex. A goroutine acquires RLock() twice, if another goroutine issues a Lock() request in between, it results in a dead lock. 

I'll submit a PR tomorrow.

**Comment by riuvshin** [comment] 2016-05-05 07:30
@dongluochen what a great news! thanks a lot!

**Comment by dongluochen** [comment] 2016-05-06 01:59
@riuvshin @garagatyi `swarm:1.2.2-rc1` is released. It'd be great if you can test this image (or latest code) with your workload to see if the hang problem is resolved. Appreciate your effort.

**Comment by dongluochen** [comment] 2016-05-06 02:11
Let's keep the issue open to wait for confirmation.

**Comment by riuvshin** [comment] 2016-05-06 10:38
Hi @dongluochen, I've finished my load test (in 2hrs ~1800 iterations) with 0 errors, before fix that test was killing swarm in few mins, so looks VERY good!
Huge thanks to you guys! Issue can be closed.

**Comment by nishanttotla** [comment] 2016-05-06 15:46
@riuvshin awesome, thanks for confirming and your efforts!

Closing issue @dongluochen 🎉 🎉

**Closed by nishanttotla** 2016-05-06 15:46 UTC
Labels: kind/bug, priority/P1
