### ISSUE TITLE
Docker/swarm API authentication - user/passwd credentials

### ISSUE THREAD

**Issue by bluishpe** [docker/swarm#1667] opened 2016-01-22 05:01 UTC
Hello,
    Do you know if its possible to access docker or swarm only after entering username and password for it? Is there any way to do it?

Regards

**Comment by nishanttotla** [comment] 2016-01-25 21:20
@bluishpe this looks like a duplicate of #1511, so I'm closing it. If it's different, please let us know.

**Closed** 2016-01-25 21:21 UTC
