### ISSUE TITLE
Docker Swarm reschedules but does not start container

### ISSUE THREAD

**Issue by erkules** [docker/swarm#2348] opened 2016-06-13 13:06 UTC
~~~
$ docker  -H tcp://192.168.99.100:4000  version
Client:
 Version:      1.11.1
 API version:  1.23
 Go version:   go1.5.4
 Git commit:   5604cbe
 Built:        Wed Apr 27 00:34:20 2016
 OS/Arch:      linux/amd64

Server:
 Version:      swarm/1.2.3
 API version:  1.22
 Go version:   go1.5.4
 Git commit:   eaa53c7
 Built:        Fri May 27 17:25:03 UTC 2016
 OS/Arch:      linux/amd64
~~~
~~~
$ docker  -H tcp://192.168.99.101:2375  version
Client:
 Version:      1.11.1
 API version:  1.23
 Go version:   go1.5.4
 Git commit:   5604cbe
 Built:        Wed Apr 27 00:34:20 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.11.2
 API version:  1.23
 Go version:   go1.5.4
 Git commit:   b9f10c9
 Built:        Wed Jun  1 21:20:08 2016
 OS/Arch:      linux/amd64
~~~
~~~
$ docker  -H tcp://192.168.99.100:4000   run -d --label deploy=blue -l 'com.docker.swarm.reschedule-policies=["on-node-failure"]'  --restart always --
net vxlan  --name www1 nginx                                               
5919cff7998c5475ea9ef458e7cb6a0ffeebd052dc6b042b6fcc889acda8267f

$ docker  -H tcp://192.168.99.100:4000   run -d --label deploy=blue -e resc
hedule:on-node-failure --restart always --net vxlan  --name www10 nginx    
cb224d98d8456b37318c4b7c8ae40f069c25ce5237f15b6f202eb8bef2db822d
~~~
Then killing the node the container run on:
(manage logs)
~~~
time="2016-06-13T12:53:27Z" level=error msg="Flagging engine as unhealthy. Connect failed 1 times" id="MFDP:536X:FSZG:SQKT:FV6Z:R5ZV:SVSJ:4LYJ:RFFH:JTGO:AIKB:2ZWC" name=node3 
time="2016-06-13T12:53:27Z" level=info msg="Rescheduled container 5919cff7998c5475ea9ef458e7cb6a0ffeebd052dc6b042b6fcc889acda8267f from node3 to node1 as 054eff2769fae553c90d2331a3751d0c8aeb1e9ff3732369176ef5d0022b414a" 
time="2016-06-13T12:53:27Z" level=info msg="Rescheduled container cb224d98d8456b37318c4b7c8ae40f069c25ce5237f15b6f202eb8bef2db822d from node3 to node1 as 6d164766090e7e316fa873aa47280c01f24b1857af47cb5b501a49720c8ca20d" 
~~~

~~~
root@node1:~# docker ps -a
CONTAINER ID        IMAGE               COMMAND                  CREATED             STATUS                          PORTS               NAMES
6d164766090e        nginx               "nginx -g 'daemon off"   6 minutes ago       Created                                             www10
054eff2769fa        nginx               "nginx -g 'daemon off"   6 minutes ago       Created                                             www1
~~~

As a fact they are not started.

**Comment by composer22** [comment] 2016-06-13 15:20
This has been reported as an **overlay** network issue.

But I am seeing issues with Bridge networks as well. Sometimes it works; most times it doesn't and I am unable to locate any root cause in the logs.

**Comment by erkules** [comment] 2016-06-13 19:54
thx

**Comment by nishanttotla** [comment] 2016-06-14 20:55
Closing this issue in favor of #2133 and #2149. Let's continue the discussion there.

**Closed by nishanttotla** 2016-06-14 20:55 UTC
