### ISSUE TITLE
swarm rescheduling doesnt work with overlay networks

### ISSUE THREAD

**Issue by slawekgh** [docker/swarm#2149] opened 2016-04-20 10:49 UTC
I have 2 swarm nodes SwarmNode#1  and SwarmNode#2 
I created 8 containers , 4 of them with regular network, 4 of them with overlay network 
next I simulated downtime for SwarmNode#1 

after that swarm rescheduled only these containers which dont have overlay network 

for those which has overlay there is log in swarm manage:

Failed to start rescheduled container XXXXX: 500 Internal Server Error: service endpoint with name ubuntu07 already exists
Failed to start rescheduled container XXXXX: 500 Internal Server Error: service endpoint with name ubuntu06 already exists

**Comment by doronp** [comment] 2016-04-20 18:58
@slawekgh I would like to have a look. Can you please provide Steps to reproduce, Docker Swarm, versions etc (regular detailed bug report) .

From what you have included my guess would be that in the Engine the network ubuntu07 (it is a network right?) is being recreated when it shouldn't be...

I would assume that you actually created the networks along with the containers and that Swarm is actually redoing the create along with the network.

Any way I will need your inputs to be certain and on the same page and will fix it when in a few if needed.
Cheers,
Doronp

**Comment by slawekgh** [comment] 2016-04-21 07:57
I have 3 nodes:
gmbNode01 - swarm master + consul 
gmbNode02 - swarm node #1
gmbNode03 - swarm node #2

gmbNode01 - 10.3.0.10
gmbNode02 - 10.3.0.11
gmbNode03 - 10.3.0.12

=====================================
docker info for all 3 nodes:

root@gmbNode01:~# docker info
Containers: 13
 Running: 11
 Paused: 0
 Stopped: 2
Images: 13
Server Version: 1.11.0
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 97
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge null host
Kernel Version: 4.2.0-23-generic
Operating System: Ubuntu 15.10
OSType: linux
Architecture: x86_64
CPUs: 1
Total Memory: 1.636 GiB
Name: gmbNode01
ID: xxx
Docker Root Dir: /var/lib/docker
Debug mode (client): false
Debug mode (server): false
Registry: https://index.docker.io/v1/
WARNING: No swap limit support

=====
root@gmbNode02:~# docker info
Containers: 1
 Running: 1
 Paused: 0
 Stopped: 0
Images: 6
Server Version: 1.11.0
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 38
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: overlay bridge null host
Kernel Version: 4.2.0-23-generic
Operating System: Ubuntu 15.10
OSType: linux
Architecture: x86_64
CPUs: 1
Total Memory: 1.636 GiB
Name: gmbNode02
ID: xxx
Docker Root Dir: /var/lib/docker
Debug mode (client): false
Debug mode (server): false
Registry: https://index.docker.io/v1/
WARNING: No swap limit support
Cluster store: consul://10.3.0.10:8500
Cluster advertise: 10.3.0.11:2375
root@gmbNode02:~#


====
root@gmbNode03:~# docker info
Containers: 1
 Running: 1
 Paused: 0
 Stopped: 0
Images: 3
Server Version: 1.11.0
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 15
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: overlay host bridge null
Kernel Version: 4.2.0-23-generic
Operating System: Ubuntu 15.10
OSType: linux
Architecture: x86_64
CPUs: 1
Total Memory: 1.636 GiB
Name: gmbNode03
ID: xxx
Docker Root Dir: /var/lib/docker
Debug mode (client): false
Debug mode (server): false
Registry: https://index.docker.io/v1/
WARNING: No swap limit support
Cluster store: consul://10.3.0.10:8500
Cluster advertise: 10.3.0.12:2375

=====================================
swarm info:


root@gmbNode01:~# docker -H tcp://0.0.0.0:5000 info
Containers: 2
 Running: 2
 Paused: 0
 Stopped: 0
Images: 9
Server Version: swarm/1.2.0
Role: primary
Strategy: spread
Filters: health, port, dependency, affinity, constraint
Nodes: 2
 gmbNode02: 10.3.0.11:2375
  └ Status: Healthy
  └ Containers: 1
  └ Reserved CPUs: 0 / 1
  └ Reserved Memory: 0 B / 1.718 GiB
  └ Labels: executiondriver=, kernelversion=4.2.0-23-generic, operatingsystem=Ubuntu 15.10, storagedriver=aufs
  └ Error: (none)
  └ UpdatedAt: 2016-04-21T07:38:43Z
  └ ServerVersion: 1.11.0
 gmbNode03: 10.3.0.12:2375
  └ Status: Healthy
  └ Containers: 1
  └ Reserved CPUs: 0 / 1
  └ Reserved Memory: 0 B / 1.718 GiB
  └ Labels: executiondriver=, kernelversion=4.2.0-23-generic, operatingsystem=Ubuntu 15.10, storagedriver=aufs
  └ Error: (none)
  └ UpdatedAt: 2016-04-21T07:39:11Z
  └ ServerVersion: 1.11.0
Plugins:
 Volume:
 Network:
Kernel Version: 4.2.0-23-generic
Operating System: linux
Architecture: amd64
CPUs: 2
Total Memory: 3.437 GiB
Name: 4d7adc8e5ca0
Docker Root Dir:
Debug mode (client): false
Debug mode (server): false
WARNING: No kernel memory limit support


=======================================
I create overlay network:

root@gmbNode01:~# docker network ls
NETWORK ID          NAME                        DRIVER
da63a70e8095        gmbNode02/bridge            bridge
74afd057b75d        gmbNode02/docker_gwbridge   bridge
37a50a448390        gmbNode02/host              host
541175d7da98        gmbNode02/none              null
e4f490fa927c        gmbNode03/bridge            bridge
72c28ba240ef        gmbNode03/docker_gwbridge   bridge
09ad30f81b4d        gmbNode03/host              host
56ce9ba13635        gmbNode03/none              null

root@gmbNode01:~# docker network create --subnet=192.168.10.0/24 overlay_network_00
fb04faea67c584d029b060bf1d9bb47df60e96fec08b5be58e7469b60f9293c2

root@gmbNode01:~# docker network ls
NETWORK ID          NAME                        DRIVER
da63a70e8095        gmbNode02/bridge            bridge
74afd057b75d        gmbNode02/docker_gwbridge   bridge
37a50a448390        gmbNode02/host              host
541175d7da98        gmbNode02/none              null
e4f490fa927c        gmbNode03/bridge            bridge
72c28ba240ef        gmbNode03/docker_gwbridge   bridge
09ad30f81b4d        gmbNode03/host              host
56ce9ba13635        gmbNode03/none              null
fb04faea67c5        overlay_network_00          overlay

======================================

I create 4 containers with overlay network and 4 containers without overlay network:

root@gmbNode01:~# docker ps
CONTAINER ID        IMAGE               COMMAND             CREATED             STATUS              PORTS               NAMES


root@gmbNode01:~# for id in `echo 0 1 2 3` ; do docker run -tdi  -e reschedule:on-node-failure --net=overlay_network_00 --name=ubuntu_OV_$id ubuntu   ; done
root@gmbNode01:~# for id in `echo 0 1 2 3` ; do docker run -tdi  -e reschedule:on-node-failure --name=ubuntu_without_OV_$id ubuntu   ; done

root@gmbNode01:~# docker ps
CONTAINER ID        IMAGE               COMMAND             CREATED             STATUS              PORTS               NAMES
1d5437ba0b49        ubuntu              "/bin/bash"         7 seconds ago       Up 6 seconds                            gmbNode03/ubuntu_without_OV_3
a9b070614314        ubuntu              "/bin/bash"         8 seconds ago       Up 7 seconds                            gmbNode02/ubuntu_without_OV_2
dfad4bd5b0a0        ubuntu              "/bin/bash"         9 seconds ago       Up 8 seconds                            gmbNode03/ubuntu_without_OV_1
2d06b720ced3        ubuntu              "/bin/bash"         10 seconds ago      Up 8 seconds                            gmbNode02/ubuntu_without_OV_0
070092b5cf15        ubuntu              "/bin/bash"         26 seconds ago      Up 25 seconds                           gmbNode03/ubuntu_OV_3
775e6e312795        ubuntu              "/bin/bash"         27 seconds ago      Up 26 seconds                           gmbNode02/ubuntu_OV_2
245afdae01e7        ubuntu              "/bin/bash"         29 seconds ago      Up 27 seconds                           gmbNode03/ubuntu_OV_1
0f91e7e4e8e5        ubuntu              "/bin/bash"         30 seconds ago      Up 28 seconds                           gmbNode02/ubuntu_OV_0


=====================================
I simulate downtime for node#1 (gmbNode02), after a while it seems that swarm rescheduled only containers without overlay network:

root@gmbNode01:~# docker ps
CONTAINER ID        IMAGE               COMMAND             CREATED              STATUS              PORTS               NAMES
8545e06cf872        ubuntu              "/bin/bash"         About a minute ago   Up About a minute                       gmbNode03/ubuntu_without_OV_0
159855d8c0e3        ubuntu              "/bin/bash"         About a minute ago   Up About a minute                       gmbNode03/ubuntu_without_OV_2
1d5437ba0b49        ubuntu              "/bin/bash"         4 minutes ago        Up 4 minutes                            gmbNode03/ubuntu_without_OV_3
dfad4bd5b0a0        ubuntu              "/bin/bash"         4 minutes ago        Up 4 minutes                            gmbNode03/ubuntu_without_OV_1
070092b5cf15        ubuntu              "/bin/bash"         5 minutes ago        Up 5 minutes                            gmbNode03/ubuntu_OV_3
245afdae01e7        ubuntu              "/bin/bash"         5 minutes ago        Up 5 minutes                            gmbNode03/ubuntu_OV_1




During my test I logged swarm-manage-logs - this is output:


time="2016-04-21T07:46:02Z" level=error msg="Error monitoring events: unexpected EOF." id="AKTP:QHPG:QFCH:NAFW:ZQW4:QA26:NJBK:DLMF:4CZX:47ZQ:VD75:ATL4" name=gmbNode02
time="2016-04-21T07:46:02Z" level=error msg="Restart event monitoring." id="AKTP:QHPG:QFCH:NAFW:ZQW4:QA26:NJBK:DLMF:4CZX:47ZQ:VD75:ATL4" name=gmbNode02
time="2016-04-21T07:46:02Z" level=error msg="Error monitoring events: unexpected EOF." id="AKTP:QHPG:QFCH:NAFW:ZQW4:QA26:NJBK:DLMF:4CZX:47ZQ:VD75:ATL4" name=gmbNode02
time="2016-04-21T07:46:02Z" level=error msg="Restart event monitoring." id="AKTP:QHPG:QFCH:NAFW:ZQW4:QA26:NJBK:DLMF:4CZX:47ZQ:VD75:ATL4" name=gmbNode02
time="2016-04-21T07:46:02Z" level=error msg="Error monitoring events: unexpected EOF." id="AKTP:QHPG:QFCH:NAFW:ZQW4:QA26:NJBK:DLMF:4CZX:47ZQ:VD75:ATL4" name=gmbNode02
time="2016-04-21T07:46:02Z" level=error msg="Restart event monitoring." id="AKTP:QHPG:QFCH:NAFW:ZQW4:QA26:NJBK:DLMF:4CZX:47ZQ:VD75:ATL4" name=gmbNode02
time="2016-04-21T07:46:02Z" level=error msg="Error monitoring events: Get http://10.3.0.11:2375/v1.15/events: dial tcp 10.3.0.11:2375: getsockopt: connection refused." id="AKTP:QHPG:QFCH:NAFW:ZQW4:QA26:NJBK:DLMF:4CZX:47ZQ:VD75:ATL4" name=gmbNode02
time="2016-04-21T07:46:02Z" level=error msg="Error monitoring events: Get http://10.3.0.11:2375/v1.15/events: dial tcp 10.3.0.11:2375: getsockopt: connection refused." id="AKTP:QHPG:QFCH:NAFW:ZQW4:QA26:NJBK:DLMF:4CZX:47ZQ:VD75:ATL4" name=gmbNode02
time="2016-04-21T07:46:02Z" level=error msg="Error monitoring events: Get http://10.3.0.11:2375/v1.15/events: dial tcp 10.3.0.11:2375: getsockopt: connection refused." id="AKTP:QHPG:QFCH:NAFW:ZQW4:QA26:NJBK:DLMF:4CZX:47ZQ:VD75:ATL4" name=gmbNode02
time="2016-04-21T07:46:34Z" level=error msg="Restart event monitoring." id="AKTP:QHPG:QFCH:NAFW:ZQW4:QA26:NJBK:DLMF:4CZX:47ZQ:VD75:ATL4" name=gmbNode02
time="2016-04-21T07:46:34Z" level=error msg="Error monitoring events: Get http://10.3.0.11:2375/v1.15/events: dial tcp 10.3.0.11:2375: getsockopt: connection refused." id="AKTP:QHPG:QFCH:NAFW:ZQW4:QA26:NJBK:DLMF:4CZX:47ZQ:VD75:ATL4" name=gmbNode02
time="2016-04-21T07:46:45Z" level=error msg="Restart event monitoring." id="AKTP:QHPG:QFCH:NAFW:ZQW4:QA26:NJBK:DLMF:4CZX:47ZQ:VD75:ATL4" name=gmbNode02
time="2016-04-21T07:46:45Z" level=error msg="Error monitoring events: Get http://10.3.0.11:2375/v1.15/events: dial tcp 10.3.0.11:2375: getsockopt: connection refused." id="AKTP:QHPG:QFCH:NAFW:ZQW4:QA26:NJBK:DLMF:4CZX:47ZQ:VD75:ATL4" name=gmbNode02
time="2016-04-21T07:46:59Z" level=error msg="Restart event monitoring." id="AKTP:QHPG:QFCH:NAFW:ZQW4:QA26:NJBK:DLMF:4CZX:47ZQ:VD75:ATL4" name=gmbNode02
time="2016-04-21T07:46:59Z" level=error msg="Error monitoring events: Get http://10.3.0.11:2375/v1.15/events: dial tcp 10.3.0.11:2375: getsockopt: connection refused." id="AKTP:QHPG:QFCH:NAFW:ZQW4:QA26:NJBK:DLMF:4CZX:47ZQ:VD75:ATL4" name=gmbNode02
time="2016-04-21T07:47:05Z" level=error msg="Flagging engine as unhealthy. Connect failed 3 times" id="AKTP:QHPG:QFCH:NAFW:ZQW4:QA26:NJBK:DLMF:4CZX:47ZQ:VD75:ATL4" name=gmbNode02
time="2016-04-21T07:47:05Z" level=error msg="HTTP error: Post http://10.3.0.11:2375/containers/a9b0706143140920924fcffadd2b5424afa4fc5e7692c22f31eb734b48563117/exec: dial tcp 10.3.0.11:2375: getsockopt: connection refused" status=500
time="2016-04-21T07:47:05Z" level=info msg="Rescheduled container a9b0706143140920924fcffadd2b5424afa4fc5e7692c22f31eb734b48563117 from gmbNode02 to gmbNode03 as 159855d8c0e3c24898089e3e1193ec5633947ae316c76c1ddf1abd3e04b06e1a"
time="2016-04-21T07:47:05Z" level=info msg="Container a9b0706143140920924fcffadd2b5424afa4fc5e7692c22f31eb734b48563117 was running, starting container 159855d8c0e3c24898089e3e1193ec5633947ae316c76c1ddf1abd3e04b06e1a"
time="2016-04-21T07:47:05Z" level=info msg="Rescheduled container 2d06b720ced3292e59ee32444fd43834df703dfd6c5fbd2e386b6b0e67149c47 from gmbNode02 to gmbNode03 as 8545e06cf8723069dadd869ec850c04ee9779b1f3e57aa4d211347f3da219716"
time="2016-04-21T07:47:05Z" level=info msg="Container 2d06b720ced3292e59ee32444fd43834df703dfd6c5fbd2e386b6b0e67149c47 was running, starting container 8545e06cf8723069dadd869ec850c04ee9779b1f3e57aa4d211347f3da219716"
time="2016-04-21T07:47:06Z" level=info msg="Rescheduled container 775e6e312795df03c78907f60abd0e346ef8ed7079d62a1c6c68c2b574525667 from gmbNode02 to gmbNode03 as 111f6930891d1e24414775e5fa36d93a97d1bb30899f6b4655cf1f867373805b"
time="2016-04-21T07:47:06Z" level=info msg="Container 775e6e312795df03c78907f60abd0e346ef8ed7079d62a1c6c68c2b574525667 was running, starting container 111f6930891d1e24414775e5fa36d93a97d1bb30899f6b4655cf1f867373805b"
time="2016-04-21T07:47:06Z" level=error msg="HTTP error: No such container a9b070614314" status=404
time="2016-04-21T07:47:06Z" level=error msg="Failed to start rescheduled container 111f6930891d1e24414775e5fa36d93a97d1bb30899f6b4655cf1f867373805b: 500 Internal Server Error: service endpoint with name ubuntu_OV_2 already exists\n"
time="2016-04-21T07:47:06Z" level=info msg="Rescheduled container 0f91e7e4e8e5e354bcba4085c438c9723774e7e0478f757e3f6d45d691f1577e from gmbNode02 to gmbNode03 as 1f1096aa3efcaa01616ccb94d103f201c955c9135370c860ed79f9a48bf80933"
time="2016-04-21T07:47:06Z" level=info msg="Container 0f91e7e4e8e5e354bcba4085c438c9723774e7e0478f757e3f6d45d691f1577e was running, starting container 1f1096aa3efcaa01616ccb94d103f201c955c9135370c860ed79f9a48bf80933"
time="2016-04-21T07:47:06Z" level=error msg="Failed to start rescheduled container 1f1096aa3efcaa01616ccb94d103f201c955c9135370c860ed79f9a48bf80933: 500 Internal Server Error: service endpoint with name ubuntu_OV_0 already exists\n"
time="2016-04-21T07:47:41Z" level=error msg="Restart event monitoring." id="AKTP:QHPG:QFCH:NAFW:ZQW4:QA26:NJBK:DLMF:4CZX:47ZQ:VD75:ATL4" name=gmbNode02
time="2016-04-21T07:47:41Z" level=error msg="Error monitoring events: Get http://10.3.0.11:2375/v1.15/events: dial tcp 10.3.0.11:2375: getsockopt: connection refused." id="AKTP:QHPG:QFCH:NAFW:ZQW4:QA26:NJBK:DLMF:4CZX:47ZQ:VD75:ATL4" name=gmbNode02
time="2016-04-21T07:47:56Z" level=error msg="Update engine specs failed: Cannot connect to the Docker daemon. Is the docker daemon running on this host?" id="AKTP:QHPG:QFCH:NAFW:ZQW4:QA26:NJBK:DLMF:4CZX:47ZQ:VD75:ATL4" name=gmbNode02
time="2016-04-21T07:48:05Z" level=error msg="Restart event monitoring." id="AKTP:QHPG:QFCH:NAFW:ZQW4:QA26:NJBK:DLMF:4CZX:47ZQ:VD75:ATL4" name=gmbNode02
time="2016-04-21T07:48:05Z" level=error msg="Error monitoring events: Get http://10.3.0.11:2375/v1.15/events: dial tcp 10.3.0.11:2375: getsockopt: connection refused." id="AKTP:QHPG:QFCH:NAFW:ZQW4:QA26:NJBK:DLMF:4CZX:47ZQ:VD75:ATL4" name=gmbNode02
time="2016-04-21T07:48:06Z" level=error msg="Restart event monitoring." id="AKTP:QHPG:QFCH:NAFW:ZQW4:QA26:NJBK:DLMF:4CZX:47ZQ:VD75:ATL4" name=gmbNode02
time="2016-04-21T07:48:06Z" level=error msg="Error monitoring events: Get http://10.3.0.11:2375/v1.15/events: dial tcp 10.3.0.11:2375: getsockopt: connection refused." id="AKTP:QHPG:QFCH:NAFW:ZQW4:QA26:NJBK:DLMF:4CZX:47ZQ:VD75:ATL4" name=gmbNode02

**Comment by slawekgh** [comment] 2016-04-25 13:42
Any ideas?

**Comment by slawekgh** [comment] 2016-04-26 10:06
exactly, the same case :-)

**Comment by hcguersoy** [comment] 2016-04-30 22:55
Same error here too :-(

```
time="2016-04-30T22:42:21Z" level=info msg="Removed Engine worker-10" 
time="2016-04-30T22:42:21Z" level=info msg="Rescheduled container ceeb8468227ca20f9dd5a5448b12ef593bed94036a68d55af025747271f8fc34 from worker-10 to worker-1 as 9166ebfff029f749b95506ea2db9734f522be2f64fe21f0bfa203a40e5da7150" 
time="2016-04-30T22:42:21Z" level=info msg="Container ceeb8468227ca20f9dd5a5448b12ef593bed94036a68d55af025747271f8fc34 was running, starting container 9166ebfff029f749b95506ea2db9734f522be2f64fe21f0bfa203a40e5da7150" 
time="2016-04-30T22:42:21Z" level=error msg="Failed to start rescheduled container 9166ebfff029f749b95506ea2db9734f522be2f64fe21f0bfa203a40e5da7150: 500 Internal Server Error: service endpoint with name lambda_6 already exists\n" 
time="2016-04-30T22:42:22Z" level=info msg="Rescheduled container cf03489586413655ed5cbb10c8baf723c1b60fa92e62626fdd8d090d5b892838 from worker-10 to worker-3 as e600364aa3196916799d31b06bd2720401fd33b4ff5d545d676f859ab3c15b5f" 
time="2016-04-30T22:42:22Z" level=info msg="Container cf03489586413655ed5cbb10c8baf723c1b60fa92e62626fdd8d090d5b892838 was running, starting container e600364aa3196916799d31b06bd2720401fd33b4ff5d545d676f859ab3c15b5f" 
time="2016-04-30T22:42:22Z" level=error msg="Failed to start rescheduled container e600364aa3196916799d31b06bd2720401fd33b4ff5d545d676f859ab3c15b5f: 500 Internal Server Error: service endpoint with name lambda_2 already exists\n" 
```

Running Swarm 1.2.0, Docker 1.11.1 with Overlay Network on Debian 8.

**Comment by akabdog** [comment] 2016-05-06 05:03
Same error here, rescheduler works fine when container launched as:
`docker run -d --env="reschedule:on-node-failure" --net="default" nginx
`
Fails to reschedule when specifying my overlay network:
`docker run -d --env="reschedule:on-node-failure" --net="eng-ci-network" nginx`

Error from swarm master:
`level=error msg="Failed to start rescheduled container b600a2b28cfec37891f2ab56ca63cb05e4d00c71cb98b87a80fad253c100b16a: 500 Internal Server Error: service endpoint with name thirsty_elion already exists\n"`

Environment:
CentOS 7.2
Consul 0.6.4
Docker Server/Client 1.11.1
Swarm - 1.2.0

I also tried these Swarm versions, same problem:
Swarm - 1.2.1
Swarm - 1.2.2-rc1

**Comment by everett-toews** [comment] 2016-05-13 01:43
Same. This is pretty easy to reproduce.

https://gist.github.com/everett-toews/c7e3745526276153e495aea097aa06f9#file-with-overlay-network-sh

**Comment by slawekgh** [comment] 2016-05-13 07:52
I also still have a problem with that

**Comment by doronp** [comment] 2016-05-17 09:04
Hi, again, somewhat late but I dove into this rabbit hole..
When the Engine goes down stale keys are left in the consul store and once the container is being rescheduled on a new engine (successfully)  the start command fails due to the fact that it results in an attempt to re-create already existing endpoint keys in the store.

As we don't get the full blown Engine and libnetwork API in Swarm (which is correct design IMHO) we cannot 'manually correct this situation. 

thus I tried to remove the endpoints by disconnecting the newly rescheduled container from the network before attempting to start it only to fail with:

no sandbox present for bb7e8bb22203be07b2ca6dbb61dadd35f3e5d8ea69ad481066d61b77cff97267\" \n"  status=500

I also noticed to some other anomalies with the store about which I will open other issue proabbly in the libnetwork project

Only then I bummed into this:
https://github.com/docker/docker/issues/22239

which I now assume should be fixed before the issue can be resolved on the Swarm side.

and so I guess This is mainly engine/libnetwork issue and we should probably follow:
https://github.com/docker/docker/issues/22239

**Comment by mavenugo** [comment] 2016-05-17 10:20
When swarm reschedules the containers `on-node-failure`, it should have force disconnected the endpoint from the network using the API equivalent of `docker network disconnect -f {network} {endpoint-name}`. This can be executed on any of the daemons in the cluster. From the logs above, I dont see that happening during rescheduling. 

ping @vieux.

**Comment by doronp** [comment] 2016-05-17 12:11
@mavenugo I tried that - and I got:
no sandbox present for ..
described above

Please advice

**Comment by mavenugo** [comment] 2016-05-17 15:13
@doronp that could be because a container with that same name exists in that host and is currently stopped. So, pls remove the container `docker rm -f {container}` and execute the `docker network disconnect -f` command.

**Comment by doronp** [comment] 2016-05-17 15:47
@mavenugo Will do and report back. Tnx.

**Comment by doronp** [comment] 2016-05-18 14:45
@mavenugo The container with the same name exists only after it has been rescheduled to the other node. You cannot disconnect before that was done, or cannot disconnect a container from a network via a node on which it does not reside in general - Meaning even removing it will not save you.

I managed to start the rescheduled container only after I ... well... RENAMED it.
It is then possible to rename it back.

I actually implemented this and you can review this here:
PR #2250

**Comment by mavenugo** [comment] 2016-05-18 15:12
@doronp thats not true. `docker network disconnect -f` was primarily added to assist with swarm rescheduling case and infact swarm is supposed to do that automatically on a new node even before the container is scheduled on the new node. the `-f` option will try and cleanup the endpoint from the kv-store even though the node that this command is executed on doesnt own the container.

**Comment by mavenugo** [comment] 2016-05-18 15:13
Regardless of my above workaround, Swarm should have executed the forced disconnect automatically. cc @vieux to checkout why that is not happening

**Comment by dongluochen** [comment] 2016-05-18 17:48
@doronp Can you provide reproduce steps and logs for your problem? Please include Swarm and Docker versions and `info`.

**Comment by doronp** [comment] 2016-05-19 07:22
@mavenugo I am not sure I understand you correctly.
Created overlay  network Net
Container A was on engine1 which failed.
Container A' was created on engine2 as a result of the reschedule. It has different ID but the same name.
Now since engine1 is down - on which engine you suggest to disconnect which container?
I understood this as - on engine2 disconnect A' from Network Net.
And this did not solve the problem but resulted in :
 'no sandbox present for ..' error described above when attempting to start A'
Was that your intention?

**Comment by doronp** [comment] 2016-05-19 07:29
@dongluochen 
Swarm version is the Head in this repo.
Dockers are:
Server Version: 1.11.1

Steps:

- start Consul And the engines to use it as the store
- Start Swarm 
- Create overlay network
- run a container with reschedule flag and attach it to the network created in the previous steps.
- list the containers on Swarm to see on which engine that container was scheduled and suspend that engine to trigger the reschedule.
- wait for the reschedule 
-Fail on start

Logs: Above Let me know if you need anything specific I missed

**Comment by composer22** [comment] 2016-06-12 18:16
Fails to work even with a bridge. This feature is not yet ready for a release.

No overlay NW's created over a fresh cluster with 11.2 - 8 machines.

```
version: "2"

services:
  hello_world:
    domainname: hello-world.com
    environment:
      - "constraint:com.example.role==worker"
    hostname: hello-world
    image: composer22/hello-world:latest
    labels:
      com.example.appgroup: "hello_world"
      com.docker.swarm.reschedule-policies: '["on-node-failure"]'
    logging:
      options:
        labels: "com.example.appgroup"
    mem_limit: 300M
    memswap_limit: 300M
    network_mode: "bridge"
    ports:
      - "8080"
    restart: always
    volumes:
      - /tmp:/tmp/test
```

# Run above and find node
# login and stop docker
service docker stop
...
#container is CREATED on another node but not started.
...
# startup old docker.
service docker start

# original container starts again on that node.
# now we have two containers one created not started/ the original running.

POS.

Other restart strategies result in same behavior.

**Comment by composer22** [comment] 2016-06-13 01:28
When it creates the new service, it seems to assign a network ID that doesn't exist on any of my machines. It could be a rnd() default. Don't know where to check to confirm. 

I see nothing in my logs to root cause.
```
 "Networks": {
                "bridge": {
                    "IPAMConfig": null,
                    "Links": null,
                    "Aliases": null,
                    "NetworkID": "40de49d4aa50fcf7da4a5708a8d7ce62a0b99f2e457936a14a70055671c3486b",
                    "EndpointID": "",
                    "Gateway": "",
                    "IPAddress": "",
                    "IPPrefixLen": 0,
                    "IPv6Gateway": "",
                    "GlobalIPv6Address": "",
                    "GlobalIPv6PrefixLen": 0,
                    "MacAddress": ""
                }
            }
```

**Comment by wallnerryan** [comment] 2016-06-17 15:19
@doronp any update on this for Swarm 1.2.3? Or is the status the same for rescheduling containers that use overlay nets.

**Comment by composer22** [comment] 2016-06-17 19:22
and not just OL networks -- all networks

**Comment by wallnerryan** [comment] 2016-06-17 19:52
@composer22 i've successfully rescheduled many containers that use default bridge networking, albeit without  referencing `network_mode: "bridge"` 

Also, the behaviour you are seeing where the container is CREATED but not started is because doing a docker stop actually cleanly brings the container down instead of a "failure". see https://github.com/docker/swarm/issues/1651#issuecomment-202377751

**Comment by bzon** [comment] 2016-06-19 10:06
I'm encountering this same issue using swarm cluster on Centos7 EC2s on docker 1.11.1.

I have 3 servers for 
consul backend (with consul container)
swarm manage(swarm manage container)
swarm node (swarm join container and my application containers)

The problem do happen when I start the Swarm Node server and the Consul backend is still down.

**Comment by composer22** [comment] 2016-06-22 01:33
@wallnerryan docker-compose defaults to overlay. I'll try some other means to fail the docker stop, but it DID work using this method sometimes, randomly, just not often. Will try and isolate better thx

**Comment by doronp** [comment] 2016-06-30 12:20
@wallnerryan I published PR #2250 long time ago.
it has not been merged yet...  It is out of my hands now as they say.

**Comment by composer22** [comment] 2016-07-06 17:59
I dunno. Maybe it's a non issue with 1.12's feature set for deploys?

**Comment by zbyte64** [comment] 2016-07-08 00:07
Also encountered this issue with overlay networks. I get:

`Failed to start rescheduled container cb4fa2b509ab6d4504efc00086fc1353b99af10456c28f2393100e3f9b7e8537: Error response from daemon: service endpoint with name c-rethinkdb-montage-5c9a717c_f13d_419a_ac5c_dd434e3a3107 already exists`

Swarm: 1.2.3
Docker: 1.11.2
Etcd: 2.3.7
OS: Ubuntu 15.10

**Comment by slawekgh** [comment] 2016-07-08 07:31
Is this issue still actual ? There is new docker version 1.12 with swarm bundled inside (swarm mode) 
Architecture is a little bit different but there is swarm rescheduling out of the box and works fine.

**Comment by zbyte64** [comment] 2016-07-08 23:03
@slawekgh I am still researching 1.12 . There is some significant architectural changes and lacking documentation that prevent me from simply changing version numbers (No more key value store, how do I set up multiple AZs, etc). Plan on diving in this weekend.

**Comment by doronp** [comment] 2016-07-11 08:09
@composer22 @zbyte64 @slawekgh 1.12 with its Swarm mode is a different project. As explained here:
https://github.com/docker/swarm

Both should work . Hence the issue should be resolve on all future engine version using Swarm (proxy not newer swarm mode)

**Comment by slawekgh** [comment] 2016-07-11 19:46
we have smth like engineering hazard issue, sometimes works , sometimes with the same hosts, config , ip_addrS and nodes doesnt :-)

**Closed** 2016-08-18 21:41 UTC
